### ISSUE TITLE
build errors on Fedora 12 w/ gcc 4.4.3

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#108]
On Fedora 12 with gcc 4.4.3 I encountered the following build issues:

create_build_files.sh is written in MSDOS format (LF+CR) and fails to run because of the ^M on the shabang line. It needs to be converted to unix format using: “dos2unix create_build_files.sh”. This likely effects all Linux/Unix builds.

Two source files had build errors due to missing header files (this is likely to be compiler-specific):

sdk/tinyxml/ticpp.cpp needs:

#include &lt;typeinfo&gt;
src/dbg_stack_trace/stack.cpp needs:

#include &lt;cstdlib&gt;  (for free())
#include &lt;cstring&gt;  (for strcmp())

Reported by: jfouche

**Comment by jhasse** [comment]
This should be fixed by now :)
