### ISSUE TITLE
Metal style prevents closing

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#110]
What steps will reproduce the problem? 1) Create a new dialog(a dialog, not a frame) 2) Set the metal extra style 3) Compile and run in linux(I did on Ubuntu 9.04) 4) Try to close the dialog pressing the “X” 5) Oooopz! It does NOT close!

What is the expected output? What do you see instead? 1) The dialog should close when I press the “X” window’s close system button!

Please use labels and text to provide additional information. 1) The problem is that you put this in the C++ code that generates wxFormBuilder: this→SetExtraStyle(wxDIALOG_EX_METAL);

The correct is this one: SetExtraStyle(this→GetExtraStyle()|wxDIALOG_EX_METAL); because the this→GetExtraStyle() contains the wxDIALOG_EX_MODAL used by wxGTK

thx

Reported by: jfouche

**Comment by jhasse** [comment]
Please reopen if this still happens with the latest wxFormBuilder / wxWidgets versions.
