### ISSUE TITLE
C++ in generated Python (Bug)

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#111]
Generated code: self.CanvasPanel.SetBackgroundColour( wx.SystemSettings.GetColour( wxSYS_COLOUR_BACKGROUND ) );

Correct: self.CanvasPanel.SetBackgroundColour( wx.SystemSettings.GetColour( wx.SYS_COLOUR_BACKGROUND ) )

Reported by: jfouche

**Comment by jhasse** [comment]
Please reopen if this is still happening.
