### ISSUE TITLE
A Fatal Error Occurred - all versions on Ubuntu 10.04 (LL)

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#114]
I try example from wiki: http://wiki.wxformbuilder.org/Tutorials/UsingWxFormBuilder
Every time when i renamed buttons, the error show. The error show too, when i try save project.
My system is Ubutnu 10.04 LTS Lucid Lynx with x86 generic kernel. I try three versions of wxFormBuilder:
- from default ubuntu repository - 3.1.59 - beta
- from ppa wxFormBuilder repo - 3.2.1- beta
- from direct binary download - 3.1.70
I have also allow other repositories for Pidgin, VirtualBox, Medibuntu, Skype, Opera.

Michal.

#####################
Error log from 3.1.59 - beta:
16:43:44: 000 135235406 wxformbuilder  
16:43:44: 001 1220115647 /usr/lib/libwx_baseu-2.8.so.0 wxAppConsole::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const  
16:43:44: 002 1220764713 /usr/lib/libwx_baseu-2.8.so.0 wxEvtHandler::ProcessEventIfMatches(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)  
16:43:44: 003 1220769012 /usr/lib/libwx_baseu-2.8.so.0 wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)  
16:43:44: 004 1220769267 /usr/lib/libwx_baseu-2.8.so.0 wxEvtHandler::ProcessEvent(wxEvent&)  
16:43:44: 005 1215866315 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxWindow::GTKProcessEvent(wxEvent&) const  
16:43:44: 006 1215888757 /usr/lib/libwx_gtk2u_core-2.8.so.0  
16:43:44: 007 1238906036 /usr/lib/libgtk-x11-2.0.so.0  
16:43:44: 008 1230881194 /usr/lib/libgobject-2.0.so.0 g_closure_invoke  
16:43:44: 009 1230979453 /usr/lib/libgobject-2.0.so.0  
16:43:44: 010 1230984803 /usr/lib/libgobject-2.0.so.0 g_signal_emit_valist  
16:43:44: 011 1230987090 /usr/lib/libgobject-2.0.so.0 g_signal_emit  
16:43:44: 012 1240142902 /usr/lib/libgtk-x11-2.0.so.0  
16:43:44: 013 1238874861 /usr/lib/libgtk-x11-2.0.so.0 gtk_propagate_event  
16:43:44: 014 1238880599 /usr/lib/libgtk-x11-2.0.so.0 gtk_main_do_event  
16:43:44: 015 1236575130 /usr/lib/libgdk-x11-2.0.so.0  
16:43:44: 016 1230230117 /lib/libglib-2.0.so.0 g_main_context_dispatch  
16:43:44: 017 1230246024 /lib/libglib-2.0.so.0  
16:43:44: 018 1230247367 /lib/libglib-2.0.so.0 g_main_loop_run  
16:43:44: 019 1238881369 /usr/lib/libgtk-x11-2.0.so.0 gtk_main  
16:43:44: 020 1215802792 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxEventLoop::Run()  
16:43:44: 021 1216404350 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxAppBase::MainLoop()  
16:43:44: 022 1216403313 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxAppBase::OnRun()  
16:43:44: 023 134639958 wxformbuilder  
16:43:44: A Fatal Error Occurred. Click Details for a backtrace.

#########################
Error log from 3.2.1 - beta:
16:50:18: 000 1238311929 /usr/lib/libgtk-x11-2.0.so.0 gtk_container_set_focus_child  
16:50:18: 001 1240194104 /usr/lib/libgtk-x11-2.0.so.0  
16:50:18: 002 1230941084 /usr/lib/libgobject-2.0.so.0 g_cclosure_marshal_VOID__VOID  
16:50:18: 003 1230874647 /usr/lib/libgobject-2.0.so.0  
16:50:18: 004 1230881194 /usr/lib/libgobject-2.0.so.0 g_closure_invoke  
16:50:18: 005 1230978502 /usr/lib/libgobject-2.0.so.0  
16:50:18: 006 1230985188 /usr/lib/libgobject-2.0.so.0 g_signal_emit_valist  
16:50:18: 007 1230987090 /usr/lib/libgobject-2.0.so.0 g_signal_emit  
16:50:18: 008 1240156886 /usr/lib/libgtk-x11-2.0.so.0 gtk_widget_grab_focus  
16:50:18: 009 1215876030 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxWindow::SetFocus()  
16:50:18: 010 1217157588 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxPanel::SetFocus()  
16:50:18: 011 3499860 /usr/lib/wxformbuilder/libwx_gtk2u_propgrid-2.8_wxfb.so wxWindowBase::SetFocusFromKbd()  
16:50:18: 012 1216468152 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxSetFocusToChild(wxWindow*, wxWindow**)  
16:50:18: 013 1216468246 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxControlContainer::SetFocusToChild()  
16:50:18: 014 1216468449 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxControlContainer::DoSetFocus()  
16:50:18: 015 1217157576 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxPanel::SetFocus()  
16:50:18: 016 13775893 /usr/lib/wxformbuilder/libwx_gtk2u_flatnotebook-2.8_wxfb.so wxPageContainer::DoSetSelection(unsigned int)  
16:50:18: 017 13773119 /usr/lib/wxformbuilder/libwx_gtk2u_flatnotebook-2.8_wxfb.so wxFlatNotebook::SetSelection(unsigned int)  
16:50:18: 018 13773647 /usr/lib/wxformbuilder/libwx_gtk2u_flatnotebook-2.8_wxfb.so wxPageContainer::SetSelection(unsigned int)  
16:50:18: 019 13792273 /usr/lib/wxformbuilder/libwx_gtk2u_flatnotebook-2.8_wxfb.so wxPageContainer::OnLeftDown(wxMouseEvent&)  
16:50:18: 020 1220115624 /usr/lib/libwx_baseu-2.8.so.0 wxAppConsole::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const  
16:50:18: 021 1220764713 /usr/lib/libwx_baseu-2.8.so.0 wxEvtHandler::ProcessEventIfMatches(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)  
16:50:18: 022 1220769012 /usr/lib/libwx_baseu-2.8.so.0 wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)  
16:50:18: 023 1220769267 /usr/lib/libwx_baseu-2.8.so.0 wxEvtHandler::ProcessEvent(wxEvent&)  
16:50:18: 024 1215866315 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxWindow::GTKProcessEvent(wxEvent&) const  
16:50:18: 025 1215888757 /usr/lib/libwx_gtk2u_core-2.8.so.0  
16:50:18: 026 1238906036 /usr/lib/libgtk-x11-2.0.so.0  
16:50:18: 027 1230881194 /usr/lib/libgobject-2.0.so.0 g_closure_invoke  
16:50:18: 028 1230979453 /usr/lib/libgobject-2.0.so.0  
16:50:18: 029 1230984803 /usr/lib/libgobject-2.0.so.0 g_signal_emit_valist  
16:50:18: 030 1230987090 /usr/lib/libgobject-2.0.so.0 g_signal_emit  
16:50:18: 031 1240142902 /usr/lib/libgtk-x11-2.0.so.0  
16:50:18: 032 1238874861 /usr/lib/libgtk-x11-2.0.so.0 gtk_propagate_event  
16:50:18: 033 1238880599 /usr/lib/libgtk-x11-2.0.so.0 gtk_main_do_event  
16:50:18: 034 1236575130 /usr/lib/libgdk-x11-2.0.so.0  
16:50:18: 035 1230230117 /lib/libglib-2.0.so.0 g_main_context_dispatch  
16:50:18: 036 1230246024 /lib/libglib-2.0.so.0  
16:50:18: 037 1230247367 /lib/libglib-2.0.so.0 g_main_loop_run  
16:50:18: 038 1238881369 /usr/lib/libgtk-x11-2.0.so.0 gtk_main  
16:50:18: 039 1215802792 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxEventLoop::Run()  
16:50:18: 040 1216404350 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxAppBase::MainLoop()  
16:50:18: 041 1216403313 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxAppBase::OnRun()  
16:50:18: 042 134651390 wxformbuilder  
16:50:18: A Fatal Error Occurred. Click Details for a backtrace.

#########################
Error log from 3.1.70:
16:52:34: 000 1238311929 /usr/lib/libgtk-x11-2.0.so.0 gtk_container_set_focus_child  
16:52:34: 001 1240194104 /usr/lib/libgtk-x11-2.0.so.0  
16:52:34: 002 1238343689 /usr/lib/libgtk-x11-2.0.so.0  
16:52:34: 003 1230941084 /usr/lib/libgobject-2.0.so.0 g_cclosure_marshal_VOID__VOID  
16:52:34: 004 1230874647 /usr/lib/libgobject-2.0.so.0  
16:52:34: 005 1230881194 /usr/lib/libgobject-2.0.so.0 g_closure_invoke  
16:52:34: 006 1230978502 /usr/lib/libgobject-2.0.so.0  
16:52:34: 007 1230985188 /usr/lib/libgobject-2.0.so.0 g_signal_emit_valist  
16:52:34: 008 1230987090 /usr/lib/libgobject-2.0.so.0 g_signal_emit  
16:52:34: 009 1240156886 /usr/lib/libgtk-x11-2.0.so.0 gtk_widget_grab_focus  
16:52:34: 010 1215876076 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxWindow::SetFocus()  
16:52:34: 011 11893946 /home/michal/Plocha/wxformbuilder/bin/../lib/libwx_gtk2u_propgrid-2.8_wxfb.so wxPGClipperWindow::SetFocus()  
16:52:34: 012 1216468188 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxSetFocusToChild(wxWindow*, wxWindow**)  
16:52:34: 013 1216468246 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxControlContainer::SetFocusToChild()  
16:52:34: 014 1216468449 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxControlContainer::DoSetFocus()  
16:52:34: 015 1217157576 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxPanel::SetFocus()  
16:52:34: 016 11971889 /home/michal/Plocha/wxformbuilder/bin/../lib/libwx_gtk2u_propgrid-2.8_wxfb.so wxPropertyGrid::HandleMouseClick(int, unsigned int, wxMouseEvent&)  
16:52:34: 017 11973080 /home/michal/Plocha/wxformbuilder/bin/../lib/libwx_gtk2u_propgrid-2.8_wxfb.so wxPropertyGrid::OnMouseClick(wxMouseEvent&)  
16:52:34: 018 1220115647 /usr/lib/libwx_baseu-2.8.so.0 wxAppConsole::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const  
16:52:34: 019 1220764713 /usr/lib/libwx_baseu-2.8.so.0 wxEvtHandler::ProcessEventIfMatches(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)  
16:52:34: 020 1220769012 /usr/lib/libwx_baseu-2.8.so.0 wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)  
16:52:34: 021 1220769267 /usr/lib/libwx_baseu-2.8.so.0 wxEvtHandler::ProcessEvent(wxEvent&)  
16:52:34: 022 1220769161 /usr/lib/libwx_baseu-2.8.so.0 wxEvtHandler::ProcessEvent(wxEvent&)  
16:52:34: 023 1217200006 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxScrollHelperEvtHandler::ProcessEvent(wxEvent&)  
16:52:34: 024 1215866315 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxWindow::GTKProcessEvent(wxEvent&) const  
16:52:34: 025 1215888757 /usr/lib/libwx_gtk2u_core-2.8.so.0  
16:52:34: 026 1238906036 /usr/lib/libgtk-x11-2.0.so.0  
16:52:34: 027 1230881194 /usr/lib/libgobject-2.0.so.0 g_closure_invoke  
16:52:34: 028 1230979453 /usr/lib/libgobject-2.0.so.0  
16:52:34: 029 1230984803 /usr/lib/libgobject-2.0.so.0 g_signal_emit_valist  
16:52:34: 030 1230987090 /usr/lib/libgobject-2.0.so.0 g_signal_emit  
16:52:34: 031 1240142902 /usr/lib/libgtk-x11-2.0.so.0  
16:52:34: 032 1238874861 /usr/lib/libgtk-x11-2.0.so.0 gtk_propagate_event  
16:52:34: 033 1238880599 /usr/lib/libgtk-x11-2.0.so.0 gtk_main_do_event  
16:52:34: 034 1236575130 /usr/lib/libgdk-x11-2.0.so.0  
16:52:34: 035 1230230117 /lib/libglib-2.0.so.0 g_main_context_dispatch  
16:52:34: 036 1230246024 /lib/libglib-2.0.so.0  
16:52:34: 037 1230247367 /lib/libglib-2.0.so.0 g_main_loop_run  
16:52:34: 038 1238881369 /usr/lib/libgtk-x11-2.0.so.0 gtk_main  
16:52:34: 039 1215802792 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxEventLoop::Run()  
16:52:34: 040 1216404350 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxAppBase::MainLoop()  
16:52:34: 041 1216403313 /usr/lib/libwx_gtk2u_core-2.8.so.0 wxAppBase::OnRun()  
16:52:34: 042 134641555 /home/michal/Plocha/wxformbuilder/bin/wxformbuilder  
16:52:34: A Fatal Error Occurred. Click Details for a backtrace.

Reported by: vadimosk

**Comment by jhasse** [comment]
Please try again with a new version of wxFormBuilder and reopen if this still happens.
