### ISSUE TITLE
wxMenuItem shortcut is \\t<shortcut>

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#116]
With a shortcut added to a wxMenuItem, instead of a shortcut, the XRC source has &lt;label&gt;Some menu item\\tCTRL+SOMECHAR&lt;/label&gt;. When replacing in the XRC output the \\t to a real tab, I get the desired effect.

Reported by: avl555

**Comment by jhasse** [comment]
If you can still reproduce this, please comment.
