### ISSUE TITLE
files missing from distro

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#122]
The files: libintl-8.dll and libiconv-2.dll appear to be missing from wxFormBuilder_v3.2.2-beta.exe.

I ran into this problem when installing this version on a new system. The application will not 
start without these, but I was able to copy them from a system that has had previous versions of wxFB installed.

I can't be sure, but I believe the older system first had v. 3.1.67 installed, so it could be that the defect was
introduced after that version.

Reported by: jdbosma

**Comment by jhasse** [comment]
This should be fixed now.
