### ISSUE TITLE
project unnecessarily marked as changed 

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#127]
Using 3.2.3 beta I open an fbp file, (the one here: http://svn.perlide.org/padre/trunk/Padre/Padre.fbp ) browsed around a a bit in the dialogs. When I clicked on [-] to collaps the tree of one of the dialogs (in the left pane), suddenly the project was marked as "changed" (with the * in the title bar) and no amount of Ctl-Z helped me get rid of it. When I tried to exit wxFormBuilder it told me the file has changed (so it is not only the display of the *).

Reported by: *anonymous

**Comment by jhasse** [comment]
See #382.
