### ISSUE TITLE
Names of generated classes are inconvenient

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#14]
I think the names of classes generated by FB currently do not reflect the fact, that the user is expected to derive from them. I would like to reference the frames using the names I see in the designer but FB uses them for its auto-generated base classes instead.

For example:

Project: ContactKeeper
Frames: PhoneList, EmailList

FB generates the following classes:

class PhoneList
class ContactKeeperPhoneList : public PhoneList
class EmailList
class ContactKeeperEmailList : public EmailList

I suggest the naming scheme be changed in one of the following ways:

1) class PhoneList : public ContactKeeperPhoneList

2) class PhoneList : public PhoneListBase

3) class PhoneList : public USER_DEFINED_PREFIX_HERE_PhoneList

That way we could refer to the frames in our apps using the names we see in the designer.

Reported by: jfouche

**Comment by jhasse** [comment]
I think a namespace would be the solution for this.
