### ISSUE TITLE
3.3.1-beta: Error in generated code for MSW

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#159]
Version 3.3.1-beta generates incorrect code for a wxITEM_NORMAL menu item with a bitmap:

```cpp
wxMenuItem* c_pItemFileOpen;
c_pItemFileOpen = new wxMenuItem( c_pMenuFile, wxID_ANY, wxString( _("&Open...") ) + wxT('\t') + wxT("CTRL+O"), _("Open an existing database."), wxITEM_NORMAL );
#ifdef __WXMSW__
c_pItemFileOpen->SetBitmaps( wxBitmap( wxT("gfx/icons/menu/open.ico"), wxBITMAP_TYPE_ANY ),  );
#elif defined( __WXGTK__ )
c_pItemFileOpen->SetBitmap( wxBitmap( wxT("gfx/icons/menu/open.ico"), wxBITMAP_TYPE_ANY ) );
#endif
```

"Kind" is set to "wxITEM_NORMAL", "bitmap" to "load from file" and the correct filename, "unchecked_bitmap" is set to "load from file" and the filename is blank of course as the menu item is now wxITEM_CHECK.

"Unchecked_bitmap" should only be generated if "kind" is set to "wxITEM_CHECK" according the help text within the program.

Reported by: *anonymous

**Comment by jhasse** [comment]
Please reopen, if this still happens.
