### ISSUE TITLE
Prompt for changes when there are no changes

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#163]
Hi,

this is about a very old problem, which may be "by design" in which case I kindly ask to reconsider: When opening a project and navigating the object tree, i.e. collapsing/uncollpasing nodes, wxFormbuilder sees this as a "change" in configuration. When leaving the tool it prompts to "save the changes".
This is problematic for the following reason:
From the user's point of view, collapsing tree nodes is not a change in his production data. When the save prompt comes up he may not be sure whether he has changed something, e.g. when the tool has been open for a long time, most of which the user just had a look at GUI variable names.

Now if he choses to not save, because he thinks the tool complains about tree collapsing only, he may accidentally lose real changes.
If on the other hand he choses to save, he may save a change he did unconciously e.g. he was testing new GUI layouts, generated the source, but did not want to save permanently.
Both of these problems happen sporadically, and are (considering complex and large GUI configurations) very annoying since problems become apparent only very late in UI testing, if at all.

The suggested fix is to clearly separate concerns: user data and tree view data should not be treated the same. Either view layout should not be saved at all, or it should be saved as a different layout file. Only changes in user data should bring up the "save changes" prompt.

Regards, ZenJu

Reported by: zhnmju123

**Comment by jhasse** [comment]
Duplicate of #47.
