### ISSUE TITLE
Inconsistent EOL style and whitespace

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#197]
I am using the vendor drop pattern to maintain a patch for wxFormBuilder and my svn repository uses the eol-style property (autoprops feature) to prevent line endings chaos. Every time i import a new wxFormBuilder release i get a bunch of errors about line ending mismatches i need to fix manually, it would be nice if you could fix these errors in your repository as well :).

Another problem i saw is whitespace mismatch, even during the same file there is sometimes tab and sometimes space used. This does not cause svn errors but it would be great if you could use only one type of whitespace, it makes it easier to supply patches and prevents conflicts just because of whitespace.

Reported by: sodev

**Comment by sodevel** [comment]
Fixed in v4.0.0
