### ISSUE TITLE
wxSpinCtrl missing OnSpinCtrlTextEnter event option

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#198]
wxSpinCtrl supported events are OnSpinCtrl and OnSpinCtrlText.
OnSpinCtrlTextEnter is a useful option that does not produce events on every keystroke but only after a value has been entered.

Reported by: kc64

**Comment by Kvaz1r** [comment]
Already was fixed by https://github.com/wxFormBuilder/wxFormBuilder/commit/6bbb67945373eceb66d28474ab45cd241faf9eff
