### ISSUE TITLE
Relative paths not work

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#204]
Hello,
I found another bug in the last version from PPA in Ubuntu 14.04 (same behavior in Ubuntu 13.10)
wxFB create the same paths for the images, no matter what I select in the project in the property "relative_path" check or uncheck it.
Im attaching a sample fbp file with the project property relative_path= unchecked you can see the Python code (line 26) created, with the property checked is the same code.

Reported by: mlacunza

**Comment by jhasse** [comment]
Fixed by #496.
