### ISSUE TITLE
Codegeneration outdated for wxWidgets 3.1

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#211]
The codegeneration templates and the xml files describing the object properties are out there since wxWidgets 2.8 and most of them dont have been updated for quite some time. wxWidgets is currently at version 3.1, wxFormBuilder itself cannot be compiled with wxWidgets 2.8 anymore, so i have taken the time to review ALL templates and xml files and updated them to wxWidgets 3.1 level. I have taken wxWidgets svn revision 76938 as source.

What i have done in detail:
- Reviewed all style flags, removed old ones, added new ones, renamed from old names to new names
- Reviewed all event types, added new event handlers, removed old ones. I did not add support for the new bind system, i have still to evaluate how its new features can be exposed to wxFormBuilder.
- Updated almost all help messages related to style flags and event handlers to the wording of the wxWidgets documentation
- I did not add any new controls or checked if additional parameters should be added to existing ones except i updated wxButton to support bitmaps now, wxButton is pretty much identical to wxBitmapButton now, but i kept wxBitmapButton for backward compatibility
- Updated font parameters (family, style, weight) to use the new names, this way generated code doesn't cause deprecated warnings anymore. I also updated the wxFormBuilder code itself to use the new names so compilation of wxFormBuilder also doesn't cause these warnings anymore.
- All these changes are implemented for ALL supported generation languages, including XRC, and of course the preview inside wxFormBuilder
- Updated project file version to 1.14 and implemented upgrading from the previous version

Because the codegeneration templates and the xml files had mixed whitespace and non uniform identation and because i had to edit them i took the chance to reformat every template and xml file. I have used the most commonly used style for each, that is tab inside the templates and space inside the xml files. This causes a lot of differences in the patch file but it was just too much work to seperate the whitespace changes from the functional changes.

All these changes are contained in the attached file codegen_wx31.patch.

Additionally i changed the codegeneration to use the static box of a wxStaticBoxSizer as parent for its children. However, like with the highlight patch for the designer, this was not easy and might have some side effects, therefor i made an extra patch for this, codegen_wx31_sbox.patch, this patch does not rely on the other one.

Basically the #wxparent search function now stops at a wxStaticBoxSizer and returns it, the following code generates the method call to return its static box. Usually the #wxparent macro is just used to get the name of the parent to use it as parent for the created element, but there is another case when it can be used, to extract parameters of it. This seems to be used only for the #ifnull and the like macros and it might be an issue that these return the wxStaticBoxSizer object now that isnt even a wxWindow. However the wxStaticBox is not part of the wxFormBuilder object hierarchy so there cannot be done much else. I analysed all generator templates and none seems to use #wxparent in a way that causes such a problem.

I am also not familiar with other generation languages than c++ so the method call to get the static box of the sizer might be wrong for these, but it looks pretty much like other code that gets generated for these languages :).

Reported by: sodev

**Comment by jhasse** [comment]
The patches from sourceforge. (GitHub doesn't support .patch files???)

[211.zip](https://github.com/wxFormBuilder/wxFormBuilder/files/1842065/211.zip)

**Comment by sodevel** [comment]
I have to dig up my old patch here (it was me who created it in the SourceForge days) because recently i synchronized my repository again and spend a lot of time fixing a huge amount of merge errors, most caused by whitespace and formatting differences.

I recreated the patch against 3bf169ee3b3c7476295cf3c9de0fe8fb760b503b so it is up to date with all additions that were made in the last years plus some fixes from me to these. In addition it contains all whitespace fixes `git apply` was unhappy about. It does NOT contain the wxStaticBoxSizer fixes from the second patch file, most of these are present in disabled form in the current code base anyway.

Now that time has passed and after other wxWidgets 3.1 only additions have been made in the past, maybe now its time to update the remaining elements to wxWidgets 3.1. Also it would be REALLY helpful if the project could agree on a common code style, recent changes again contain different whitspace and formatting, this makes it a really time consuming process to integrate these into an own fork (at least if its svn based like mine, don't know if its easier when its git based :o)).

[wx31_ws.zip](https://github.com/wxFormBuilder/wxFormBuilder/files/2160755/wx31_ws.zip)

**Comment by jhasse** [comment]
Thanks for the patch!

Why did you do this change though?

```diff
diff --git a/src/maingui.cpp "b/src/maingui.cpp"
index f9dddca..188a6e9 100644
--- a/src/maingui.cpp
+++ "b/src/maingui.cpp"
@@ -45,7 +45,7 @@
 #include "model/objectbase.h"
 
 #if wxVERSION_NUMBER >= 2905 && wxVERSION_NUMBER <= 3100
-#include <wx/xrc/xh_auinotbk.h>
+#include <wx/xrc/xh_aui.h>
 #elif wxVERSION_NUMBER > 3100
 #include <wx/xrc/xh_aui.h>
 #endif
@@ -213,7 +213,7 @@ int MyApp::OnRun()
 	wxInitAllImageHandlers();
 	wxXmlResource::Get()->InitAllHandlers();
 	#if wxVERSION_NUMBER >= 2905 && wxVERSION_NUMBER <= 3100
-	wxXmlResource::Get()->AddHandler(new wxAuiNotebookXmlHandler);
+	wxXmlResource::Get()->AddHandler(new wxAuiXmlHandler);
 	#elif wxVERSION_NUMBER > 3100
 	wxXmlResource::Get()->AddHandler(new wxAuiXmlHandler);
 	#endif
```

It won't compile with 3.0 then.

> Also it would be REALLY helpful if the project could agree on a common code style, recent changes again contain different whitspace and formatting, this makes it a really time consuming process to integrate these into an own fork (at least if its svn based like mine, don't know if its easier when its git based :o)).

Thanks for the suggestion. There's a `.clang-format` file in the root directory with the style I prefer (an incomplete written version: https://github.com/jhasse/cpp-style-guide), but most of the source is using different styles - very inconsistent indeed. If I would change everything now, it would mess up the history and also make applying old patches even more painful.

**Comment by jhasse** [comment]
Why did you change the default orientation of `wxWrapSizer` from `wxHORIZONTAL` to `wxVERTICAL` in layout.xml?

**Comment by jhasse** [comment]
Thanks for the explanation :)

> I don't know a good solution for this problem, but this patch already messes up the history of all xml-files and template-files and i know the pain very well that happens when i merge changes into these files.

I'm working on a pull request where I have removed any unnecessary changes. I'll ping you when it's ready so that you can have a look.

> starting parameters below the opening bracket (a style i personally really don't like)

Can you give an example? I'm not sure I understand what you mean exactly.

**Comment by sodevel** [comment]
```
void foo(int a1,
         int a2);
```

versus my preferred style

```
void foo(
   int a1,
   int a2
);
```

And about the different whitespace problems, in the first example, if the whole block would be indented with your rules you would have some TAB in the beginning of line two followed by some SPACE. Now if you rename foo and have to adjust the alignment many editors (or people :)) are dumb and replace everything with TAB and fill with SPACE if TAB alone doesn't align because of tab width.

**Comment by jhasse** [comment]
I see, so your suggestion would basically be to use spaces-only?

**Comment by sodevel** [comment]
Yes, i think it is a more foolproof solution and also works great when you do some quick edits with simple text editors, just make sure they convert all TAB into SPACE.

**Comment by jhasse** [comment]
Well tabs-vs.-spaces is a never ending debate. It looks to me that most of wxFormBuilder's code is currently using tabs, that's why I want to stick with them. And because I'm pro-tabs myself ;)

> also works great when you do some quick edits with simple text editors

In my experience people will start adding 3 or 5 spaces indents then.
