### ISSUE TITLE
System Errors

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#214]
This note is to support. I am having problems opening previously installed and newly downloaded files. It started after I logged on to GitHub and cloned one of the apps. I don't believe it is internal (vulnerability issue with Windows 7 and 8). I have not tried to build anything yet because I am still creating U/I components, but again I can't open the program. Any suggestions?

---
## See Attached- Log.Txt

12:53:46: 0x44bd1f: ObjectDatabase::LoadPlugins(boost::shared_ptr<wxFBManager>) in C:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
12:53:46: 0x46d012: ApplicationData::LoadApp() in C:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
12:53:46: 0x46d13a: ApplicationData::Initialize() in C:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
12:53:46: 0x401c3e: MyApp::OnRun() in C:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
12:53:46: 0x67b30da9: Z12wxInitializeiPPw in C:\Program Files (x86)\wxFormBuilder\wxmsw28u_gcc.dll
12:53:46: 0x67b830c1: Z7wxEntryP11HINSTANCE__S0_Pci in C:\Program Files (x86)\wxFormBuilder\wxmsw28u_gcc.dll
12:53:46: 0x4014d7: WinMain@16 in C:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
12:53:46: 0x5803d6: operator<<(std::ostream&, MD5) in C:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
12:53:46: 0x4010b6: [unknown function] in C:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
12:53:46: 0x401128: [unknown function] in C:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
12:53:46: 0x7661338a: BaseThreadInitThunk in C:\Windows\syswow64\kernel32.dll
12:53:46: 0x77239f72: RtlInitializeExceptionChain in C:\Windows\SysWOW64\ntdll.dll
12:53:46: 0x77239f45: RtlInitializeExceptionChain in C:\Windows\SysWOW64\ntdll.dll
12:53:46: A Fatal Error Occurred. Click Details for a backtrace.

Reported by: habatchii

**Comment by jhasse** [comment]
I'm unable to reproduce this. Please reopen if this still happens.
