### ISSUE TITLE
wxRichTextControl does not export class name

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#221]
I am using wxFormBuilder version: 3.5.0

I added a wxRichTextCtrl. In the xrc, the corresponding line is:

<object class="unknown" name="txt_about" />

Contrast that with the line for a wxTextCtrl:
<object class="wxTextCtrl" name="txt_info">

When I load the xrc in code, I get a wxWidgets assert at the following line:
   wxRichTextCtrl* pTxt_about = XRCCTRL(*this, "txt_about", wxRichTextCtrl);

I think the reason for this is probably class being exported as "unknown".

Reported by: victorcoorg

**Comment by Kvaz1r** [comment]
Seems like duplicate of #618

**Comment by sodevel** [comment]
Indeed, thanks for the notification
