### ISSUE TITLE
Multiple wxTimer bug

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#235]
wxTimer ID Initial should't be wx.ID_ANY, when multiple wxTimer created won't trigger any one.
And the new event for wxCombobox - EVT_COMBOBOX_DROPDOWN and EVT_COMBOBOX_CLOSEUP not implement.

Reported by: tkwl1sec

**Comment by sodevel** [comment]
Fixed in v4.0.0
