### ISSUE TITLE
wxFont::wxFont depcrecated in wxWidgets 3.1.0

### ISSUE THREAD

**Issue by jhasse** [wxFormBuilder/wxFormBuilder#240]
When setting the font of a `wxWindow` wxFormBuilder generates C++ code which generates the following warning with wxWidgets 3.1.0:

```
warning C4996: 'wxFont::wxFont': deprecated: use wxFONT{FAMILY,STYLE,WEIGHT}_XXX constants ie: wxFONTFAMILY_SWISS, wxFONTSTYLE_NORMAL, wxFONTWEIGHT_BOLD
```

**Comment by jpd236** [comment]
FYI, I think this was fixed already:

https://github.com/wxFormBuilder/wxFormBuilder/commit/feec1abbf18528ab756f099f0368895c82b135bf

**Comment by jhasse** [comment]
Thanks! Yes, it was fixed by that commit.

**Comment by Rickmc3280** [comment]
in version 3.1.3  I am getting this issue.  What would be the fix for this?

**Comment by sodevel** [comment]
Use the latest release of wxFB, it should generate up-to-date code. If not and if you are on windows you can use the latest CI build, otherwise you have to compile wxFB yourself.
