### ISSUE TITLE
Set up automated builds with Travis CI

### ISSUE THREAD

**Issue by jhasse** [wxFormBuilder/wxFormBuilder#242]
This PR needs to be merged first: https://github.com/travis-ci/apt-package-whitelist/pull/3161

Does anyone know how to make that happen?

**Comment by rjpcomputing** [comment]
Hum I don't understand what needs to happen after reading that PR. So I am not sure how to help.

**Comment by jhasse** [comment]
Basically Travis CI has a whitelist of packages one can use in their automated builds. Currently wxWidgets isn't white-listed. If it was, I could set-up automated builds for wxFormBuilder.

**Comment by rjpcomputing** [comment]
OK. I do have wxFormBuilder built for each commit on Debian and Windows, but it is not available to the world so TravisCI would be very nice. I have no idea how to work with/in TravisCI, sorry.

Thanks.

**Comment by patangl** [comment]
I already tried setting up a Travis build, but I hit the same problem.
Is it possible to download the build artifacts from the [wxWidgets Travis build](https://travis-ci.org/wxWidgets/wxWidgets
) and build wxFB using those?

If we get Travis builds to work, we should also consider doing Windows builds on Appveyor.

**Comment by patlkli** [comment]
I already tried setting up a Travis build, but I hit the same problem.
Is it possible to download the build artifacts from the [wxWidgets Travis build](https://travis-ci.org/wxWidgets/wxWidgets) and build wxFB using those?

If we get Travis builds to work, we should also consider doing Windows builds on Appveyor.

**Comment by jhasse** [comment]
>  Is it possible to download the build artifacts from the wxWidgets Travis build and build wxFB using those?

Might be, but using the packages would be the cleaner solution IMHO.

**Comment by patlkli** [comment]
I found out, that the missing whitelist entry is only relevant when using the container-based virtualization environment on Travis.

I'm using the classic sudo-enabled environment now.
Travis build should soon be up and running.

**Comment by patlkli** [comment]
I just committed the Travis build config in 7d3b96d1682c1c8e4e5c48942e8ba9fb4088998f on the cmake_build branch. This should fix this issue and will get merged to master as soon as we ensured that the CMake build system works on all platforms.
