### ISSUE TITLE
Build instructions for Windows

### ISSUE THREAD

**Issue by stampedeboss** [wxFormBuilder/wxFormBuilder#253]
Where can I find them?

**Comment by NewPagodi** [comment]
The developers currently use premake to generate the build necessary build files.  For example, to use wxWidgets 3.0 with visual studio 2010, you would open a command prompt, change to the root folder of the wxFormbuilder source, and enter something like:

.\build\premake\windows\premake4.exe --file=build/premake/solution.lua --wx-root=C:\wxWidgets-3.0.2 --wx-version=3.0 --compiler=vc  vs2010

**Comment by davidfraser** [comment]
Is there any plan to distribute Windows binaries?

**Comment by stampedeboss** [comment]
Not able to build following instructions, get error messages:
error: failed retrieving file 'perl-Net-SMTP-SSL-1.02-1-any.pkg.tar.xz' from rep                                                                                                                                                                                               o.msys2.org : Maximum file size exceeded
error: failed retrieving file 'perl-Net-SMTP-SSL-1.02-1-any.pkg.tar.xz' from dow                                                                                                                                                                                               nloads.sourceforge.net : Maximum file size exceeded
error: failed retrieving file 'perl-Net-SMTP-SSL-1.02-1-any.pkg.tar.xz' from www                                                                                                                                                                                               2.futureware.at : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.


We really need someone to provide the windows binaries.

**Comment by SpareSimian** [comment]
Looks like a pacman bug: https://bbs.archlinux.org/viewtopic.php?id=184864

**Comment by davidfraser** [comment]
Were the originally supplied Windows binaries built with MSys2 and MinGW (as specified in the build instructions recently added in #248), or with Visual Studio?

**Comment by stampedeboss** [comment]
No offense but I've been trying for weeks without success and it appears I'm not the only one.  Guess QT is it.

**Comment by rjpcomputing** [comment]
@stampedeboss 

No offence taken. Lets try the old way.

Make sure you have mingw 4.8.x and wxPack installed. You can get them from here: 
* https://github.com/rjpcomputing/wxpack/wiki
* https://drive.google.com/drive/folders/0B54E1bClDuSuTExoUXoyRmF0Z3c

1. Open a MinGW terminal: Open a command prompt and run `mingwvars.bat`
2. Change directory to wxFB source
2. Create Build Files
`create_build_files4.bat --wx-version=3.0 --compiler=mingw64 --compiler-version=48`
3. Build
`mingw32-make config=release`

**Comment by jhasse** [comment]
There are also Windows build instructions in the README: https://github.com/wxFormBuilder/wxFormBuilder/blob/master/README.md#windows-msys2
