### ISSUE TITLE
Splash screen does not go away

### ISSUE THREAD

**Issue by seppestas** [wxFormBuilder/wxFormBuilder#255]
When running wxFormBuilder on macOS the splash screen does not go away, even when running a debug build (that should not even display the splash screen judging from a [quick glance at the code](https://github.com/wxFormBuilder/wxFormBuilder/blob/master/src/maingui.cpp#L235)):
<img width="534" alt="screen shot 2016-11-10 at 10 31 56" src="https://cloud.githubusercontent.com/assets/1408377/20171760/6e925b14-a732-11e6-9873-c3319b1487d9.png">

This results in wxFormBuilder being pretty useless on a single screen setup.

__Environment:__
macOS 10.12.1
xFormBuilder v3.5 - RC2 built from 55f688f with wXWidgets 3.0.2 (wxMedia disabled)

**Comment by jhasse** [comment]
I think the start up time is fast enough nowadays that a splash screen isn't needed at all. What do you think?

Removing it completely would also "fix": Splash screen isn't HiDPI aware and the copyright date is wrong.
