### ISSUE TITLE
Windows Build Instructions missing dependencies and other issues

### ISSUE THREAD

**Issue by david-alleyn** [wxFormBuilder/wxFormBuilder#256]
This pertains to the instructions for Windows in the README.md

This also assumes that you haven't installed msys2 32-bit before following the instructions.

Problem: Parts of the package group, mingw-w64-gcc-toolchain, are also required but not installed by the provided pacman command. 

Consequence: g++, libbfq, and libiberty are not installed in the provided instructions. Making softlinks fails, compiling fails.

Solution: After installing parts of the mingw-w64-gcc-toolchain, it is then possible to link libbfq and libiberty to their respective locations, and compilation is possible.

Additionally:

The line: 
`winpty cmd.exe /C "create_build_files4.bat --wx-root=/mingw32/bin --force-wx-config --disable-mediactrl"`
does not execute. When following the instructions, I had to manually run `create_build_files4.bat --wx-root=/mingw32/bin --force-wx-config --disable-mediactrl"` from within the opened cmd.exe prompt.

FURTHERMORE:

Even after the compilation finishes, the compiled application DOESN'T RUN in windows, even after copying the required DLLs from mingw32's folders. 

0xc000007b error when starting the application.

Anyone want to tackle this one? I require an updated Windows binary. Building it myself seemed okay, until it wasn't. Haha. Any tips and tricks would be great.

**Comment by davidfraser** [comment]
I have the above problems too. Are you using 64-bit mingw toolchain or 32-bit?

**Comment by david-alleyn** [comment]
Tried it with both.

First with the 64-bit because I forgot that I was supposed to do it with 32-bit. Followed by a complete wipe and a re-attempt with 32bit. Both produce exactly the same results.

**Comment by jhasse** [comment]
Sorry that it didn't work, I'll try to reproduce your result.

>Even after the compilation finishes, the compiled application DOESN'T RUN in windows, even after copying the required DLLs from mingw32's folders.
>
>0xc000007b error when starting the application.
>
>Anyone want to tackle this one?

I guess that's because of missing / wrong DLLs. Try opening a cmd.exe and run:

```
set PATH=C:\msys64\mingw32\bin;%PATH%
wxformbuilder.exe
```

This should use the correct DLL files. I've got a script which copies them automatically and will upload that in the next days :)

**Comment by SpareSimian** [comment]
On a 64-bit system, so I'm using the 64 bit instructions from the current README.md, and the final make command tells me that g++ isn't found.

**Comment by SpareSimian** [comment]
Adding /mingw32/bin to the end of $PATH is allowing it to build. (/mingw64/bin is empty.)

**Comment by SpareSimian** [comment]
The make exits with this failure:
> md5.cc
> wxFormBuilder.rc
>   *** Error: Unrecognised option: '--rcflags'
> Use wx-config --help for information on command line options.
> Linking wxFormBuilder

**Comment by jhasse** [comment]
This error is currently "normal". Your resulting build should work fine though :)

**Comment by GeVanCo** [comment]
> This error is currently "normal". Your resulting build should work fine though :)

I want to pick up on this one again.  I too faced the same problem and yes, wxFormBuilder.exe is generated in the output directory.  But when I want to start the executable, I get the following error:

![wxformbuilder_error](https://user-images.githubusercontent.com/3616771/82721928-485f1200-9cc2-11ea-9b4b-77591179072b.png)

Any reason?  Compilation went fine (using mingw32.exe), including the "normal" error.  Here are the last steps of the building process:

`
xrcpreview.cpp
annoyingdialog.cpp
filetocarray.cpp
stringutils.cpp
typeconv.cpp
wxfbipc.cpp
md5.cc
wxFormBuilder.rc
  *** Error: Unrecognised option: '--rcflags'
Use wx-config --help for information on command line options.
Linking wxFormBuilder
`

What I would like to do by changing some code:

- Comply the generated Python code with the respective PEP's (e.g. no space after opening parenthesis and before closing parenthesis)

-  Get rid of the tabs that are used for indentation.  This isn't Python indentation style.  Tabs should be spaces instead.
