### ISSUE TITLE
Windows crash（wxFormBuilder v3.5 rc1）

### ISSUE THREAD

**Issue by hzm** [wxFormBuilder/wxFormBuilder#257]
When I type some Chinese characters, and then click another button, the program crashes. The error log is as follows:

11:00:54: 0x61602e51: ZNK16wxAppConsoleBase11HandleEventEP12wxEvtHandlerMS0_FvR7wxEventES3_ in D:\Program Files\wxFormBuilder\wxbase30u_gcc_cl.dll
11:00:54: 0x61603347: ZNK16wxAppConsoleBase16CallEventHandlerEP12wxEvtHandlerR14wxEventFunctorR7wxEvent in D:\Program Files\wxFormBuilder\wxbase30u_gcc_cl.dll
11:00:54: 0x61782178: ZN12wxEvtHandler23ProcessEventIfMatchesIdERK21wxEventTableEntryBasePS_R7wxEvent in D:\Program Files\wxFormBuilder\wxbase30u_gcc_cl.dll
11:00:54: 0x6178222a: ZN16wxEventHashTable11HandleEventER7wxEventP12wxEvtHandler in D:\Program Files\wxFormBuilder\wxbase30u_gcc_cl.dll
11:00:54: 0x617c3bdb: get_output_format in D:\Program Files\wxFormBuilder\wxbase30u_gcc_cl.dll
11:00:54: 0x6c9b8618: ZN8wxWindow16MSWHandleMessageEPljjl in D:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
11:00:54: 0x6c9aa43c: ZN8wxWindow13MSWWindowProcEjjl in D:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
11:00:54: 0x6c9af397: Z9wxWndProcP6HWND__jjl in D:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
11:00:54: 0x748c84f3: SetManipulationInputTarget in C:\WINDOWS\SYSTEM32\USER32.dll
11:00:54: 0x748a6c40: CallWindowProcW in C:\WINDOWS\SYSTEM32\USER32.dll
11:00:54: 0x748a6820: DispatchMessageW in C:\WINDOWS\SYSTEM32\USER32.dll
11:00:54: 0x748ae1a1: SystemParametersInfoW in C:\WINDOWS\SYSTEM32\USER32.dll
11:00:54: 0x6c9af397: Z9wxWndProcP6HWND__jjl in D:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
11:00:54: 0x748c84f3: SetManipulationInputTarget in C:\WINDOWS\SYSTEM32\USER32.dll
11:00:54: 0x748a6c40: CallWindowProcW in C:\WINDOWS\SYSTEM32\USER32.dll
11:00:54: 0x748a6541: DispatchMessageW in C:\WINDOWS\SYSTEM32\USER32.dll
11:00:54: 0x748b9bfb: IsDialogMessageW in C:\WINDOWS\SYSTEM32\USER32.dll
11:00:54: 0x6c9ae76c: ZN8wxWindow22MSWSafeIsDialogMessageEP6tagMSG in D:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
11:00:54: 0x6c9aeab3: ZN8wxWindow17MSWProcessMessageEP6tagMSG in D:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
11:00:54: 0x6c9f43ed: ZN14wxGUIEventLoop17PreProcessMessageEP6tagMSG in D:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
11:00:54: 0x6c9f4702: ZN14wxGUIEventLoop14ProcessMessageEP6tagMSG in D:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
11:00:54: 0x6c9f455b: ZN14wxGUIEventLoop8DispatchEv in D:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
11:00:54: 0x61637155: ZN17wxEventLoopManual5DoRunEv in D:\Program Files\wxFormBuilder\wxbase30u_gcc_cl.dll
11:00:54: 0x61603f77: ZN16wxAppConsoleBase8MainLoopEv in D:\Program Files\wxFormBuilder\wxbase30u_gcc_cl.dll
11:00:54: 0x61691966: Z11wxEntryRealRiPPw in D:\Program Files\wxFormBuilder\wxbase30u_gcc_cl.dll
11:00:54: 0x401557: WinMain@16 in D:\Program Files\wxFormBuilder\wxFormBuilder.exe
11:00:54: 0x4010fd: [unknown function] in D:\Program Files\wxFormBuilder\wxFormBuilder.exe
11:00:54: 0x77b65de3: RtlUnicodeStringToInteger in C:\WINDOWS\SYSTEM32\ntdll.dll
11:00:54: 0x77b65dae: RtlUnicodeStringToInteger in C:\WINDOWS\SYSTEM32\ntdll.dll
11:00:54: A Fatal Error Occurred. Click Details for a backtrace.

**Comment by hzm** [comment]
When I type some Chinese characters in label, and then click another button, the program crashes.

**Comment by jhasse** [comment]
Does this also happen with non-Chinese characters?
