### ISSUE TITLE
Python __init__ arguments

### ISSUE THREAD

**Issue by attoblarg** [wxFormBuilder/wxFormBuilder#261]
What starting a new form, the following code is generated for the constructor in Python:

```
class MyPanel1 ( wx.Panel ):
        def __init__( self, parent ):
                wx.Panel.__init__ ( self, parent, id = wx.ID_ANY, pos = wx.DefaultPosition, size = wx.Size( 500,300 ), style = wx.TAB_TRAVERSAL )
```

If I want to be able to set the size, style, or any other panel parameter (some of which can only be set in the constructor), then it would be much more helpful if this was the code generated instead:

```
class MyPanel1 ( wx.Panel ):
        def __init__( self, parent, id = wx.ID_ANY, pos = wx.DefaultPosition, size = wx.Size( 500,300 ), style = wx.TAB_TRAVERSAL, *args, **kwargs ):
                wx.Panel.__init__ ( self, parent, id = id, pos = pos, size = size, style = style, *args, **kwargs )
```

Any other parameter that is currently set by altering the superclass constructor, such as the window_name property, should also be moved to the subclass constructor, or moved to a class method call if available.

Please consider adding this change.

**Comment by acolomb** [comment]
I'd really like this enhancement, so that `wx.Panel`s defined within a wxFormBuilder project can be reused in other forms within the same project.  This is almost possible already by setting the `subclass` attribute for a panel where the generated class should be used.  It just fails because of this constructor argument incompatibility.

**Comment by attoblarg** [comment]
I'm not sure if this is helpful, but here is alternative way the output could be implemented, if it is easier (?).

In this version, all the manual assignments from the wxFormBuilder GUI are added to a kwargs dictionary, and all the `__init__` call signatures end up being the same (e.g. for `wx.Panel`, `__init__( self, parent, **kwargs )`).

```python
class MyPanel1 ( wx.Panel ):
    def __init__( self, parent, **kwargs ):
        
        # Settings from wxFormBuilder
        if 'id' not in kwargs:
            kwargs['id'] = wx.ID_ANY
        if 'pos' not in kwargs:
            kwargs['pos'] = wx.DefaultPosition
        if 'size' not in kwargs:
            kwargs['size'] = wx.Size( 500,300 )
        if 'style' not in kwargs:
            kwargs['style'] = wx.ID_ANY
        
        wx.Panel.__init__ ( self, parent, **kwargs )
        # etc.
```

**Comment by acolomb** [comment]
Isn't that what keyword arguments with default values are for?  Seems extra verbose compared to your first suggestion.

I've just tested something similar to your first solution by modifying `output/plugins/forms/xml/forms.pythoncode` and in my basic testing so far it works pretty well.
