### ISSUE TITLE
Create Windows installer using AppVeyor

### ISSUE THREAD

**Issue by jhasse** [wxFormBuilder/wxFormBuilder#262]
* [x] Run InnoSetup to create the installer
* [ ] Automatically include all the needed DLL files
* [ ] Upload the installer automatically to a GitHub release

**Comment by rugruth** [comment]
Simply Awesome. 

Keep up the good work :)

R.

**Comment by jhasse** [comment]
Okay AppVeyor now builds the installer. If someone wants to try it out: https://ci.appveyor.com/api/buildjobs/h066tldremgkpfed/artifacts/install%2Fwindows%2FwxFormBuilder_v3.6.0.exe

If just included all the DLLs like it was done in #263. The installer is only 11 MB, I think that's okay.

We'll have to upload it to a GitHub release manually for now, I couldn't find a way to do this without also creating the release via AppVeyor. Ideally I would want AppVeyor only to build the installer when I push a tag.

**Comment by TcT2k** [comment]
From what I understood from the AppVeyor documentation on [github releases](https://www.appveyor.com/docs/deployment/github/), you can limit the deployment to tag pushes only (see last line in the sample config).
