### ISSUE TITLE
Random Crashes in v3.5 RC1 on windows

### ISSUE THREAD

**Issue by S0C1esq** [wxFormBuilder/wxFormBuilder#269]
Random crashes after editing details in **Object Properties**

15:23:29: 0x61602e51: ZNK16wxAppConsoleBase11HandleEventEP12wxEvtHandlerMS0_FvR7wxEventES3_ in C:\Program Files\wxFormBuilder\wxbase30u_gcc_cl.dll
15:23:29: 0x61603347: ZNK16wxAppConsoleBase16CallEventHandlerEP12wxEvtHandlerR14wxEventFunctorR7wxEvent in C:\Program Files\wxFormBuilder\wxbase30u_gcc_cl.dll
15:23:29: 0x61782178: ZN12wxEvtHandler23ProcessEventIfMatchesIdERK21wxEventTableEntryBasePS_R7wxEvent in C:\Program Files\wxFormBuilder\wxbase30u_gcc_cl.dll
15:23:29: 0x6178222a: ZN16wxEventHashTable11HandleEventER7wxEventP12wxEvtHandler in C:\Program Files\wxFormBuilder\wxbase30u_gcc_cl.dll
15:23:29: 0x617c3bdb: get_output_format in C:\Program Files\wxFormBuilder\wxbase30u_gcc_cl.dll
15:23:29: 0x77525839: RtlSetLastWin32Error in C:\WINDOWS\SYSTEM32\ntdll.dll
15:23:29: 0x6c9b8618: ZN8wxWindow16MSWHandleMessageEPljjl in C:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
15:23:29: 0x6c9aa410: ZN8wxWindow13MSWWindowProcEjjl in C:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
15:23:29: 0x6ca3c154: ZN10wxTextCtrl13MSWWindowProcEjjl in C:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
15:23:29: 0x6c9af397: Z9wxWndProcP6HWND__jjl in C:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
15:23:29: 0x76e58233: RecordShutdownReason in C:\WINDOWS\System32\USER32.dll
15:23:29: 0x76e2e638: DispatchMessageW in C:\WINDOWS\System32\USER32.dll
15:23:29: 0x76e2e103: DispatchMessageW in C:\WINDOWS\System32\USER32.dll
15:23:29: 0x76e30ca9: IsDialogMessageW in C:\WINDOWS\System32\USER32.dll
15:23:29: 0x6c9ae76c: ZN8wxWindow22MSWSafeIsDialogMessageEP6tagMSG in C:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
15:23:29: 0x6c9aeab3: ZN8wxWindow17MSWProcessMessageEP6tagMSG in C:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
15:23:29: 0x6c9f43ed: ZN14wxGUIEventLoop17PreProcessMessageEP6tagMSG in C:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
15:23:29: 0x6c9f4702: ZN14wxGUIEventLoop14ProcessMessageEP6tagMSG in C:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
15:23:29: 0x6c9f455b: ZN14wxGUIEventLoop8DispatchEv in C:\Program Files\wxFormBuilder\wxmsw30u_core_gcc_cl.dll
15:23:29: 0x61637155: ZN17wxEventLoopManual5DoRunEv in C:\Program Files\wxFormBuilder\wxbase30u_gcc_cl.dll
15:23:29: 0x61603f77: ZN16wxAppConsoleBase8MainLoopEv in C:\Program Files\wxFormBuilder\wxbase30u_gcc_cl.dll
15:23:29: 0x61691966: Z11wxEntryRealRiPPw in C:\Program Files\wxFormBuilder\wxbase30u_gcc_cl.dll
15:23:29: 0x401557: WinMain@16 in C:\Program Files\wxFormBuilder\wxFormBuilder.exe
15:23:29: 0x4010fd: [unknown function] in C:\Program Files\wxFormBuilder\wxFormBuilder.exe
15:23:29: 0x77569bc3: RtlDestroyQueryDebugBuffer in C:\WINDOWS\SYSTEM32\ntdll.dll
15:23:29: 0x77569b92: RtlDestroyQueryDebugBuffer in C:\WINDOWS\SYSTEM32\ntdll.dll
15:23:29: A Fatal Error Occurred. Click Details for a backtrace.

**Comment by jhasse** [comment]
Can you try again with 3.6.0?

**Comment by jhasse** [comment]
Please reopen if it still happens with 3.6.0 or newer.
