### ISSUE TITLE
wxFormBuilder.org domain name

### ISSUE THREAD

**Issue by TcT2k** [wxFormBuilder/wxFormBuilder#270]
Does somebody of the developers still have access to the domain?

If yes it might make sense to directly send it to https://github.com/wxFormBuilder/wxFormBuilder instead of the sourceforge page in the future a github hosted static site might also make sense.

If no body has access it might make sense to replace the links inside the application.

**Comment by rjpcomputing** [comment]
@TcT2k 

I contacted the person that set that up. I will wait for their reply and let you know.

**Comment by rjpcomputing** [comment]
@TcT2k 

OK I got comfirmation that the URL is now pointing to https://github.com/wxFormBuilder/wxFormBuilder
