### ISSUE TITLE
Binary for macOS

### ISSUE THREAD

**Issue by eliclement** [wxFormBuilder/wxFormBuilder#271]
Is there a binary download of the latest 3.6.0 for macOS available? (the latest available for macOS was the 3.5.1 RC1 release at [sourceforge](https://sourceforge.net/projects/wxformbuilder/files/wxformbuilder-nightly/3.5.1-rc1/))

If not, what are the required building steps (easy explanation)?
Thanks!

**Comment by jhasse** [comment]
> Is there a binary download of the latest 3.6.0 for macOS available?

No, sorry.

**Comment by eliclement** [comment]
Can you point me in the right direction to build one myself?

**Comment by jhasse** [comment]
Have a look at #247.

**Comment by jhasse** [comment]
Could you get it to work?

**Comment by jhasse** [comment]
Let's continue this discussion in #247.
