### ISSUE TITLE
automatic arrays in generated code

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#28]
I would like wxFormbuilder to generate array variables when an array subscript is found in a variable name.  If the user creates 3 buttons with names m_button[0], m_button[1], m_button[2], the class definition will contain this: "wxButton* m_button[3];", rather than 3 separate variables.
Attached is a diff against version 3.1 that implements this for cpp

Reported by: crc1021

**Comment by sodevel** [comment]
Implemented in #431
