### ISSUE TITLE
make config=release dies trying to link with wx_gtk3u_media-3.1 library

### ISSUE THREAD

**Issue by crunch3** [wxFormBuilder/wxFormBuilder#288]
On Fedora 25, make config=release fails to link wxFormBuilder, apparently needing wx_gtk3u_media-3.1

Google doesn't have wx_gtk3u_media-3.1 indexed.  What's supposed to be there?

FYI, here's the output from make config=release...
------------------------------------------------------------
==== Building TiCPP (release) ====
==== Building plugin-interface (release) ====
==== Building additional-components-plugin (release) ====
==== Building common-components-plugin (release) ====
==== Building forms-components-plugin (release) ====
==== Building containers-components-plugin (release) ====
==== Building layout-components-plugin (release) ====
==== Building wxFormBuilder (release) ====
additional.cpp
Linking wxFormBuilder
/usr/bin/ld: cannot find -lwx_gtk3u_media-3.1
collect2: error: ld returned 1 exit status
wxFormBuilder.make:134: recipe for target '../../../output/bin/wxformbuilder' failed
make[1]: *** [../../../output/bin/wxformbuilder] Error 1
Makefile:44: recipe for target 'wxFormBuilder' failed
make: *** [wxFormBuilder] Error 2
make: *** Waiting for unfinished jobs....
In file included from ../../../sdk/plugin_interface/component.h:33:0,
                 from ../../../plugins/additional/additional.cpp:26:
../../../sdk/plugin_interface/fontcontainer.h: In member function ‘wxFont wxFontContainer::GetFont() const’:
../../../sdk/plugin_interface/fontcontainer.h:93:83: warning: ‘wxFont::wxFont(int, int, int, int, bool, const wxString&, wxFontEncoding)’ is deprecated: use wxFONT{FAMILY,STYLE,WEIGHT}_XXX constants [-Wdeprecated-declarations]
   return wxFont( pointSize, m_family, m_style, m_weight, m_underlined, m_faceName );
                                                                                   ^
In file included from /usr/local/include/wx-3.1/wx/font.h:524:0,
                 from /usr/local/include/wx-3.1/wx/window.h:23,
                 from /usr/local/include/wx-3.1/wx/wx.h:38,
                 from ../../../sdk/plugin_interface/component.h:30,
                 from ../../../plugins/additional/additional.cpp:26:
/usr/local/include/wx-3.1/wx/gtk/font.h:89:5: note: declared here
     wxFont(int size,
     ^~~~~~
../../../plugins/additional/additional.cpp: In member function ‘virtual wxObject* RichTextCtrlComponent::Create(IObject*, wxObject*)’:
../../../plugins/additional/additional.cpp:234:59: warning: ‘wxFont::wxFont(int, int, int, int, bool, const wxString&, wxFontEncoding)’ is deprecated: use wxFONT{FAMILY,STYLE,WEIGHT}_XXX constants [-Wdeprecated-declarations]
   wxFont textFont = wxFont(12, wxROMAN, wxNORMAL, wxNORMAL);
                                                           ^
In file included from /usr/local/include/wx-3.1/wx/font.h:524:0,
                 from /usr/local/include/wx-3.1/wx/window.h:23,
                 from /usr/local/include/wx-3.1/wx/wx.h:38,
                 from ../../../sdk/plugin_interface/component.h:30,
                 from ../../../plugins/additional/additional.cpp:26:
/usr/local/include/wx-3.1/wx/gtk/font.h:89:5: note: declared here
     wxFont(int size,
     ^~~~~~
../../../plugins/additional/additional.cpp:235:57: warning: ‘wxFont::wxFont(int, int, int, int, bool, const wxString&, wxFontEncoding)’ is deprecated: use wxFONT{FAMILY,STYLE,WEIGHT}_XXX constants [-Wdeprecated-declarations]
   wxFont boldFont = wxFont(12, wxROMAN, wxNORMAL, wxBOLD);
                                                         ^
In file included from /usr/local/include/wx-3.1/wx/font.h:524:0,
                 from /usr/local/include/wx-3.1/wx/window.h:23,
                 from /usr/local/include/wx-3.1/wx/wx.h:38,
                 from ../../../sdk/plugin_interface/component.h:30,
                 from ../../../plugins/additional/additional.cpp:26:
/usr/local/include/wx-3.1/wx/gtk/font.h:89:5: note: declared here
     wxFont(int size,
     ^~~~~~
../../../plugins/additional/additional.cpp:236:61: warning: ‘wxFont::wxFont(int, int, int, int, bool, const wxString&, wxFontEncoding)’ is deprecated: use wxFONT{FAMILY,STYLE,WEIGHT}_XXX constants [-Wdeprecated-declarations]
   wxFont italicFont = wxFont(12, wxROMAN, wxITALIC, wxNORMAL);
                                                             ^
In file included from /usr/local/include/wx-3.1/wx/font.h:524:0,
                 from /usr/local/include/wx-3.1/wx/window.h:23,
                 from /usr/local/include/wx-3.1/wx/wx.h:38,
                 from ../../../sdk/plugin_interface/component.h:30,
                 from ../../../plugins/additional/additional.cpp:26:
/usr/local/include/wx-3.1/wx/gtk/font.h:89:5: note: declared here
     wxFont(int size,
     ^~~~~~
../../../plugins/additional/additional.cpp:238:46: warning: ‘wxFont::wxFont(int, int, int, int, bool, const wxString&, wxFontEncoding)’ is deprecated: use wxFONT{FAMILY,STYLE,WEIGHT}_XXX constants [-Wdeprecated-declarations]
   wxFont font(12, wxROMAN, wxNORMAL, wxNORMAL);
                                              ^
In file included from /usr/local/include/wx-3.1/wx/font.h:524:0,
                 from /usr/local/include/wx-3.1/wx/window.h:23,
                 from /usr/local/include/wx-3.1/wx/wx.h:38,
                 from ../../../sdk/plugin_interface/component.h:30,
                 from ../../../plugins/additional/additional.cpp:26:
/usr/local/include/wx-3.1/wx/gtk/font.h:89:5: note: declared here
     wxFont(int size,
     ^~~~~~
../../../plugins/additional/additional.cpp: In member function ‘virtual wxObject* MediaCtrlComponent::Create(IObject*, wxObject*)’:
../../../plugins/additional/additional.cpp:1290:3: error: ‘wxMediaCtrl’ was not declared in this scope
   wxMediaCtrl* mc = new wxMediaCtrl((wxWindow *)parent, wxID_ANY, wxT(""),obj->GetPropertyAsPoint(_("pos")),
   ^~~~~~~~~~~
../../../plugins/additional/additional.cpp:1290:16: error: ‘mc’ was not declared in this scope
   wxMediaCtrl* mc = new wxMediaCtrl((wxWindow *)parent, wxID_ANY, wxT(""),obj->GetPropertyAsPoint(_("pos")),
                ^~
../../../plugins/additional/additional.cpp:1290:25: error: expected type-specifier before ‘wxMediaCtrl’
   wxMediaCtrl* mc = new wxMediaCtrl((wxWindow *)parent, wxID_ANY, wxT(""),obj->GetPropertyAsPoint(_("pos")),
                         ^~~~~~~~~~~
../../../plugins/additional/additional.cpp:1303:100: error: ‘wxMEDIACTRLPLAYERCONTROLS_STEP’ was not declared in this scope
 f(  obj->GetPropertyAsString( _("player_controls") ) == wxT("STEP") ) mc->ShowPlayerControls(wxMEDIACTRLPLAYERCONTROLS_STEP);
                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../plugins/additional/additional.cpp:1304:102: error: ‘wxMEDIACTRLPLAYERCONTROLS_VOLUME’ was not declared in this scope
   obj->GetPropertyAsString( _("player_controls") ) == wxT("VOLUME") ) mc->ShowPlayerControls(wxMEDIACTRLPLAYERCONTROLS_VOLUME);
                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../plugins/additional/additional.cpp:1305:103: error: ‘wxMEDIACTRLPLAYERCONTROLS_DEFAULT’ was not declared in this scope
  obj->GetPropertyAsString( _("player_controls") ) == wxT("DEFAULT") ) mc->ShowPlayerControls(wxMEDIACTRLPLAYERCONTROLS_DEFAULT);
                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../plugins/additional/additional.cpp:1306:100: error: ‘wxMEDIACTRLPLAYERCONTROLS_NONE’ was not declared in this scope
 f(  obj->GetPropertyAsString( _("player_controls") ) == wxT("NONE") ) mc->ShowPlayerControls(wxMEDIACTRLPLAYERCONTROLS_NONE);
                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../plugins/additional/additional.cpp:1318:55: error: ‘wxMEDIACTRLPLAYERCONTROLS_STEP’ was not declared in this scope
   if(!obj->IsNull(_("style"))) mc->ShowPlayerControls(wxMEDIACTRLPLAYERCONTROLS_STEP);
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../plugins/additional/additional.cpp: In member function ‘virtual wxObject* StyledTextComponent::Create(IObject*, wxObject*)’:
../../../plugins/additional/additional.cpp:1654:47: warning: ‘wxFont::wxFont(int, int, int, int, bool, const wxString&, wxFontEncoding)’ is deprecated: use wxFONT{FAMILY,STYLE,WEIGHT}_XXX constants [-Wdeprecated-declarations]
   wxFont font(10, wxMODERN, wxNORMAL, wxNORMAL);
                                               ^
In file included from /usr/local/include/wx-3.1/wx/font.h:524:0,
                 from /usr/local/include/wx-3.1/wx/window.h:23,
                 from /usr/local/include/wx-3.1/wx/wx.h:38,
                 from ../../../sdk/plugin_interface/component.h:30,
                 from ../../../plugins/additional/additional.cpp:26:
/usr/local/include/wx-3.1/wx/gtk/font.h:89:5: note: declared here
     wxFont(int size,
     ^~~~~~
additional-components-plugin.make:129: recipe for target 'obj/Release/additional-components-plugin/additional.o' failed
make[1]: *** [obj/Release/additional-components-plugin/additional.o] Error 1
Makefile:24: recipe for target 'additional-components-plugin' failed
make: *** [additional-components-plugin] Error 2

**Comment by jhasse** [comment]
It seems you have compiled wxWidgets yourself? You'll need to enable the multimedia component.

I would advice you to install wxWidgets from the repositories though. You'll need to install `wxGTK3-media`. You can search packages for files using:

```
dnf provides '*wx_gtk3u_media-3.1*'
```
