### ISSUE TITLE
Update the README's download link

### ISSUE THREAD

**Issue by jondo** [wxFormBuilder/wxFormBuilder#293]
The [current README](https://github.com/wxFormBuilder/wxFormBuilder/blob/749c5ebf2b7933f26f8b6d29f457dd0e8428474d/README.md) links to a download marked as "(last successful build)". Which version is offered there? How is this related to the [3.6.0 release](https://github.com/wxFormBuilder/wxFormBuilder/releases/tag/v3.6.0)?

**Comment by jhasse** [comment]
This links to a build of the latest commit in the master branch.
