### ISSUE TITLE
Windows installation error (installing from source)

### ISSUE THREAD

**Issue by Conkey100** [wxFormBuilder/wxFormBuilder#296]
I followed the "Install From Source" instructions in the readme file, 64bit windows 10. The build step failed with the error: "*** Error: Unrecognised option: '--rcflags'"

wxFormbuilder.exe was created, but if I try to run it I get the following 4 system errors:

"The code execution cannot proceed because libintl-8.dll was not found. Reinstalling the program may fix this problem." 

"The code execution cannot proceed because wxbase30u_gcc_custom.dll was not found. Reinstalling the program may fix this problem."

"The code execution cannot proceed because wxmsw30u_adv_gcc_cutom.dll was not found. Reinstalling the program may fix this problem."

"The code execution cannot proceed because wxmsw30u_aui_gcc_cutom.dll was not found. Reinstalling the program may fix this problem."

The complete output from make:
$ make config=release
==== Building TiCPP (release) ====
Creating ../../../sdk/lib
Creating obj/Release/TiCPP
ticpp.cpp
tinystr.cpp
tinyxml.cpp
tinyxmlerror.cpp
tinyxmlparser.cpp
Linking TiCPP
==== Building plugin-interface (release) ====
Creating obj/Release/plugin-interface
xrcconv.cpp
wizard.cpp
Linking plugin-interface
==== Building additional-components-plugin (release) ====
Creating obj/Release/additional-components-plugin
additional.cpp
Linking additional-components-plugin
==== Building common-components-plugin (release) ====
Creating obj/Release/common-components-plugin
common.cpp
Linking common-components-plugin
==== Building containers-components-plugin (release) ====
Creating obj/Release/containers-components-plugin
containers.cpp
Linking containers-components-plugin
==== Building forms-components-plugin (release) ====
Creating obj/Release/forms-components-plugin
forms.cpp
Linking forms-components-plugin
==== Building layout-components-plugin (release) ====
Creating obj/Release/layout-components-plugin
layout.cpp
Linking layout-components-plugin
==== Building wxFormBuilder (release) ====
Creating obj/Release/wxFormBuilder
maingui.cpp
codegen.cpp
codeparser.cpp
codewriter.cpp
cppcg.cpp
luacg.cpp
phpcg.cpp
pythoncg.cpp
xrccg.cpp
stack.cpp
database.cpp
objectbase.cpp
types.cpp
xrcfilter.cpp
about.cpp
appdata.cpp
bitmaps.cpp
cmdproc.cpp
customkeys.cpp
genericpanel.cpp
mainframe.cpp
menueditor.cpp
palette.cpp
title.cpp
wxfbevent.cpp
wxfbmanager.cpp
codeeditor.cpp
cpppanel.cpp
dataobject.cpp
innerframe.cpp
menubar.cpp
visualeditor.cpp
visualobj.cpp
geninhertclass.cpp
geninhertclass_gui.cpp
objinspect.cpp
wxfbadvprops.cpp
luapanel.cpp
objecttree.cpp
phppanel.cpp
pythonpanel.cpp
xrcpanel.cpp
xrcpreview.cpp
annoyingdialog.cpp
encodingutils.cpp
filetocarray.cpp
stringutils.cpp
typeconv.cpp
wxfbipc.cpp
md5.cc
wxFormBuilder.rc
  *** Error: Unrecognised option: '--rcflags'
Use wx-config --help for information on command line options.
Linking wxFormBuilder

**Comment by jhasse** [comment]
The DLL files are located inside `C:\msys64\mingw32\bin`. So in order to run the exe file you'll need to add that directory to your `PATH` or copy the DLLs next to the exe or run it from the Mingw32 shell using `./wxFormBuilder.exe`.
