### ISSUE TITLE
Can't build on debian stretch

### ISSUE THREAD

**Issue by JiffB** [wxFormBuilder/wxFormBuilder#297]
Hi,

I installed necessary libs (+ freebsd-glue & freebsd-buildutils, just in case), but I'm stuck at the initialization by something I don't know how to fix; here's the log:

remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
From https://github.com/wxFormBuilder/wxFormBuilder
 * branch            HEAD       -> FETCH_HEAD
Already up-to-date.
make: Entering directory '/usr/local/src/WXFORMBUILDER/wxFormBuilder/build/premake/linux'
==== Building Premake4 ====
Linking Premake4
/usr/bin/ld: obj/Release/os_match.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/os_uuid.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/os_chdir.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/os_pathsearch.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/os_rmdir.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/os_copyfile.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/os_mkdir.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/premake.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/lauxlib.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/lobject.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/lcode.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/ltm.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/loadlib.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/lgc.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/llex.o: relocation R_X86_64_32S against hidden symbol `luaX_tokens' can not be used when making a shared object
/usr/bin/ld: obj/Release/ldebug.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/lstrlib.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/lparser.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/lstate.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/lmem.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/lmathlib.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/ltable.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/linit.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/lundump.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/lvm.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/lbaselib.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/ltablib.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/ldo.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/lapi.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/loslib.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/liolib.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: obj/Release/ldblib.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Premake4.make:126: recipe for target 'bin/release/premake4' failed
make[1]: *** [bin/release/premake4] Error 1
Makefile:16: recipe for target 'Premake4' failed
make: *** [Premake4] Error 2
make: Leaving directory '/usr/local/src/WXFORMBUILDER/wxFormBuilder/build/premake/linux'
./create_build_files4.sh: 91: ./create_build_files4.sh: ./premake/linux/bin/release/premake4: not found
./create_build_files4.sh: 92: ./create_build_files4.sh: ./premake/linux/bin/release/premake4: not found
./create_build_files4.sh: 93: ./create_build_files4.sh: ./premake/linux/bin/release/premake4: not found
./GET_WXFOMRBUILDER_SRC.sh: 9: cd: can't cd to build/3.0/gmake
make: *** No targets specified and no makefile found.  Stop.

Can you explain me where it comes from and how to fix that, please ?

**Comment by jhasse** [comment]
No idea. Can you see if there's a Debian package for premake? You should be able to use that instead of compiling premake yourself (this is what `create_build_files4.sh` tries to do).

**Comment by JiffB** [comment]
O_o, my bad, I just thought premake was a local arousing the monster before feeding.
There is indeed a debian stretch (stable) package named "premake4" that I installed after reading you; then I fixed the script by commenting/modifying 4 lines:

###make CONFIG=Release -C./premake/$platform

###./premake/$platform/bin/release/premake4 --file=./premake/solution.lua $wxunicode $wxroot $wxversion $mediactrl $shared $arch codeblocks
premake4 --file=./premake/solution.lua $wxunicode $wxroot $wxversion $mediactrl $shared $arch codeblocks
###./premake/$platform/bin/release/premake4 --file=./premake/solution.lua $wxunicode $wxroot $wxversion $mediactrl $shared $arch $rpath codelite
premake4 --file=./premake/solution.lua $wxunicode $wxroot $wxversion $mediactrl $shared $arch $rpath codelite
###./premake/$platform/bin/release/premake4 --file=./premake/solution.lua $wxunicode $wxroot $wxversion $mediactrl $shared $arch $rpath gmake
premake4 --file=./premake/solution.lua $wxunicode $wxroot $wxversion $mediactrl $shared $arch $rpath gmake

and this time, it compiled like a charm;)
So, thanks for help & regards.
Jiff
