### ISSUE TITLE
bitmap button with text

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#30]
Add the possibility to use bitmap button with text (wx.lib.buttons)

Reported by: *anonymous

**Comment by specing** [comment]
Speaking of wxBitmapButton, how does one see its label inside the wxFormBuilder Editor window? I also set its bitmap source to "Load from Art Provider" and selected a random one (wxART_FLOPPY) from the drop-down, but all that is shown in the Editor preview is a square button with just a red '?' image and no label next to it.

**Comment by jhasse** [comment]
@specing Yeah the preview is kind of broken :( But it should work in the final window.

Regarding a bitmap button with text: This is now possible with wxButton in 3.8.0, so I'm closing this.
