### ISSUE TITLE
Wiki is missing. Command line arguments documentation is missing

### ISSUE THREAD

**Issue by siryoav** [wxFormBuilder/wxFormBuilder#300]
Found this:
http://www.huge-man-linux.net/man1/wxformbuilder.html

It documents command line arguments for the wxformbuilder.exe 

I wanted to generate target code with command line build tool, so I could save in my source control only the  .fbp file
To sum it up - 
wxformbuilder -g <Path to .fbp>
output is written to the same folder your .fbp is in

**Comment by jhasse** [comment]
I've created a simple Wiki page with the command line arguments: https://github.com/wxFormBuilder/wxFormBuilder/wiki

Feel free to expand it :)
