### ISSUE TITLE
Why is there no ticpp.h found?

### ISSUE THREAD

**Issue by richierh** [wxFormBuilder/wxFormBuilder#301]
Hi, I am trying to install wxformbuilder from source, I got this following error while using make config==release

sudo make config=release==== Building TiCPP (release) ====
==== Building plugin-interface (release) ====
xrcconv.cpp
../../../sdk/plugin_interface/xrcconv.cpp:33:19: fatal error: ticpp.h: No such file or directory
compilation terminated.
plugin-interface.make:130: recipe for target 'obj/Release/plugin-interface/xrcconv.o' failed
make[1]: *** [obj/Release/plugin-interface/xrcconv.o] Error 1
Makefile:20: recipe for target 'plugin-interface' failed
make: *** [plugin-interface] Error 2

**Comment by jhasse** [comment]
Run:

```
git submodule update --init
```

**Comment by richierh** [comment]
Okay..now it's working..thanks
