### ISSUE TITLE
[Solved] Dynamic window size

### ISSUE THREAD

**Issue by TheDogeOfTheInternet** [wxFormBuilder/wxFormBuilder#302]
It would be much appreciated if you could add a way of determining the window size based on the screen size of the computer running the program. 

The simplest way (in my opinion) is to add 'size' as a parameter in the '__init__' function, so that the class that calls the frame can determine the size.

If there is already a way to do this, please inform me.

**Comment by jhasse** [comment]
The constructor of generated classes should have a `wxSize` parameter (set the size to -1,-1 in wxFormBuilder). Does that work for you?

**Comment by TheDogeOfTheInternet** [comment]
Do you mean that I should edit the generated file and change the 'wx.Frame' constructor? Because the generated file's constructor doesn't have size as a parameter.

**Comment by jhasse** [comment]
You're using Python? I was talking about C++.

You can use `SetSize` to change the window size after the initialization.

**Comment by TheDogeOfTheInternet** [comment]
Worked perfectly. Thanks.
