### ISSUE TITLE
Can not install on Github desktop, Windows10, Errors included 

### ISSUE THREAD

**Issue by sprinteroz** [wxFormBuilder/wxFormBuilder#305]
Hi I just tried to install this using windows 10 64bit github desktop version, but get the install errors below.

Cloning into 'C:\Users\XXX\Documents\GitHub\wxFormBuilder'...
remote: Counting objects: 11970, done.        
Receiving objects:   0% (1/11970)   
Receiving objects:   1% (120/11970)   
Receiving objects:   2% (240/11970)   
Receiving objects:   3% (360/11970)   
Receiving objects:   4% (479/11970)   
Receiving objects:   5% (599/11970)   
Receiving objects:   6% (719/11970)   
Receiving objects:   7% (838/11970)   
Receiving objects:   8% (958/11970)   
Receiving objects:   9% (1078/11970)   
Receiving objects:  10% (1197/11970)   
Receiving objects:  11% (1317/11970)   
Receiving objects:  12% (1437/11970)   
Receiving objects:  13% (1557/11970), 276.01 KiB | 539.00 KiB/s   
Receiving objects:  14% (1676/11970), 276.01 KiB | 539.00 KiB/s   
Receiving objects:  15% (1796/11970), 276.01 KiB | 539.00 KiB/s   
Receiving objects:  16% (1916/11970), 276.01 KiB | 539.00 KiB/s   
Receiving objects:  17% (2035/11970), 276.01 KiB | 539.00 KiB/s   
Receiving objects:  18% (2155/11970), 788.01 KiB | 774.00 KiB/s   
Receiving objects:  19% (2275/11970), 788.01 KiB | 774.00 KiB/s   
Receiving objects:  20% (2394/11970), 788.01 KiB | 774.00 KiB/s   
Receiving objects:  21% (2514/11970), 788.01 KiB | 774.00 KiB/s   
Receiving objects:  22% (2634/11970), 788.01 KiB | 774.00 KiB/s   
Receiving objects:  22% (2715/11970), 788.01 KiB | 774.00 KiB/s   
Receiving objects:  23% (2754/11970), 788.01 KiB | 774.00 KiB/s   
Receiving objects:  24% (2873/11970), 788.01 KiB | 774.00 KiB/s   
Receiving objects:  25% (2993/11970), 2.36 MiB | 1.55 MiB/s   
Receiving objects:  26% (3113/11970), 2.36 MiB | 1.55 MiB/s   
Receiving objects:  27% (3232/11970), 2.36 MiB | 1.55 MiB/s   
Receiving objects:  28% (3352/11970), 2.36 MiB | 1.55 MiB/s   
Receiving objects:  29% (3472/11970), 2.36 MiB | 1.55 MiB/s   
Receiving objects:  30% (3591/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  31% (3711/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  32% (3831/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  33% (3951/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  34% (4070/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  35% (4190/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  36% (4310/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  37% (4429/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  38% (4549/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  39% (4669/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  40% (4788/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  41% (4908/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  42% (5028/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  43% (5148/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  44% (5267/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  45% (5387/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  46% (5507/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  47% (5626/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  48% (5746/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  49% (5866/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  50% (5985/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  51% (6105/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  51% (6141/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  52% (6225/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  53% (6345/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  54% (6464/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  55% (6584/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  56% (6704/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  57% (6823/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  58% (6943/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  59% (7063/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  60% (7182/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  61% (7302/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  62% (7422/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  63% (7542/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  64% (7661/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  65% (7781/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  66% (7901/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  67% (8020/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  68% (8140/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  69% (8260/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  70% (8379/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  71% (8499/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  72% (8619/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  73% (8739/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  74% (8858/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  75% (8978/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  76% (9098/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  77% (9217/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  78% (9337/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  79% (9457/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  80% (9576/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  81% (9696/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  82% (9816/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  83% (9936/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  84% (10055/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  85% (10175/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  86% (10295/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  87% (10414/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  88% (10534/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  89% (10654/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  90% (10773/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  91% (10893/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  92% (11013/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  93% (11133/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  94% (11252/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  95% (11372/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  96% (11492/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  97% (11611/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  98% (11731/11970), 2.61 MiB | 1.13 MiB/s   
Receiving objects:  99% (11851/11970), 2.61 MiB | 1.13 MiB/s   
remote: Total 11970 (delta 0), reused 0 (delta 0), pack-reused 11970        
Receiving objects: 100% (11970/11970), 6.87 MiB | 2.27 MiB/s   
Receiving objects: 100% (11970/11970), 6.89 MiB | 2.27 MiB/s, done.
Resolving deltas:   0% (0/7760)   
Resolving deltas:   1% (82/7760)   
Resolving deltas:   2% (156/7760)   
Resolving deltas:   3% (233/7760)   
Resolving deltas:   4% (311/7760)   
Resolving deltas:   5% (406/7760)   
Resolving deltas:   6% (481/7760)   
Resolving deltas:   7% (548/7760)   
Resolving deltas:   8% (631/7760)   
Resolving deltas:  10% (806/7760)   
Resolving deltas:  12% (955/7760)   
Resolving deltas:  13% (1056/7760)   
Resolving deltas:  15% (1198/7760)   
Resolving deltas:  16% (1275/7760)   
Resolving deltas:  17% (1320/7760)   
Resolving deltas:  18% (1399/7760)   
Resolving deltas:  19% (1493/7760)   
Resolving deltas:  21% (1670/7760)   
Resolving deltas:  22% (1710/7760)   
Resolving deltas:  23% (1833/7760)   
Resolving deltas:  24% (1911/7760)   
Resolving deltas:  25% (1971/7760)   
Resolving deltas:  26% (2035/7760)   
Resolving deltas:  27% (2102/7760)   
Resolving deltas:  28% (2177/7760)   
Resolving deltas:  29% (2283/7760)   
Resolving deltas:  31% (2425/7760)   
Resolving deltas:  32% (2487/7760)   
Resolving deltas:  33% (2625/7760)   
Resolving deltas:  34% (2658/7760)   
Resolving deltas:  35% (2755/7760)   
Resolving deltas:  36% (2822/7760)   
Resolving deltas:  37% (2874/7760)   
Resolving deltas:  38% (2957/7760)   
Resolving deltas:  39% (3075/7760)   
Resolving deltas:  40% (3121/7760)   
Resolving deltas:  41% (3182/7760)   
Resolving deltas:  42% (3264/7760)   
Resolving deltas:  43% (3340/7760)   
Resolving deltas:  44% (3417/7760)   
Resolving deltas:  45% (3496/7760)   
Resolving deltas:  46% (3575/7760)   
Resolving deltas:  47% (3651/7760)   
Resolving deltas:  48% (3736/7760)   
Resolving deltas:  49% (3807/7760)   
Resolving deltas:  50% (3899/7760)   
Resolving deltas:  51% (3976/7760)   
Resolving deltas:  52% (4043/7760)   
Resolving deltas:  53% (4167/7760)   
Resolving deltas:  54% (4227/7760)   
Resolving deltas:  55% (4286/7760)   
Resolving deltas:  56% (4347/7760)   
Resolving deltas:  57% (4431/7760)   
Resolving deltas:  58% (4506/7760)   
Resolving deltas:  59% (4579/7760)   
Resolving deltas:  60% (4660/7760)   
Resolving deltas:  61% (4768/7760)   
Resolving deltas:  62% (4814/7760)   
Resolving deltas:  63% (4889/7760)   
Resolving deltas:  64% (4969/7760)   
Resolving deltas:  65% (5052/7760)   
Resolving deltas:  66% (5124/7760)   
Resolving deltas:  67% (5202/7760)   
Resolving deltas:  68% (5292/7760)   
Resolving deltas:  69% (5367/7760)   
Resolving deltas:  70% (5435/7760)   
Resolving deltas:  71% (5511/7760)   
Resolving deltas:  72% (5590/7760)   
Resolving deltas:  73% (5668/7760)   
Resolving deltas:  74% (5751/7760)   
Resolving deltas:  75% (5832/7760)   
Resolving deltas:  76% (5908/7760)   
Resolving deltas:  77% (5990/7760)   
Resolving deltas:  78% (6056/7760)   
Resolving deltas:  80% (6215/7760)   
Resolving deltas:  81% (6299/7760)   
Resolving deltas:  82% (6373/7760)   
Resolving deltas:  83% (6463/7760)   
Resolving deltas:  84% (6519/7760)   
Resolving deltas:  85% (6608/7760)   
Resolving deltas:  86% (6674/7760)   
Resolving deltas:  87% (6764/7760)   
Resolving deltas:  88% (6831/7760)   
Resolving deltas:  89% (6919/7760)   
Resolving deltas:  90% (6988/7760)   
Resolving deltas:  91% (7067/7760)   
Resolving deltas:  92% (7140/7760)   
Resolving deltas:  93% (7227/7760)   
Resolving deltas:  94% (7341/7760)   
Resolving deltas:  95% (7373/7760)   
Resolving deltas:  96% (7451/7760)   
Resolving deltas:  98% (7640/7760)   
Resolving deltas:  99% (7685/7760)   
Resolving deltas:  99% (7734/7760)   
Resolving deltas: 100% (7760/7760)   
Resolving deltas: 100% (7760/7760), done.
Checking out files:   2% (19/863)   
Checking out files:   3% (26/863)   
Checking out files:   4% (35/863)   
Checking out files:   4% (40/863)   
Checking out files:   5% (44/863)   
Checking out files:   6% (52/863)   
Checking out files:   6% (60/863)   
Checking out files:   7% (61/863)   
Checking out files:   8% (70/863)   
Checking out files:   9% (78/863)   
Checking out files:   9% (81/863)   
Checking out files:  10% (87/863)   
Checking out files:  11% (95/863)   
Checking out files:  12% (104/863)   
Checking out files:  12% (108/863)   
Checking out files:  13% (113/863)   
Checking out files:  14% (121/863)   
Checking out files:  15% (130/863)   
Checking out files:  15% (133/863)   
Checking out files:  16% (139/863)   
Checking out files:  17% (147/863)   
Checking out files:  17% (155/863)   
Checking out files:  18% (156/863)   
Checking out files:  19% (164/863)   
Checking out files:  20% (173/863)   
Checking out files:  20% (181/863)   
Checking out files:  21% (182/863)   
Checking out files:  22% (190/863)   
Checking out files:  23% (199/863)   
Checking out files:  24% (208/863)   
Checking out files:  25% (216/863)   
Checking out files:  26% (225/863)   
Checking out files:  26% (233/863)   
Checking out files:  27% (234/863)   
Checking out files:  28% (242/863)   
Checking out files:  29% (251/863)   
Checking out files:  29% (256/863)   
Checking out files:  30% (259/863)   
Checking out files:  31% (268/863)   
Checking out files:  31% (270/863)   
Checking out files:  32% (277/863)   
Checking out files:  33% (285/863)   
Checking out files:  34% (294/863)   
Checking out files:  35% (303/863)   
Checking out files:  36% (311/863)   
Checking out files:  36% (318/863)   
Checking out files:  37% (320/863)   
Checking out files:  38% (328/863)   
Checking out files:  39% (337/863)   
Checking out files:  40% (346/863)   
Checking out files:  41% (354/863)   
Checking out files:  42% (363/863)   
Checking out files:  42% (366/863)   
Checking out files:  43% (372/863)   
Checking out files:  44% (380/863)   
Checking out files:  44% (387/863)   
Checking out files:  45% (389/863)   
Checking out files:  46% (397/863)   
Checking out files:  46% (405/863)   
Checking out files:  47% (406/863)   
Checking out files:  48% (415/863)   
Checking out files:  49% (423/863)   
Checking out files:  50% (432/863)   
Checking out files:  50% (433/863)   
Checking out files:  51% (441/863)   
Checking out files:  52% (449/863)   
Checking out files:  53% (458/863)   
Checking out files:  54% (467/863)   
Checking out files:  55% (475/863)   
Checking out files:  56% (484/863)   
Checking out files:  56% (488/863)   
Checking out files:  57% (492/863)   
Checking out files:  58% (501/863)   
Checking out files:  59% (510/863)   
Checking out files:  59% (511/863)   
Checking out files:  60% (518/863)   
Checking out files:  61% (527/863)   
Checking out files:  62% (536/863)   
Checking out files:  62% (537/863)   
Checking out files:  63% (544/863)   
Checking out files:  64% (553/863)   
Checking out files:  65% (561/863)   
Checking out files:  65% (565/863)   
Checking out files:  66% (570/863)   
Checking out files:  67% (579/863)   
Checking out files:  68% (587/863)   
Checking out files:  69% (596/863)   
Checking out files:  70% (605/863)   
Checking out files:  70% (609/863)   
Checking out files:  71% (613/863)   
Checking out files:  72% (622/863)   
Checking out files:  72% (628/863)   
Checking out files:  73% (630/863)   
Checking out files:  74% (639/863)   
Checking out files:  75% (648/863)   
Checking out files:  75% (655/863)   
Checking out files:  76% (656/863)   
Checking out files:  77% (665/863)   
Checking out files:  78% (674/863)   
Checking out files:  78% (680/863)   
Checking out files:  79% (682/863)   
Checking out files:  80% (691/863)   
Checking out files:  81% (700/863)   
Checking out files:  81% (704/863)   
Checking out files:  82% (708/863)   
Checking out files:  83% (717/863)   
Checking out files:  84% (725/863)   
Checking out files:  84% (729/863)   
Checking out files:  85% (734/863)   
Checking out files:  86% (743/863)   
Checking out files:  86% (749/863)   
Checking out files:  87% (751/863)   
Checking out files:  88% (760/863)   
Checking out files:  89% (769/863)   
Checking out files:  89% (770/863)   
Checking out files:  90% (777/863)   
Checking out files:  91% (786/863)   
Checking out files:  92% (794/863)   
Checking out files:  93% (803/863)   
Checking out files:  94% (812/863)   
Checking out files:  94% (813/863)   
Checking out files:  95% (820/863)   
Checking out files:  96% (829/863)   
Checking out files:  97% (838/863)   
Checking out files:  98% (846/863)   
Checking out files:  99% (855/863)   
Checking out files:  99% (861/863)   
Checking out files: 100% (863/863)   
Checking out files: 100% (863/863), done.
Submodule 'sdk/tinyxml' (https://github.com/rjpcomputing/ticpp.git) registered for path 'sdk/tinyxml'
Cloning into 'C:/Users/XXX/Documents/GitHub/wxFormBuilder/sdk/tinyxml'...
remote: Counting objects: 700, done.        
Receiving objects:   0% (1/700)   
Receiving objects:   1% (7/700)   
Receiving objects:   2% (14/700)   
Receiving objects:   3% (21/700)   
Receiving objects:   4% (28/700)   
Receiving objects:   5% (35/700)   
Receiving objects:   6% (42/700)   
Receiving objects:   7% (49/700)   
Receiving objects:   8% (56/700)   
Receiving objects:   9% (63/700)   
Receiving objects:  10% (70/700)   
Receiving objects:  11% (77/700)   
Receiving objects:  12% (84/700)   
Receiving objects:  13% (91/700)   
Receiving objects:  14% (98/700)   
Receiving objects:  15% (105/700)   
Receiving objects:  16% (112/700)   
Receiving objects:  17% (119/700)   
Receiving objects:  18% (126/700)   
Receiving objects:  19% (133/700)   
Receiving objects:  20% (140/700)   
Receiving objects:  21% (147/700)   
Receiving objects:  22% (154/700)   
Receiving objects:  23% (161/700)   
Receiving objects:  24% (168/700)   
Receiving objects:  25% (175/700)   
Receiving objects:  26% (182/700)   
Receiving objects:  27% (189/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  28% (196/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  29% (203/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  30% (210/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  31% (217/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  32% (224/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  33% (231/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  34% (238/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  35% (245/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  36% (252/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  37% (259/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  38% (266/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  39% (273/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  40% (280/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  41% (287/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  42% (294/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  43% (301/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  44% (308/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  45% (315/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  46% (322/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  47% (329/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  48% (336/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  49% (343/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  50% (350/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  51% (357/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  52% (364/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  53% (371/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  53% (375/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  54% (378/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  55% (385/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  56% (392/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  57% (399/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  58% (406/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  59% (413/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  60% (420/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  61% (427/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  62% (434/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  63% (441/700), 340.01 KiB | 316.00 KiB/s   
Receiving objects:  64% (448/700), 800.01 KiB | 509.00 KiB/s   
Receiving objects:  65% (455/700), 800.01 KiB | 509.00 KiB/s   
Receiving objects:  66% (462/700), 800.01 KiB | 509.00 KiB/s   
Receiving objects:  67% (469/700), 800.01 KiB | 509.00 KiB/s   
Receiving objects:  68% (476/700), 800.01 KiB | 509.00 KiB/s   
Receiving objects:  69% (483/700), 800.01 KiB | 509.00 KiB/s   
Receiving objects:  70% (490/700), 800.01 KiB | 509.00 KiB/s   
Receiving objects:  71% (497/700), 800.01 KiB | 509.00 KiB/s   
Receiving objects:  72% (504/700), 800.01 KiB | 509.00 KiB/s   
Receiving objects:  73% (511/700), 800.01 KiB | 509.00 KiB/s   
Receiving objects:  74% (518/700), 800.01 KiB | 509.00 KiB/s   
Receiving objects:  75% (525/700), 800.01 KiB | 509.00 KiB/s   
Receiving objects:  76% (532/700), 800.01 KiB | 509.00 KiB/s   
Receiving objects:  77% (539/700), 800.01 KiB | 509.00 KiB/s   
Receiving objects:  78% (546/700), 800.01 KiB | 509.00 KiB/s   
Receiving objects:  79% (553/700), 800.01 KiB | 509.00 KiB/s   
Receiving objects:  80% (560/700), 800.01 KiB | 509.00 KiB/s   
Receiving objects:  81% (567/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects:  82% (574/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects:  83% (581/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects:  84% (588/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects:  85% (595/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects:  86% (602/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects:  87% (609/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects:  88% (616/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects:  89% (623/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects:  90% (630/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects:  91% (637/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects:  92% (644/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects:  93% (651/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects:  94% (658/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects:  95% (665/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects:  96% (672/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects:  97% (679/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects:  98% (686/700), 1.39 MiB | 688.00 KiB/s   
remote: Total 700 (delta 0), reused 0 (delta 0), pack-reused 700        
Receiving objects:  99% (693/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects: 100% (700/700), 1.39 MiB | 688.00 KiB/s   
Receiving objects: 100% (700/700), 1.51 MiB | 730.00 KiB/s, done.
Resolving deltas:   0% (0/464)   
Resolving deltas:   1% (6/464)   
Resolving deltas:   2% (12/464)   
Resolving deltas:   3% (14/464)   
Resolving deltas:   5% (24/464)   
Resolving deltas:   9% (42/464)   
Resolving deltas:  14% (65/464)   
Resolving deltas:  16% (78/464)   
Resolving deltas:  19% (91/464)   
Resolving deltas:  20% (94/464)   
Resolving deltas:  21% (99/464)   
Resolving deltas:  22% (104/464)   
Resolving deltas:  23% (107/464)   
Resolving deltas:  26% (121/464)   
Resolving deltas:  27% (126/464)   
Resolving deltas:  28% (130/464)   
Resolving deltas:  43% (200/464)   
Resolving deltas:  44% (207/464)   
Resolving deltas:  47% (222/464)   
Resolving deltas:  48% (227/464)   
Resolving deltas:  49% (229/464)   
Resolving deltas:  50% (232/464)   
Resolving deltas:  52% (242/464)   
Resolving deltas:  56% (260/464)   
Resolving deltas:  58% (270/464)   
Resolving deltas:  59% (275/464)   
Resolving deltas:  63% (295/464)   
Resolving deltas:  64% (299/464)   
Resolving deltas:  68% (320/464)   
Resolving deltas:  69% (323/464)   
Resolving deltas:  71% (330/464)   
Resolving deltas:  73% (339/464)   
Resolving deltas:  75% (349/464)   
Resolving deltas:  76% (354/464)   
Resolving deltas:  78% (362/464)   
Resolving deltas:  79% (370/464)   
Resolving deltas:  82% (381/464)   
Resolving deltas:  85% (399/464)   
Resolving deltas:  88% (412/464)   
Resolving deltas:  89% (417/464)   
Resolving deltas:  90% (422/464)   
Resolving deltas:  94% (438/464)   
Resolving deltas:  95% (442/464)   
Resolving deltas:  96% (448/464)   
Resolving deltas:  98% (456/464)   
Resolving deltas: 100% (464/464)   
Resolving deltas: 100% (464/464), done.
fatal: reference is not a tree: 01fc2f8cddd305b1c92fcced9c7346f0349d755a
Unable to checkout '01fc2f8cddd305b1c92fcced9c7346f0349d755a' in submodule path 'sdk/tinyxml'

**Comment by jhasse** [comment]
Please try again and reopen if this is still happening.
