### ISSUE TITLE
mismatch between program and library build versions detected

### ISSUE THREAD

**Issue by mrunmayi29** [wxFormBuilder/wxFormBuilder#306]
I am getting this error while executing ./wxformBuilder.exe
The library used 3.0(wchar_t, compiler with c++ ABI 1010, wx containers compatible with 2.8)
and your program used 3.0(wchar_t, compiler with c++ ABI 1011, wx containers compatible with 2.8)

**Comment by jhasse** [comment]
This is a MSYS2 bug :(   https://github.com/Alexpux/MINGW-packages/issues/1578

Not much we can do about it atm. I want to explore building wxFormBuilder with the Windows Subsystem for Linux, but I'm currently waiting for Fedora to arrive at the Store.

**Comment by mrunmayi29** [comment]
okay, I need to install and use  wxFormBuilder in windows. Is there any alternative way other than MSYS2.

**Comment by mrunmayi29** [comment]
okay :)
