### ISSUE TITLE
checkboxes for wxtreectrl

### ISSUE THREAD

**Issue by mrunmayi29** [wxFormBuilder/wxFormBuilder#308]
In wxtreeListCtrl we have wxTL_CHECKBOX, but it selects only one item and not all children of that item. Can we have checkbox feature for wxtreectrl which will select all children of subtree when that parent node is selected? or Do we have such similar feature for any other tree component?

**Comment by jhasse** [comment]
Isn't that possible to implement in your code by listening on the callbacks?

**Comment by mrunmayi29** [comment]
yes, I used that, thank you
