### ISSUE TITLE
Leftover premake object files causes compilation to fail

### ISSUE THREAD

**Issue by jgmdev** [wxFormBuilder/wxFormBuilder#309]
It seems someone did a commit on a hurry and added the premake object files to the repository tree:

https://github.com/wxFormBuilder/wxFormBuilder/tree/master/build/premake/linux/obj/Release

Discovered this after various reports of failing builds on archlinux user repository where I'm the maintainer of the wxformbuilder-git package:

https://aur.archlinux.org/packages/wxformbuilder-git

**Comment by jhasse** [comment]
Thanks for reporting, I've removed the folder from git :)
