### ISSUE TITLE
Python bug while adding wx.adv.DatePickerCtrl

### ISSUE THREAD

**Issue by elitur** [wxFormBuilder/wxFormBuilder#312]
Hi,

Python code after adding "wx.adv.DatePickerCtrl":
import wx
import import wx.xrc
...
???  = wx.DatePickerCtrl(..., wx.DP_ALLOWNONE | wx.DP_DEFAULT | wx.DP_DROPDOWN | wx.DP_SHOWCENTURY)

Looks like must be:

import wx
import wx.adv
import wx.xrc
...
??? = wx.adv.DatePickerCtrl(..., wx.adv.DP_ALLOWNONE | wx.adv.DP_DEFAULT | wx.adv.DP_DROPDOWN | wx.adv.DP_SHOWCENTURY)

Thank you in advance and greate thanks for exellent product,

Eliyahu Turetsky

**Comment by undergraver** [comment]
Hi,

I have a pull request ready for this:

https://github.com/wxFormBuilder/wxFormBuilder/pull/322

Hope this helps,
Iulian

**Comment by jhasse** [comment]
Thanks for the PR :) Please reopen if this still happens with #322.
