### ISSUE TITLE
C++ Codegenerator: Expose sizers to derived class by putting them in the protected section of the header

### ISSUE THREAD

**Issue by hvMuc0001** [wxFormBuilder/wxFormBuilder#315]
I had to implement a fullscreen capability in our graphical frontend.
I realised it by using frame->ShowFullscreen( true,  wxFULLSCREEN_ALL)
The frame is my OpenGL frame, which then nicely enlarged to fullscreen.
On the side and below of the frame there are some tool and cmd input tool areas, which are needed to go away, when the OpenGL frame is fullscreen.
I did this with bSizer4->Show(false) and bSizer2->Show(false) which where the top sizers of the respective tool areas.
To do it nicely I implemented that in the derived frame and made it reachable by a key.
The only downside was that the two sizers were local to the FrameBase::FrameBase constructor and I needed the declarations of the sizers ( wxBoxSizer* bSizer4; ... ) go to the protected part of the FrameBase.h header.
After that it worked really nicely as expected.
Unfortunately now I have to move these sizers every time to the header, when I change the layout.
Would it be possible to add a check box "Expose Sizer" ( or in general "Expose <Element>" ) to move the individual element to the header...
Is there any other way to do that and I just overlooked it ? 

And thanks for the really excellent tool. Totally love it...

**Comment by jhasse** [comment]
What about using `GetSizer` on their parents?

**Comment by hvMuc0001** [comment]
The problem is that the hierarchy is quite deep to achieve the desired layout with all the subelements... 
Using wxFormBuilder generates the hierarchy and code fine but somewhat shielded within the constructor of FrameBase.
Within the constructor all the menu items and sizers are declared in local scope and are then added to each other to create the desired hierarchy and layout... 
This works fine as long as one doesn't want to switch off individual sizers and do a fullscreen afterwards..
Are there any means to find a specific 'tagged' sizer?
Otherwise I do have a bSizer2 in code which I have no handle or pointer to it. 

Example of the layout:

![graph1](https://user-images.githubusercontent.com/2496604/31458411-504dd840-aec0-11e7-8371-728f2e037737.png)

I need to switch off bSizer2 and bSizer4 and basically don't know how to access them from outside the constructor..
When putting these sizers in the header in protected scope I at least would be able to access them in the derived class and do what I want with them...

Any ideas other than my original question ?

**Comment by jhasse** [comment]
What about setting C++ -> permission to protected on the Sizers?

**Comment by hvMuc0001** [comment]
Hello Jan,

That is actually what I was looking for... By setting the c++-permissions to protected, the declaration went into the header and I could access the sizers in the derived class. 
I just didn't know that feature.
So thanks a lot for directing me !

Best regards,
Hans

**Comment by jhasse** [comment]
You're welcome :)
