### ISSUE TITLE
Editing "choices" for wxComboBox or wxChoice leads to crash

### ISSUE THREAD

**Issue by peralmered** [wxFormBuilder/wxFormBuilder#318]
To recreate crash:

1. Start a new project
2. Add a frame
3. Add a wxBoxSizer
4. Throw in a wxScrolledWindow
5. Make a wxGridBagSizer
6. Put in a wxStaticText
7. Insert a wxComboBox
8. In Object Properties, "choices", add a couple of options and click "Ok"
9. Click the Frame in the Designer view

Replacing wxComboBox with wxChoice leads to the exact same result.

Tried both v3.6.0 and the latest stable Windows build as of 2017-10-13.
Windows 10 Home x64, fully updated 2017-10-13, 16GB RAM.

**Comment by peralmered** [comment]
Video:

[https://youtu.be/JehiRbzUdCU](url)

**Comment by sodevel** [comment]
Most probably same reason like #536
