### ISSUE TITLE
TreeListCtrl is now in wx.dataview instead of wx in wxPython Phoenix

### ISSUE THREAD

**Issue by somelinguist** [wxFormBuilder/wxFormBuilder#324]
Just ran into "AttributeError: module 'wx' has no attribute 'TreeListCtrl'".

See https://wxpython.org/Phoenix/docs/html/wx.dataview.TreeListCtrl.html

It looks like TreeListCtrl and its styles are now under wx.dataview in wxPython Phoenix, but wxFormBuilder still produces code that assumes it's in wx.

I'm running the latest Windows build as of Oct 25, 2017.

Also, it adds the control to the parent, but then doesn't reference it using self:

```python
    self.results_list = wx.TreeListCtrl( self.left_panel, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, wx.TL_DEFAULT_STYLE|wx.TL_SINGLE )
    results_list.AppendColumn( u"Source", wx.COL_WIDTH_DEFAULT, wx.ALIGN_LEFT, wx.COL_RESIZABLE|wx.COL_SORTABLE )
```

**Comment by jmagic** [comment]
Hi somelinguist,

I've just tested this in wxFormBuilder v3.6.2, and when I create a TreeListCtrl I get the following code:
![image](https://user-images.githubusercontent.com/1159605/39605764-57989774-4f75-11e8-92a0-cb2b18a0dd2d.png)

Which seems to be appropriately using wx.dataview.

Could you try creating a new TreeListCtrl and see if you have the same results?

Thanks,
Jim M

**Comment by somelinguist** [comment]
Looks good. Thanks!
