### ISSUE TITLE
generate frame code can not work in linux

### ISSUE THREAD

**Issue by 561546441** [wxFormBuilder/wxFormBuilder#327]
`class MyFrame10 ( wx.Frame ):
	
	def __init__( self, parent ):
		wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = wx.EmptyString, pos = wx.DefaultPosition, size = wx.Size( 500,300 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )
		
		self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
		
		
		self.Centre( wx.BOTH )
	
	def __del__( self ):
		pass
	

`

the function self.SetSizeHints( wx.DefaultSize, wx.DefaultSize ) can not work.

wxFormBuilder version: 3.6.1
g++ version: 4.9.4
os: ubuntu14.04

**Comment by jhasse** [comment]
> can not work.

What do you mean by that?

**Comment by jlxip** [comment]
Confirmed. The default generated code for Python seems to be obsolete (?). Tested in wxFormBuilder 3.6.1.
`self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )` produces an error:

`TypeError: in method 'Window_SetSizeHints', expected argument 2 of type 'int'`

Running in python interpreter: `wx.DefaultSize` returns `wx.Size(-1, -1)`.
So changing the generated code to:
`self.SetSizeHints( -1, -1 )` works as it should.

**Comment by jlxip** [comment]
Also, removing the line which causes the error seems to work as well.

**Comment by jlxip** [comment]
Maybe it's not the program itself but `wxPython`, as I'm using version 3.0.2.0.

**Comment by 561546441** [comment]
Now, I use self.SetSizeHintsSz instaed of self.SetSizeHints.

**Comment by jlxip** [comment]
@561546441 Is there any way to make that the default generated code?

**Comment by stuartaw** [comment]
Your link for the over version is no longer valid.

For us poor saps limited to wxPython 2.x, perhaps you could let us know the secret of WHEN this change happened, therefore what old version we should look for? that would be most helpful..

**Comment by jmagic** [comment]
I'm sorry to hear the link isn't working for you, it still seems to be working for me.

The version it is pointing to is wxFormBuilder_v3.5.1-rc1.exe, 

I think the change happened when wx and wxFormBuilder moved to version 4. "_This was a change in the API from 3.x.x to 4.x.x: https://docs.wxpython.org/classic_vs_phoenix.html?highlight=setsizehints_"

Good luck with your old code!
