### ISSUE TITLE
Unable to import wx.xrc

### ISSUE THREAD

**Issue by peredur02** [wxFormBuilder/wxFormBuilder#328]
wxFormBuilder imports wx and wx.xrc. However the second of these causes an error on my Ubuntu 17.10 system as follows:

Traceback (most recent call last): File "/home/peter/python/wxpython/wxFormBuilder/Demo/demo.py", line 4, in module 

import demogui 

File "/home/peter/python/wxpython/wxFormBuilder/Demo/demogui.py", line 11, in module 

import wx.xrc 

File "/usr/local/lib/python3.6/dist-packages/wx/xrc.py", line 10, in module 

from ._xrc import * 

ImportError: libwx_gtk3u_html-3.0.so.0: cannot open shared object file: No such file or directory

The obvious answer would be that the file was missing, but it isn't:

peter@peter-HP-Pavilion-15-Notebook-PC:~$ locate libwx_gtk3u_html-3.0.so.0

/usr/local/lib/python3.6/dist-packages/wx/libwx_gtk3u_html-3.0.so.0

So, to my inexperienced eyes it seems to be present and in the right place.  Is this an error with my system or with wxFormBuilder (and apologies if it's the former).

I'm using wxPython for Python 3, by the way.

Many thanks

**Comment by jhasse** [comment]
How did you install wxFormBuilder?

**Comment by peredur02** [comment]
Downloaded version 3.6.1 from GitHub and then ran the installer.

**Comment by jhasse** [comment]
Which installer?

Can you post the output of `file /usr/local/lib/python3.6/dist-packages/wx/libwx_gtk3u_html-3.0.so.0` and `python --version`.

**Comment by peredur02** [comment]
El 24/11/17 a las 14:26, Jan Niklas Hasse escribió:
>
> Which installer?
>
> Can you post the output of |file 
> /usr/local/lib/python3.6/dist-packages/wx/libwx_gtk3u_html-3.0.so.0| 
> and |python --version|.
>
>

The make file in ../build/3.0/gmake, after running the 
create_build_files4.sh shell script.  Sorry, I should have made that 
clear.  It's a while ago...

The output of the commands is as follows:

peter@peter-HP-Pavilion-15-Notebook-PC:/usr/local/lib/python3.6/dist-packages/wx$ 
file /usr/local/lib/python3.6/dist-packages/wx/libwx_gtk3u_html-3.0.so.0
/usr/local/lib/python3.6/dist-packages/wx/libwx_gtk3u_html-3.0.so.0: ELF 
64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, 
BuildID[sha1]=a15b1b817e02ba19328f6b33c04e951528821d61, not stripped
peter@peter-HP-Pavilion-15-Notebook-PC:/usr/local/lib/python3.6/dist-packages/wx$ 
python --version
Python 2.7.14

As I'm sure you know, Python 2.7 is the default on Debian based systems 
due to various dependencies on it.  The python3 command is required to 
run Python v3.x

Thanks


Peter

-- 

*Peter Bradley*

**Comment by jhasse** [comment]
Try

```
export LD_LIBRARY_PATH=/usr/local/lib/python3.6/dist-packages/wx/
```

before you run Python.

**Comment by peredur02** [comment]
Yep.  That works.

**Comment by jhasse** [comment]
Please reopen, if something still doesn't work.
