### ISSUE TITLE
Is it possible to set the values of wxEnumProperty from wxFormBuilder?

### ISSUE THREAD

**Issue by muman613** [wxFormBuilder/wxFormBuilder#330]
Hello,

I have spent the last 2 hours trying to figure out how the have wxFormBuilder 3.5.2-rc2 allow me to set the values of a wxEnumProperty in a Property Grid. I can manually edit the generated code (which is anathema to the entire process) and get the enumerated types to show. But I cannot for the life of me figure out how the set the enumerated types once the property grid is completely initialized by the base class (generated by wxFormBuilder). This is aggrevating because I love wxFormBuilder and don't want to have to manually patch the generated code every time I tweak the UI in the form builder.

Thank you,
Michael Uman

**Comment by NewPagodi** [comment]
In the constructor for the derived class, you can add items to the enum property like so:
```
wxPGProperty* prop = m_propertyGrid1->GetProperty("Property Name");

prop->AddChoice("val 1", 0);
prop->AddChoice("val 2", 1);
prop->AddChoice("val 3", 2);
prop->AddChoice("val 4", 3);
prop->AddChoice("val 5", 4);
```

**Comment by muman613** [comment]
NewPagodi,

Thank you very much for your prompt reply. That seems like an acceptable way to initialize the enum property. 

Michael Uman
