### ISSUE TITLE
Dies on startup under XP

### ISSUE THREAD

**Issue by DRNadler** [wxFormBuilder/wxFormBuilder#332]
Here's the error dialog:

<img width="401" alt="wxformbuilder_v3 6 1 dies under xp" src="https://user-images.githubusercontent.com/12815332/33290225-0e89a28c-d390-11e7-9404-ba6b4e0c7895.png">

**Comment by jhasse** [comment]
It was never tested with XP (and I don't have a copy anymore). Your only option is to try to compile wxFormBuilder yourself (see README).
