### ISSUE TITLE
build error under Linux

### ISSUE THREAD

**Issue by geenweb** [wxFormBuilder/wxFormBuilder#333]
The documented build process worked fine (except needed to change directory name from 3.0 to 3.1) without errors or warnings until make. Make errors out with:
==== Building TiCPP (release) ====
ticpp.cpp
g++: error: unrecognized command line option ‘-std=c++14’
make[1]: *** [obj/Release/TiCPP/ticpp.o] Error 1
make: *** [TiCPP] Error 2

**Comment by jhasse** [comment]
Which distribution are you using? Looks like your GCC is too old.

**Comment by geenweb** [comment]
I was using 4.8. I just updated to 6 and it compiled cleanly. Thanks!
