### ISSUE TITLE
Not found file on compilation

### ISSUE THREAD

**Issue by hildogjr** [wxFormBuilder/wxFormBuilder#341]
Error on compilation at Ubuntu 16.04, not founded a file library (is it missing some dependence installation?)

    ==== Building TiCPP (release) ====
    ==== Building plugin-interface (release) ====
    xrcconv.cpp
    ../../sdk/plugin_interface/xrcconv.cpp:33:19: fatal error: ticpp.h: No such file or directory
    compilation terminated.
    plugin-interface.make:130: recipe for target 'obj/Release/plugin-interface/xrcconv.o' failed
    make[1]: *** [obj/Release/plugin-interface/xrcconv.o] Error 1
    Makefile:20: recipe for target 'plugin-interface' failed
    make: *** [plugin-interface] Error 2

**Comment by jhasse** [comment]
You need to init the submodules ;)
