### ISSUE TITLE
A Fatal Error Occurred.

### ISSUE THREAD

**Issue by putong888** [wxFormBuilder/wxFormBuilder#343]
23:08:02: 000 4376185 /home/zhangt/wxFormBuilder/output/bin/wxformbuilder   
23:08:02: 001 -488875764 /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0   
23:08:02: 002 -500325200 /lib/x86_64-linux-gnu/libc.so.6   
23:08:02: 003 5643197  wxSizer::Add(wxSizer*, int, int, int, wxObject*)  
23:08:02: 004 -490311170 /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0 wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const  
23:08:02: 005 -488712473 /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0 wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)  
23:08:02: 006 -488712229 /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0 wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)  
23:08:02: 007 -488711285 /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0 wxEvtHandler::TryHereOnly(wxEvent&)  
23:08:02: 008 -488711149 /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0 wxEvtHandler::ProcessEventLocally(wxEvent&)  
23:08:02: 009 -488711051 /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0 wxEvtHandler::ProcessEvent(wxEvent&)  
23:08:02: 010 -488711705 /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0 wxEvtHandler::SafelyProcessEvent(wxEvent&)  
23:08:02: 011 -480795450 /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0   
23:08:02: 012 -509068564 /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0   
23:08:02: 013 -515534939 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 g_closure_invoke  
23:08:02: 014 -515461183 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0   
23:08:02: 015 -515426311 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 g_signal_emit_valist  
23:08:02: 016 -515424113 /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 g_signal_emit  
23:08:02: 017 -507922116 /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0   
23:08:02: 018 -509074812 /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 gtk_propagate_event  
23:08:02: 019 -509073861 /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 gtk_main_do_event  
23:08:02: 020 -512791412 /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0   
23:08:02: 021 -525319785 /lib/x86_64-linux-gnu/libglib-2.0.so.0 g_main_context_dispatch  
23:08:02: 022 -525319184 /lib/x86_64-linux-gnu/libglib-2.0.so.0   
23:08:02: 023 -525318382 /lib/x86_64-linux-gnu/libglib-2.0.so.0 g_main_loop_run  
23:08:02: 024 -509077865 /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0 gtk_main  
23:08:02: 025 -480985387 /usr/lib/x86_64-linux-gnu/libwx_gtk2u_core-3.0.so.0 wxGUIEventLoop::DoRun()  
23:08:02: 026 -490040493 /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0 wxEventLoopBase::Run()  
23:08:02: 027 -490281370 /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0 wxAppConsoleBase::MainLoop()  
23:08:02: 028 4387327 /home/zhangt/wxFormBuilder/output/bin/wxformbuilder   
23:08:02: 029 -489705616 /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0 wxEntry(int&, wchar_t**)  
23:08:02: 030 4351304 /home/zhangt/wxFormBuilder/output/bin/wxformbuilder   
23:08:02: 031 -500410320 /lib/x86_64-linux-gnu/libc.so.6 __libc_start_main  
23:08:02: 032 4374089 /home/zhangt/wxFormBuilder/output/bin/wxformbuilder   
23:08:02: A Fatal Error Occurred. Click Details for a backtrace.

**Comment by jhasse** [comment]
Which Linux distribution is this?

**Comment by putong888** [comment]
ubuntu 16.04

**Comment by jhasse** [comment]
When did the error appear? I.e. what would I need to do to reproduce it?
