### ISSUE TITLE
Wrong code generated for wxPython Appending MenuItem

### ISSUE THREAD

**Issue by bazza2jw** [wxFormBuilder/wxFormBuilder#349]
The generated code for a menu and  menu item is:
	self.m_menu11 = wx.Menu()
		self.m_menuItem1 = wx.MenuItem( self.m_menu11, wx.ID_ANY, u"MyMenuItem", wx.EmptyString, wx.ITEM_NORMAL )
		self.m_menu11.Append( self.m_menuItem1 )

This fails with wxPython because the self.m_menu11.Append( self.m_menuItem1 ) should be self.m_menu11.AppendItem( self.m_menuItem1 )

Likewise appending sub menus should use AppendSubMenu.

**Comment by jmagic** [comment]
HI bazza2jw,

I think this is expected. wxFormBuilder is generating code for wxPython version 4.0.1
The API is here: https://docs.wxpython.org/wx.Menu.html#wx.Menu.Append

If you are still using wxPython version 3.X.X, and you want to use wxFormBuilder, you can get an older version from here: https://sourceforge.net/projects/wxformbuilder/files/latest/download?source=files

To migrate to wxPython version 4, check out the migration guide: https://docs.wxpython.org/MigrationGuide.html
