### ISSUE TITLE
Flatpak installation fails with GPG error

### ISSUE THREAD

**Issue by acolomb** [wxFormBuilder/wxFormBuilder#354]
Tried to install the 3.6.2 release from `wxformbuilder.flatpak` on Ubuntu 17.10.  I get the following error:

    error: GPG verification enabled, but no signatures found (use gpg-verify=false in remote config to disable)

How can I override that? The `flatpak install --bundle ...` command automatically creates a "remote" where gpg verification **is** already disabled:

    $ flatpak remote-list --show-disabled --show-details
    flathub   Central repository of Flatpak applications https://dl.flathub.org/repo/   1
    org.wxformbuilder.wxFormBuilder-origin   wxformbuilder.flatpak   0 no-gpg-verify,disabled,no-enumerate

So is the bundle somehow broken?

**Comment by jhasse** [comment]
I think it's a flatpak bug: https://github.com/flatpak/flatpak/issues/388

Try running `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo` and then try to install the flatpak again.

**Comment by acolomb** [comment]
Sorry, that doesn't help. As my listing in the original report shows, the flathub repo was already configured correctly, but I retried anyway by deleting and re-creating it as you suggested.

The signature verification fails not for the flathub summay files, but the actual flatpak bundle downloaded here on Github.

**Comment by jhasse** [comment]
It works for me on Fedora 27, so I'm not sure what's causing it :(

**Comment by acolomb** [comment]
After updating to Ubuntu 18.04 a few days ago, installation of the flatpak bundle now worked flawlessly.  Seems whatever changes went into Ubuntu's flatpak package, it's now fixed.

**Comment by jhasse** [comment]
Good to know, I will close this for now :)

**Comment by kelmes** [comment]
On Ubuntu 18.10 it seems this issue is still present. Trying to install a locally build (unsigned) flatpak using
```
flatpak install --bundle org.gnome.Epiphany.flatpak
```
 I get:
```
error: Failed to install bundle org.gnome.Epiphany/x86_64/master: GPG verification enabled, but no signatures found (use gpg-verify=false in remote config to disable)
```

As above, I appear to have a new remote where gpg verification is disabled
```
 flatpak remote-list --show-disabled --show-details
Name                                         Title                      URL                                      Collection ID Priority Options                                 
flathub                                      Flathub                    https://dl.flathub.org/repo/             -             1        system                                  
gnome-apps-nightly                           GNOME Nightly Applications https://sdk.gnome.org/nightly/repo-apps/ -             1        system                                  
gnome-nightly                                GNOME Nightly Runtime      https://sdk.gnome.org/nightly/repo/      -             1        system                                  
flathub                                      Flathub                    https://dl.flathub.org/repo/             -             1        user                                    
gnome                                        Gnome Stable Runtimes      https://sdk.gnome.org/repo/              -             1        user                                    
gnome-nightly                                GNOME Nightly Runtime      https://sdk.gnome.org/nightly/repo/      -             1        user                                    
com.belledonnecommunications.linphone-origin Linphone                   https://linphone.org/flatpak/            -             0        user,no-enumerate                       
org.gnome.Epiphany-origin                    org.gnome.Epiphany.flatpak                                          -             0        user,disabled,no-enumerate,no-gpg-verify
```

**Comment by kelmes** [comment]
Actually, this seems to have been just a misleading error message. I uninstalled another copy of the same application (from a different remote) and now it works.

**Comment by jhasse** [comment]
Good to know :) Hopefully flatpak will fix this at some point.

**Comment by nikodunk** [comment]
> Actually, this seems to have been just a misleading error message. I uninstalled another copy of the same application (from a different remote) and now it works.

This misleading error message still exists today, and your uninstall advice still works! Thank you :)

**Comment by Inmoresentum** [comment]
> Actually, this seems to have been just a misleading error message. I uninstalled another copy of the same application (from a different remote) and now it works.

This works. So the bug still exists even today.

**Comment by kenshanta** [comment]
> I think it's a flatpak bug: [flatpak/flatpak#388](https://github.com/flatpak/flatpak/issues/388)
> 
> Try running `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo` and then try to install the flatpak again.

The Problem and Solution are still accepted for `**Fedora 39`**

**Comment by gegentan** [comment]
I had the same issue. I fixed it with just rebooting.

**Comment by trusktr** [comment]
In my case, after removing some of my flatpaks, and then running `flatpak uninstall --unused` to prune unused dependencies, trying to install my desired flatpak worked and I no longer got the above error regarding missing GPG signatures.

Looks like this is a usability issue with flatpak, the error is not very helpful because it's a problem with a pre-existing flatpak being already installed, but the error says GPG signatures missing.
