### ISSUE TITLE
Install from Sources for Windows not working as described

### ISSUE THREAD

**Issue by miikeat** [wxFormBuilder/wxFormBuilder#359]
I tried to build wxfb from sources as described in the readme.
The buildprocess seems to work fine but when I try to run the binary i get these errors for most of the dlls that come with the windows installation package:

```The code execution cannot proceed because libstdc++-6.dll was not found. Reinstalling the program may fix this problem.```

When I copy them from the installed directory I get this error message but I have no clue what to do now...

```wxFormBuilder.exe - Entry Point Not Found 
The procedure entry point _ZTV17wxFindReplaceData could not be located in the 
dynamic link library C:\msys64\home\User\wxFormBuilder\output\wxFormBuilder.exe.
```

And no, I did not build it with msys64, but msys32 is just installed as well to that directory!

**Comment by jhasse** [comment]
How did you run wxFormBuilder? It should be

```
cd ../../../output/
./wxFormBuilder.exe
```

from the MinGW 32 bit shell.

Btw: Using msys64 or msys32 doesn't matter (in fact I only test with msys64), what's important is to use MinGW 32 bit.

**Comment by miikeat** [comment]
When i tried that after building nothing happend (it hang with a blinking cursor) so i ran it from explorer.

When i try it now after copying all the dlls it does nothing, just returns to the shell instantly

**Comment by jhasse** [comment]
Where did you copy the DLLs from?

**Comment by miikeat** [comment]
from the windows installation package (wxFormBuilder_v3.6.1.exe)

**Comment by miikeat** [comment]
after building i had just the wxFormBuilder.exe, Changelog and Licence.txt and the 3 directories in my output directory

**Comment by jhasse** [comment]
They are from an older version of MSYS2 / MinGW-w64, that's why you got the missing entry point error.

Copy them from `C:\msys64\mingw32\bin` instead. But in theory this shouldn't be necessary in the MinGW 32 Bit shell, the instructions in the README should work. Sorry about that, I'll have a look.

**Comment by miikeat** [comment]
Ahh .. i'll try that ASAP, unfortunately I have to leave now, but I'll give it a try latest tomorrow!
Maybe something went wrong when creating the symbolic links...

**Comment by miikeat** [comment]
Thanks! unlinking and recreating the symbolic links did the trick!
