### ISSUE TITLE
Rpm support

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#36]
It would be great if you could make a rpm package. I would like to use it under Fedora and, although I've tried to install it several times I couldn't make it work. 

Reported by: *anonymous

**Comment by patlkli** [comment]
@jhasse Do you really want to do this for the 3.6.0 release with the old build system?

**Comment by jhasse** [comment]
You're right, I better do this for CMake, otherwise I'll have to redo all the work ;)

**Comment by jhasse** [comment]
I think it might make sense to create a Flatpak instead, as the support on Fedora is pretty good. Also this would cover many other Linux distributions.

I've created a new issue here: #273

**Comment by patlkli** [comment]
@jhasse It would definitely hinder getting wxFormBuilder into official package repositories of Fedora or other RPM-based distros, if we decide to drop this...

**Comment by jhasse** [comment]
That's true, it's just that I don't have the time to work on this right now. Feel free to reopen if you want to take over.
