### ISSUE TITLE
Fatal error while ctrl+z

### ISSUE THREAD

**Issue by filsek** [wxFormBuilder/wxFormBuilder#367]
Extremely annoying bug, that actually brought me to drop wxFormBuilder.
When you press ctrl+z three times, the application crashes and ALL of your changes since
last startup are lost permanently. So long few hours of work.
Doesn't matter is you ctrl+s during your work. The file is in state before any work.

Working on Ubunti 16.4LTS setup on Windows 10 via Oracle VirtualBox.

**Comment by jhasse** [comment]
I couldn't reproduce this, could you provide an example project where this happens?

Also: Are you running wxFormBuilder on Ubuntu or Windows? VirtualBox shouldn't matter.
