### ISSUE TITLE
Incompatibility with wxPython code generation

### ISSUE THREAD

**Issue by bertbarabas** [wxFormBuilder/wxFormBuilder#368]
**wxFormBuilder version**: v3.6.2
**Operating system**: Window 10
**wxPython version**: 4.0.1
**Python version**: 3.6.4

**Description of the problem**:
There is an incompatibility with wxPython code generation.

wxFormBuilder generates code to call Ok on Bitmap but wxPython calls the method IsOk.

wxFormBuilder also generates code to call SetBitmapHover instead of SetBitmapCurrent on BitmapButton.

**Comment by jmagic** [comment]
Hi bertbarabas,

Could you give me more detail on how you get the Bitmap in wxFormBuilder? 

I can only find wxStaticBitmap, and no way to add the method....

I'm working on the changes for SetBitmapCurrent.

Thanks,
Jim M

**Comment by bertbarabas** [comment]
Hi Jim,

There are a number of widgets that provide a "load from file" parameter for loading bitmaps. E.g. here is the code generated for a wxPanel in a wxListBook but there are several other widgets that allow you to load wx.Bitmap. As you can see below the generated code calls Ok() but wxBitmap only understand IsOk(). 

`self.listbookMainPanel.AddPage( self.m_panelRules, u"Rules", False )
listbookMainPanelBitmap = wx.Bitmap( u"Rules1.png", wx.BITMAP_TYPE_ANY )
if ( listbookMainPanelBitmap.Ok() ):
	listbookMainPanelImages.Add( listbookMainPanelBitmap )`

Looking at the generated code again, I wonder if the code generator only calls Ok() on wxBitmaps when adding pages to a listBook because I don't immediately see any other examples.

Best regards,
Bert
