### ISSUE TITLE
Crash when change the wxWindow.size.Width

### ISSUE THREAD

**Issue by Dambuster88** [wxFormBuilder/wxFormBuilder#369]
My program is crashing when I change the width of the window.
None of the other properties is crashing the program, only the width.
Windows 7 x64
wxFormBuilder v.3.6.2
```
22:10:54: 0x62721adc: ZN11wxSizerItem4FreeEv in C:\Program Files (x86)\wxFormBuilder\wxmsw30u_core_gcc_custom.dll
22:10:54: 0x4dbc02: VisualEditor::Create() in C:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
22:10:54: 0x4dd3d5: VisualEditor::OnPropertyModified(wxFBPropertyEvent&) in C:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
22:10:54: 0x71382bc2: ZNK16wxAppConsoleBase11HandleEventEP12wxEvtHandlerMS0_FvR7wxEventES3_ in C:\Program Files (x86)\wxFormBuilder\wxbase30u_gcc_custom.dll
22:10:54: 0x71382f77: ZNK16wxAppConsoleBase16CallEventHandlerEP12wxEvtHandlerR14wxEventFunctorR7wxEvent in C:\Program Files (x86)\wxFormBuilder\wxbase30u_gcc_custom.dll
22:10:54: A Fatal Error Occurred. Click Details for a backtrace.

```

**Comment by jhasse** [comment]
Do you know which steps can reproduce the crash?

**Comment by Erriez** [comment]
I can reproduce this on Windows and Linux with v3.6.2 and an earlier wxFormBuilder version 3.5.

A screenshot:
![wxformbuilderfatalerror](https://user-images.githubusercontent.com/8849873/38048761-911d8d86-32c6-11e8-80e3-862fa968ce09.png)

To reproduce this:
1. Add a frame and wxBoxSizer.
2. Select the Frame and set small window size: Width = 2 and Height = 2.
3. Change minimum_size Width = 3 and Height = 100.

My last change was minimum_size Width = 3 which crashed wxFormBuilder.

**Comment by Erriez** [comment]
Thank Jan! Problem solved.
