### ISSUE TITLE
UI problem with system Dark Theme

### ISSUE THREAD

**Issue by Yousha** [wxFormBuilder/wxFormBuilder#374]
Look at the screenshot please:

http://oi68.tinypic.com/2w7jui1.jpg

It's because I'm using DARK THEME for my Windows OS(7) and texts colors in Properties panel are Hardcoded... So wxFormBuilder is not able to use native/system color

Both text and background are white

**Comment by tvanderpool** [comment]
This affects linux as well. Ubuntu 14.04 & 18.04
wxFormBuilder v3.5.2-RC2
![image](https://user-images.githubusercontent.com/13110204/43174123-0738b324-8f7e-11e8-951b-2d595395bc02.png)

**Comment by jhasse** [comment]
Can you try again with a recent wxFormBuilder version and wxWidgets 3.1?

**Comment by Yousha** [comment]
"Properties" panel and Designer is FIXED but "Events" panel is NOT fixed yet:

![](http://oi67.tinypic.com/34opj45.jpg)

**Comment by tester0077** [comment]
I am running into a problem which looks like it is related to the 'theme'
Running Windows 10, 64-bit, latest Github version built from source with MSVC 2019 
Workflow:
Start new project
add a main frame
crashes debug version
![NewProjectTheme-issue](https://user-images.githubusercontent.com/9053628/163055661-fc4b19fb-8289-498b-abba-ef6d0b8c7806.jpg)

**Comment by sodevel** [comment]
No its not, see my answer in #734
