### ISSUE TITLE
fix for:  cannot find -lwx_gtk2u_media-3.0

### ISSUE THREAD

**Issue by sigoa** [wxFormBuilder/wxFormBuilder#375]
use ./create_build_files4.sh   --disable-mediactrl  
to avoid link error during build :

Linking wxFormBuilder
/usr/bin/ld: cannot find -lwx_gtk2u_media-3.0
collect2: error: ld returned 1 exit status
wxFormBuilder.make:134: rule for target  „../../../output/bin/wxformbuilder-30“  breakage
make[1]: *** [../../../output/bin/wxformbuilder-30] error 1
Makefile:44: rule for target „wxFormBuilder“ breakage

**Comment by jhasse** [comment]
You need to install `libwxgtk-media3.0-dev` as mentioned in the README.
