### ISSUE TITLE
make line endings configurable

### ISSUE THREAD

**Issue by graph** [wxFormBuilder/wxFormBuilder#383]
Currently it's hard coded based on OS. I would like it to be a setting for the project.

**Comment by jhasse** [comment]
What line endings are you looking for?

**Comment by graph** [comment]
unix style LF. Currently it does CRLF on windows and no way to change it. And on linux it does LF and no way to change it.

**Comment by jhasse** [comment]
> unix style LF

Good, this will happen in the next wxFormBuilder version :)

IMHO LF is the future and CRLF needs to die. Therefore I don't think that there needs to be a setting for it ;)
