### ISSUE TITLE
Linking Grid Control to Database

### ISSUE THREAD

**Issue by dcapeletti** [wxFormBuilder/wxFormBuilder#387]
Today I'm working on a project that could be huge and used wxformbuilder as a tool to speed up the graphical interface that I then modify through the inheritance in python so as not to touch the files generated by wxformbuilder.

The point is that I work with a database of approximately 276 tables, about 90 queries in the DB plus some in the code.

I use [ORM sqlalchemy](http://www.sqlalchemy.org/) technology together with mysql and wxpython as part of the graphical interface. The ORM is responsible for table definition and data persistence in the Database.

To work with grids I have to write a lot of python code to load and list the records in them and then write code to save them in the DB, which is somewhat problematic when you have more than 5 grids per screen.

I was wondering if wxformbuilder can't help us in some way, for example linking the grid control to a DB table either by the ORM or by the driver directly, by both or by another method.
The aim is to list the records in a table and if the user modifies a data, that can be saved in the DB without writing so much python code.

Thank you so much for reading me.

**Comment by dcapeletti** [comment]
If you know of any kind of python wrapping to load a table into the grid, you can comment on it here. Thank you very much

**Comment by jhasse** [comment]
I think you might actually get a better answer asking on stackoverflow.com or a similar forum. If I'm not mistaken, wxFormBuilder doesn't have any functionality for what you're describing (and is lacking the manpower to implement it), so I'm closing this for now.
