### ISSUE TITLE
wxWrapSizer

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#39]
Please add wxWrapSizer also into the "Layout" component palette. (It is pretty much similar to a wxBoxSizer, so I guess it wouldn't take too much effort to add it, but it would have been an enermous help for my project.)

Reported by: tiborgats

**Comment by Poddster** [comment]
A wrap-sizer would be very useful. Currently I'm having to use a normal box and then patch the generated code.

**Comment by fdelapena** [comment]
I think this is implemented since #258.
