### ISSUE TITLE
About Dialog shows raw HTML

### ISSUE THREAD

**Issue by IanSimcock** [wxFormBuilder/wxFormBuilder#392]
In the current and previous versions (possibly earlier too, I'm not sure), when I open the about dialog the windows contains raw HTML code rather than rendered HTML.

The fact that I can't see anyone else mentioning this makes me wonder if it's just me, but I can see how.

I'm running Windows 8 and WxFormBuilder 3.6.2.

Ian.

**Comment by jhasse** [comment]
I can't reproduce this on Windows 8 or Linux. Can you post a screenshot and try with a version compiled from source?

**Comment by IanSimcock** [comment]
I don't have a C++ working compiler, so I can't build it from source, but
attached is the requested screen shot.

Ian.

**Comment by jhasse** [comment]
I can't see the screenshot, I think you have to use GitHub to upload it.

**Comment by IanSimcock** [comment]
I guess that GitHub doesn't handle attachments, since the image was there and I had to save it from the email to attach it here :-)

Anyway, I hope it gives some sort of clue as to what's happening.

Ian.

![wxformbuilder with about dialog](https://user-images.githubusercontent.com/5259565/40668183-04cca430-63a3-11e8-8474-0c568258b21a.png)
