### ISSUE TITLE
App hangs upon adding choices in wxListBox

### ISSUE THREAD

**Issue by ksaurabh02** [wxFormBuilder/wxFormBuilder#393]
Application hangs on Mac when you add wxListBox choices. Does not crash but hangs.
Step to reproduce:
Add wxListBox item -> Add choices
Version: 3.6.2

**Comment by jhasse** [comment]
Can you attach a debugger?

**Comment by nohal** [comment]
FWIW, not reproducible here with a trivial project.

**Comment by jhasse** [comment]
Hm ... sounds like #348?

**Comment by nohal** [comment]
@jhasse may well be, I of course use a local build against wx 3.1.1...

**Comment by jhasse** [comment]
As everything is already merged, I think the only think I need to do is to tag 3.7.0, right?

**Comment by nohal** [comment]
I think so, the Travis builds are set to use `wxmac --devel` for some time already so the build product should be fine.

**Comment by jhasse** [comment]
All done.

@ksaurabh02 can you try the new release and see if that fixes this issue? https://github.com/wxFormBuilder/wxFormBuilder/releases/tag/v3.7.0

If not, please reopen.

**Comment by ksaurabh02** [comment]
It works. Thank you.
