### ISSUE TITLE
wxToolBar uses depricated wxPython method AddLabelTool. Should use AddTool instead

### ISSUE THREAD

**Issue by bertbarabas** [wxFormBuilder/wxFormBuilder#398]
**wxFormBuilder version**: v3.7.0
**Operating system**: Window 10
**wxPython version**: 4.0.1
**Python version**: 3.6.5

**Description of the problem**:

I am receiving the following message when running code generated by wxFormBuilder:

`wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  self.m_tool_Tabs = self.m_toolBar1.AddLabelTool( wx.ID_ANY, wx.EmptyString, wx.Bitmap( u"images/YPS__tags_W-512-30.png", wx.BITMAP_TYPE_ANY ), wx.NullBitmap, wx.ITEM_NORMAL, u"Tags", wx.EmptyString, None )
`

**Comment by eloyparedesq** [comment]
I have de same issue

wxFormBuilder version: v3.8.0

**Comment by gonesurfing** [comment]
Still present in 3.9.0
