### ISSUE TITLE
make config=release on windows install

### ISSUE THREAD

**Issue by loveknight11** [wxFormBuilder/wxFormBuilder#401]
when i run make config=release on windows i get this error
==== Building TiCPP (release) ====
ticpp.cpp
/bin/sh: g++: command not found
make[1]: *** [TiCPP.make:134: obj/Release/TiCPP/ticpp.o] Error 127
make: *** [Makefile:17: TiCPP] Error 2

**Comment by jhasse** [comment]
Make sure you are in a MinGW 32 bit shell and that you've run the pacman command. Reopen this issue if it still happens.
