### ISSUE TITLE
error to Import wx.combo

### ISSUE THREAD

**Issue by Moriand** [wxFormBuilder/wxFormBuilder#411]
hello, when I try to execute the code, an error comes out saying that:
`module 'wx' has no attribute 'combo'`
at the moment I updated the wxpython to 4.0.2

**Comment by Moriand** [comment]
@jmoraleda  What happens is that I had written badly and did not have all the imported bookstores

**Comment by jmoraleda** [comment]
Per the documentation, in wxpython 4,`BitmapComboBox` has moved from `wx.combo` to `wx.adv` (https://wxpython.org/Phoenix/docs/html/wx.adv.BitmapComboBox.html#wx-adv-bitmapcombobox). There is no longer a `wx.combo` module so I it is indeed an error to `import wx.combo` and I am going to reopen the issue.
