### ISSUE TITLE
wxWidgets 3.1 Compile Fix

### ISSUE THREAD

**Issue by sodevel** [wxFormBuilder/wxFormBuilder#414]
The attached patch fixes the comile errors that occur when you compile against wxWidgets 3.1 with wxWidgets 3.0 Compatibility disabled.

The Patch is against 3bf169ee3b3c7476295cf3c9de0fe8fb760b503b

[wxfbadvprops_universal.zip](https://github.com/wxFormBuilder/wxFormBuilder/files/2160727/wxfbadvprops_universal.zip)

**Comment by jhasse** [comment]
Thanks! Can you create a pull request on GitHub with the patch?

**Comment by jhasse** [comment]
Nervermind, I've manually applied the patch :)
