### ISSUE TITLE
wxSpinCtrlDouble Fixes

### ISSUE THREAD

**Issue by sodevel** [wxFormBuilder/wxFormBuilder#415]
This patch adds some missing flags and event handlers to wxSpinCtrlDouble, it should have been part of #211 but sadly i forgot to include it there.

The patch is against 3bf169ee3b3c7476295cf3c9de0fe8fb760b503b, for your convenience the archive contains two files, one can be applied before applying #211, ther other one after applying #211. Keep in mind that #211 CAN NOT be applied anymore after using this patch without adjustments.

[wxspinctrldouble.zip](https://github.com/wxFormBuilder/wxFormBuilder/files/2161225/wxspinctrldouble.zip)

**Comment by jhasse** [comment]
If I understand it correctly, this can be closed now because of #426. Please reopen, if I'm mistaken.
