### ISSUE TITLE
"Move left" of an item inside a wxBoxSizer item

### ISSUE THREAD

**Issue by specing** [wxFormBuilder/wxFormBuilder#416]
"Move left" of an item inside a wxStaticBoxSizer inside a vertical wxBoxSizer moves said item to the bottom of the wxBoxSizer, not immidiately above or below the wxStaticBoxSizer. The latter would be much more appropriate.

the version is from git master, compiled a week ago.

**Comment by specing** [comment]
Nevermind, I momentarily forgot that items can be moved by just dragging them.

**Comment by jhasse** [comment]
Okay :)
