### ISSUE TITLE
Bug: Program crash when modifying icon size in wxStaticBitmap

### ISSUE THREAD

**Issue by ctfyui** [wxFormBuilder/wxFormBuilder#419]
Program crash when modifying iconsize in wxStaticBitmap

![Screenshot](https://user-images.githubusercontent.com/33893082/42407905-6ae0a872-81f6-11e8-8375-6e3af2511dce.png)

Error infomation

14:57:32: 0x75bf98cd: free in C:\Windows\syswow64\msvcrt.dll
14:57:32: 0x7151ada9: ZN19wxVariantDataStringD0Ev in D:\Program Files (x86)\wxFormBuilder\wxbase30u_gcc_custom.dll
14:57:32: 0x70d37b36: ZN14wxPropertyGrid17DoPropertyChangedEP12wxPGPropertyj in D:\Program Files (x86)\wxFormBuilder\wxmsw30u_propgrid_gcc_custom.dll
14:57:32: 0x70d32ab0: ZN14wxPropertyGrid23HandleCustomEditorEventER7wxEvent in D:\Program Files (x86)\wxFormBuilder\wxmsw30u_propgrid_gcc_custom.dll
14:57:32: 0x70d69f4a: ZN34wxPropertyGridEditorEventForwarder12ProcessEventER7wxEvent in D:\Program Files (x86)\wxFormBuilder\wxmsw30u_propgrid_gcc_custom.dll
14:57:32: 0x6261f626: ZN10wxTextCtrl6OnCharER10wxKeyEvent in D:\Program Files (x86)\wxFormBuilder\wxmsw30u_core_gcc_custom.dll
14:57:32: 0x71382bc2: ZNK16wxAppConsoleBase11HandleEventEP12wxEvtHandlerMS0_FvR7wxEventES3_ in D:\Program Files (x86)\wxFormBuilder\wxbase30u_gcc_custom.dll
14:57:32: 0x75bf98da: free in C:\Windows\syswow64\msvcrt.dll
14:57:32: 0x71464ef7: ZN9wxVariantD1Ev in D:\Program Files (x86)\wxFormBuilder\wxbase30u_gcc_custom.dll
14:57:32: 0x70d0cf07: ZNK18wxPGTextCtrlEditor7OnEventEP14wxPropertyGridP12wxPGPropertyP8wxWindowR7wxEvent in D:\Program Files (x86)\wxFormBuilder\wxmsw30u_propgrid_gcc_custom.dll
14:57:32: 0x71382f77: ZNK16wxAppConsoleBase16CallEventHandlerEP12wxEvtHandlerR14wxEventFunctorR7wxEvent in D:\Program Files (x86)\wxFormBuilder\wxbase30u_gcc_custom.dll
14:57:32: 0x714e41ee: ZN12wxEvtHandler23ProcessEventIfMatchesIdERK21wxEventTableEntryBasePS_R7wxEvent in D:\Program Files (x86)\wxFormBuilder\wxbase30u_gcc_custom.dll
14:57:32: 0x625698bd: ZN8wxWindow16MSWHandleMessageEPljjl in D:\Program Files (x86)\wxFormBuilder\wxmsw30u_core_gcc_custom.dll
14:57:32: 0x770a6d51: GetThreadDesktop in C:\Windows\syswow64\USER32.dll
14:57:32: 0x770b0d27: GetClientRect in C:\Windows\syswow64\USER32.dll
14:57:32: 0x770b0d4d: CallWindowProcW in C:\Windows\syswow64\USER32.dll
14:57:32: 0x6255ffe0: ZN8wxWindow16MSWDefWindowProcEjjl in D:\Program Files (x86)\wxFormBuilder\wxmsw30u_core_gcc_custom.dll
14:57:32: 0x6255a310: ZN8wxWindow13MSWWindowProcEjjl in D:\Program Files (x86)\wxFormBuilder\wxmsw30u_core_gcc_custom.dll
14:57:32: 0x770a7038: GetWindowLongW in C:\Windows\syswow64\USER32.dll
14:57:32: 0x626236fc: ZNK11wxTextEntry10IsEditableEv in D:\Program Files (x86)\wxFormBuilder\wxmsw30u_core_gcc_custom.dll
14:57:32: 0x6261c464: ZN10wxTextCtrl13MSWWindowProcEjjl in D:\Program Files (x86)\wxFormBuilder\wxmsw30u_core_gcc_custom.dll
14:57:32: 0x625620d2: Z9wxWndProcP6HWND__jjl in D:\Program Files (x86)\wxFormBuilder\wxmsw30u_core_gcc_custom.dll
14:57:32: 0x770a62fa: gapfnScSendMessage in C:\Windows\syswow64\USER32.dll
14:57:32: 0x770a6d3a: GetThreadDesktop in C:\Windows\syswow64\USER32.dll
14:57:32: 0x770a77c4: CharPrevW in C:\Windows\syswow64\USER32.dll
14:57:32: 0x770a788a: DispatchMessageW in C:\Windows\syswow64\USER32.dll
14:57:32: 0x770cc81f: IsDialogMessageW in C:\Windows\syswow64\USER32.dll
14:57:32: 0x6255d509: ZN8wxWindow22MSWSafeIsDialogMessageEP6tagMSG in D:\Program Files (x86)\wxFormBuilder\wxmsw30u_core_gcc_custom.dll
14:57:32: 0x625a7bad: ZN14wxGUIEventLoop17PreProcessMessageEP6tagMSG in D:\Program Files (x86)\wxFormBuilder\wxmsw30u_core_gcc_custom.dll
14:57:32: 0x4d0020: wxInnerFrame::wxInnerFrame(wxWindow*, int, wxPoint const&, wxSize const&, long) in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0xdbbbc9d6: [unknown function] in [unknown module]
14:57:32: 0xacbcf940: [unknown function] in [unknown module]
14:57:32: 0x32d86ce3: [unknown function] in [unknown module]
14:57:32: 0x45df5c75: [unknown function] in [unknown module]
14:57:32: 0xdcd60dcf: [unknown function] in [unknown module]
14:57:32: 0xabd13d59: [unknown function] in [unknown module]
14:57:32: 0x26d930ac: [unknown function] in [unknown module]
14:57:32: 0x51de003a: [unknown function] in [unknown module]
14:57:32: 0xc8d75180: [unknown function] in [unknown module]
14:57:32: 0xbfd06116: [unknown function] in [unknown module]
14:57:32: 0x21b4f4b5: [unknown function] in [unknown module]
14:57:32: 0x56b3c423: [unknown function] in [unknown module]
14:57:32: 0xcfba9599: [unknown function] in [unknown module]
14:57:32: 0xb8bda50f: [unknown function] in [unknown module]
14:57:32: 0x2802b89e: [unknown function] in [unknown module]
14:57:32: 0x5f058808: [unknown function] in [unknown module]
14:57:32: 0xc60cd9b2: [unknown function] in [unknown module]
14:57:32: 0xb10be924: [unknown function] in [unknown module]
14:57:32: 0x2f6f7c87: [unknown function] in [unknown module]
14:57:32: 0x58684c11: ImportCookieFileByProcessW in C:\Windows\SysWOW64\ieframe.dll
14:57:32: 0xc1611dab: [unknown function] in [unknown module]
14:57:32: 0xb6662d3d: [unknown function] in [unknown module]
14:57:32: 0x76dc4190: StrStrW in C:\Windows\syswow64\SHELL32.dll
14:57:32: 0x1db7106: [unknown function] in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0x98d220bc: [unknown function] in [unknown module]
14:57:32: 0xefd5102a: [unknown function] in [unknown module]
14:57:32: 0x71b18589: [unknown function] in [unknown module]
14:57:32: 0x6b6b51f: [unknown function] in [unknown module]
14:57:32: 0x9fbfe4a5: [unknown function] in [unknown module]
14:57:32: 0xe8b8d433: [unknown function] in [unknown module]
14:57:32: 0x7807c9a2: [unknown function] in [unknown module]
14:57:32: 0xf00f934: [unknown function] in [unknown module]
14:57:32: 0x9609a88e: [unknown function] in [unknown module]
14:57:32: 0xe10e9818: [unknown function] in [unknown module]
14:57:32: 0x7f6a0dbb: [unknown function] in [unknown module]
14:57:32: 0x86d3d2d: [unknown function] in [unknown module]
14:57:32: 0x91646c97: [unknown function] in [unknown module]
14:57:32: 0xe6635c01: [unknown function] in [unknown module]
14:57:32: 0x6b6b51f4: [unknown function] in [unknown module]
14:57:32: 0x1c6c6162: [unknown function] in [unknown module]
14:57:32: 0x856530d8: [unknown function] in [unknown module]
14:57:32: 0xf262004e: [unknown function] in [unknown module]
14:57:32: 0x6c0695ed: [unknown function] in [unknown module]
14:57:32: 0x1b01a57b: [unknown function] in [unknown module]
14:57:32: 0x8208f4c1: [unknown function] in [unknown module]
14:57:32: 0xf50fc457: [unknown function] in [unknown module]
14:57:32: 0x65b0d9c6: [unknown function] in [unknown module]
14:57:32: 0x12b7e950: [unknown function] in [unknown module]
14:57:32: 0x8bbeb8ea: [unknown function] in [unknown module]
14:57:32: 0xfcb9887c: [unknown function] in [unknown module]
14:57:32: 0x62dd1ddf: [unknown function] in [unknown module]
14:57:32: 0x15da2d49: [unknown function] in [unknown module]
14:57:32: 0x8cd37cf3: [unknown function] in [unknown module]
14:57:32: 0xfbd44c65: [unknown function] in [unknown module]
14:57:32: 0x4db26158: [unknown function] in [unknown module]
14:57:32: 0x3ab551ce: [unknown function] in [unknown module]
14:57:32: 0xa3bc0074: [unknown function] in [unknown module]
14:57:32: 0xd4bb30e2: [unknown function] in [unknown module]
14:57:32: 0x4adfa541: [unknown function] in [unknown module]
14:57:32: 0x3dd895d7: [unknown function] in [unknown module]
14:57:32: 0xa4d1c46d: [unknown function] in [unknown module]
14:57:32: 0xd3d6f4fb: [unknown function] in [unknown module]
14:57:32: 0x4369e96a: [unknown function] in [unknown module]
14:57:32: 0x346ed9fc: [unknown function] in [unknown module]
14:57:32: 0xad678846: [unknown function] in [unknown module]
14:57:32: 0xda60b8d0: [unknown function] in [unknown module]
14:57:32: 0x44042d73: [unknown function] in [unknown module]
14:57:32: 0x33031de5: [unknown function] in [unknown module]
14:57:32: 0xaa0a4c5f: [unknown function] in [unknown module]
14:57:32: 0xdd0d7cc9: [unknown function] in [unknown module]
14:57:32: 0x5005713c: [unknown function] in [unknown module]
14:57:32: 0x270241aa: [unknown function] in [unknown module]
14:57:32: 0xbe0b1010: [unknown function] in [unknown module]
14:57:32: 0xc90c2086: [unknown function] in [unknown module]
14:57:32: 0x5768b525: [unknown function] in [unknown module]
14:57:32: 0x206f85b3: [unknown function] in [unknown module]
14:57:32: 0xb966d409: [unknown function] in [unknown module]
14:57:32: 0xce61e49f: [unknown function] in [unknown module]
14:57:32: 0x5edef90e: [unknown function] in [unknown module]
14:57:32: 0x29d9c998: [unknown function] in [unknown module]
14:57:32: 0xb0d09822: [unknown function] in [unknown module]
14:57:32: 0xc7d7a8b4: [unknown function] in [unknown module]
14:57:32: 0x59b33d17: [unknown function] in [unknown module]
14:57:32: 0x2eb40d81: [unknown function] in [unknown module]
14:57:32: 0xb7bd5c3b: [unknown function] in [unknown module]
14:57:32: 0xc0ba6cad: [unknown function] in [unknown module]
14:57:32: 0xedb88320: [unknown function] in [unknown module]
14:57:32: 0x9abfb3b6: [unknown function] in [unknown module]
14:57:32: 0x3b6e20c: [unknown function] in [unknown module]
14:57:32: 0x74b1d29a: [unknown function] in [unknown module]
14:57:32: 0xead54739: [unknown function] in [unknown module]
14:57:32: 0x9dd277af: [unknown function] in [unknown module]
14:57:32: 0x4db2615: [unknown function] in [unknown module]
14:57:32: 0x73dc1683: [unknown function] in [unknown module]
14:57:32: 0xe3630b12: [unknown function] in [unknown module]
14:57:32: 0x94643b84: [unknown function] in [unknown module]
14:57:32: 0xd6d6a3e: [unknown function] in [unknown module]
14:57:32: 0x7a6a5aa8: [unknown function] in [unknown module]
14:57:32: 0xe40ecf0b: [unknown function] in [unknown module]
14:57:32: 0x9309ff9d: [unknown function] in [unknown module]
14:57:32: 0xa00ae27: [unknown function] in C:\PROGRA~2\MICROS~1\Office16\2052\GrooveIntlResource.dll
14:57:32: 0x7d079eb1: [unknown function] in [unknown module]
14:57:32: 0xf00f9344: [unknown function] in [unknown module]
14:57:32: 0x8708a3d2: [unknown function] in [unknown module]
14:57:32: 0x1e01f268: [unknown function] in [unknown module]
14:57:32: 0x6906c2fe: [unknown function] in [unknown module]
14:57:32: 0xf762575d: [unknown function] in [unknown module]
14:57:32: 0x806567cb: [unknown function] in [unknown module]
14:57:32: 0x196c3671: [unknown function] in [unknown module]
14:57:32: 0x6e6b06e7: [unknown function] in [unknown module]
14:57:32: 0xfed41b76: [unknown function] in [unknown module]
14:57:32: 0x89d32be0: [unknown function] in [unknown module]
14:57:32: 0x10da7a5a: [unknown function] in [unknown module]
14:57:32: 0x67dd4acc: ZNK9TiXmlNode13ToDeclarationEv in D:\Program Files (x86)\wxFormBuilder\plugins\additional\libadditional.dll
14:57:32: 0xf9b9df6f: [unknown function] in [unknown module]
14:57:32: 0x8ebeeff9: [unknown function] in [unknown module]
14:57:32: 0x17b7be43: [unknown function] in [unknown module]
14:57:32: 0x60b08ed5: [unknown function] in [unknown module]
14:57:32: 0xd6d6a3e8: [unknown function] in [unknown module]
14:57:32: 0xa1d1937e: [unknown function] in [unknown module]
14:57:32: 0x38d8c2c4: [unknown function] in [unknown module]
14:57:32: 0x4fdff252: [unknown function] in [unknown module]
14:57:32: 0xd1bb67f1: [unknown function] in [unknown module]
14:57:32: 0xa6bc5767: [unknown function] in [unknown module]
14:57:32: 0x3fb506dd: [unknown function] in [unknown module]
14:57:32: 0x48b2364b: [unknown function] in [unknown module]
14:57:32: 0xd80d2bda: [unknown function] in [unknown module]
14:57:32: 0xaf0a1b4c: [unknown function] in [unknown module]
14:57:32: 0x36034af6: [unknown function] in [unknown module]
14:57:32: 0x41047a60: [unknown function] in [unknown module]
14:57:32: 0xdf60efc3: [unknown function] in [unknown module]
14:57:32: 0xa867df55: [unknown function] in [unknown module]
14:57:32: 0x316e8eef: [unknown function] in [unknown module]
14:57:32: 0x4669be79: [unknown function] in [unknown module]
14:57:32: 0xcb61b38c: [unknown function] in [unknown module]
14:57:32: 0xbc66831a: [unknown function] in [unknown module]
14:57:32: 0x256fd2a0: [unknown function] in [unknown module]
14:57:32: 0x5268e236: [unknown function] in [unknown module]
14:57:32: 0xcc0c7795: [unknown function] in [unknown module]
14:57:32: 0xbb0b4703: [unknown function] in [unknown module]
14:57:32: 0x220216b9: [unknown function] in [unknown module]
14:57:32: 0x5505262f: [unknown function] in [unknown module]
14:57:32: 0xc5ba3bbe: [unknown function] in [unknown module]
14:57:32: 0xb2bd0b28: [unknown function] in [unknown module]
14:57:32: 0x2bb45a92: [unknown function] in [unknown module]
14:57:32: 0x5cb36a04: [unknown function] in [unknown module]
14:57:32: 0xc2d7ffa7: [unknown function] in [unknown module]
14:57:32: 0xb5d0cf31: [unknown function] in [unknown module]
14:57:32: 0x2cd99e8b: [unknown function] in [unknown module]
14:57:32: 0x5bdeae1d: [unknown function] in [unknown module]
14:57:32: 0x9b64c2b0: [unknown function] in [unknown module]
14:57:32: 0xec63f226: [unknown function] in [unknown module]
14:57:32: 0x756aa39c: LogonUserExExW in C:\Windows\syswow64\SspiCli.dll
14:57:32: 0x26d930a: [unknown function] in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0x9c0906a9: [unknown function] in [unknown module]
14:57:32: 0xeb0e363f: [unknown function] in [unknown module]
14:57:32: 0x72076785: [unknown function] in [unknown module]
14:57:32: 0x5005713: [unknown function] in [unknown module]
14:57:32: 0x95bf4a82: [unknown function] in [unknown module]
14:57:32: 0xe2b87a14: [unknown function] in [unknown module]
14:57:32: 0x7bb12bae: [unknown function] in [unknown module]
14:57:32: 0xcb61b38: [unknown function] in [unknown module]
14:57:32: 0x92d28e9b: [unknown function] in [unknown module]
14:57:32: 0xe5d5be0d: [unknown function] in [unknown module]
14:57:32: 0x7cdcefb7: [unknown function] in [unknown module]
14:57:32: 0xbdbdf21: [unknown function] in [unknown module]
14:57:32: 0x86d3d2d4: [unknown function] in [unknown module]
14:57:32: 0xf1d4e242: [unknown function] in [unknown module]
14:57:32: 0x68ddb3f8: [unknown function] in [unknown module]
14:57:32: 0x1fda836e: [unknown function] in [unknown module]
14:57:32: 0x81be16cd: [unknown function] in [unknown module]
14:57:32: 0xf6b9265b: [unknown function] in [unknown module]
14:57:32: 0x6fb077e1: [unknown function] in [unknown module]
14:57:32: 0x18b74777: [unknown function] in [unknown module]
14:57:32: 0x88085ae6: [unknown function] in [unknown module]
14:57:32: 0xff0f6a70: [unknown function] in [unknown module]
14:57:32: 0x66063bca: [unknown function] in [unknown module]
14:57:32: 0x11010b5c: [unknown function] in [unknown module]
14:57:32: 0x8f659eff: [unknown function] in [unknown module]
14:57:32: 0xf862ae69: [unknown function] in [unknown module]
14:57:32: 0x616bffd3: ZN18wxRibbonXmlHandler12ms_classInfoE in D:\Program Files (x86)\wxFormBuilder\wxmsw30u_ribbon_gcc_custom.dll
14:57:32: 0x166ccf45: [unknown function] in [unknown module]
14:57:32: 0xa00ae278: [unknown function] in [unknown module]
14:57:32: 0xd70dd2ee: [unknown function] in [unknown module]
14:57:32: 0x4e048354: [unknown function] in [unknown module]
14:57:32: 0x3903b3c2: [unknown function] in [unknown module]
14:57:32: 0xa7672661: [unknown function] in [unknown module]
14:57:32: 0xd06016f7: [unknown function] in [unknown module]
14:57:32: 0x4969474d: [unknown function] in [unknown module]
14:57:32: 0x3e6e77db: [unknown function] in [unknown module]
14:57:32: 0xaed16a4a: [unknown function] in [unknown module]
14:57:32: 0xd9d65adc: [unknown function] in [unknown module]
14:57:32: 0x40df0b66: [unknown function] in [unknown module]
14:57:32: 0x37d83bf0: [unknown function] in [unknown module]
14:57:32: 0xa9bcae53: [unknown function] in [unknown module]
14:57:32: 0xdebb9ec5: [unknown function] in [unknown module]
14:57:32: 0x47b2cf7f: [unknown function] in [unknown module]
14:57:32: 0x30b5ffe9: [unknown function] in [unknown module]
14:57:32: 0xbdbdf21c: [unknown function] in [unknown module]
14:57:32: 0xcabac28a: [unknown function] in [unknown module]
14:57:32: 0x53b39330: [unknown function] in [unknown module]
14:57:32: 0x24b4a3a6: [unknown function] in [unknown module]
14:57:32: 0xbad03605: [unknown function] in [unknown module]
14:57:32: 0xcdd70693: [unknown function] in [unknown module]
14:57:32: 0x54de5729: [unknown function] in [unknown module]
14:57:32: 0x23d967bf: [unknown function] in [unknown module]
14:57:32: 0xb3667a2e: [unknown function] in [unknown module]
14:57:32: 0xc4614ab8: [unknown function] in [unknown module]
14:57:32: 0x5d681b02: [unknown function] in [unknown module]
14:57:32: 0x2a6f2b94: [unknown function] in [unknown module]
14:57:32: 0xb40bbe37: [unknown function] in [unknown module]
14:57:32: 0xc30c8ea1: [unknown function] in [unknown module]
14:57:32: 0x5a05df1b: [unknown function] in [unknown module]
14:57:32: 0x2d02ef8d: [unknown function] in [unknown module]
14:57:32: 0x541010: MD5::memset(unsigned char*, unsigned char, unsigned int) in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0x541060: MD5::memset(unsigned char*, unsigned char, unsigned int) in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0x540fb0: MD5::memset(unsigned char*, unsigned char, unsigned int) in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0x540fc0: MD5::memset(unsigned char*, unsigned char, unsigned int) in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0x541070: MD5::memset(unsigned char*, unsigned char, unsigned int) in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0x5410b0: MD5::memset(unsigned char*, unsigned char, unsigned int) in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0x5410d0: MD5::memset(unsigned char*, unsigned char, unsigned int) in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0x5410c0: MD5::memset(unsigned char*, unsigned char, unsigned int) in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0x2e2f2e2e: [unknown function] in [unknown module]
14:57:32: 0x69622f2e: ZN24TiXmlStylesheetReference5ParseEPKcP16TiXmlParsingData13TiXmlEncoding in D:\Program Files (x86)\wxFormBuilder\plugins\common\libcommon.dll
14:57:32: 0x6974756e: [unknown function] in [unknown module]
14:57:32: 0x322d736c: [unknown function] in [unknown module]
14:57:32: 0x2f30332e: [unknown function] in [unknown module]
14:57:32: 0x2f646662: [unknown function] in [unknown module]
14:57:32: 0x74636573: [unknown function] in [unknown module]
14:57:32: 0x2e6e6f69: [unknown function] in [unknown module]
14:57:32: 0x252e0063: [unknown function] in [unknown module]
14:57:32: 0x412a0064: [unknown function] in [unknown module]
14:57:32: 0x2a5342: [unknown function] in [unknown module]
14:57:32: 0x4d4f432a: [unknown function] in [unknown module]
14:57:32: 0x552a002a: [unknown function] in [unknown module]
14:57:32: 0x2a444e: [unknown function] in [unknown module]
14:57:32: 0x454545: PythonTemplateParser::ValueToCode(PropertyType, wxString) in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0x4d4c4e: DesignerWindow::HighlightSelection(wxDC&) in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0x7973614f: [unknown function] in [unknown module]
14:57:32: 0x65540073: [unknown function] in [unknown module]
14:57:32: 0x7865686b: [unknown function] in [unknown module]
14:57:32: 0x65725300: [unknown function] in [unknown module]
14:57:32: 0x65560063: [unknown function] in [unknown module]
14:57:32: 0x6f6c6972: [unknown function] in [unknown module]
14:57:32: 0x68490067: [unknown function] in [unknown module]
14:57:32: 0x53007865: [unknown function] in [unknown module]
14:57:32: 0x4f004d4f: [unknown function] in [unknown module]
14:57:32: 0x4b3953: MenuEditor::MenuEditor(wxWindow*, int) in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0x73726556: [unknown function] in [unknown module]
14:57:32: 0x736f6461: [unknown function] in [unknown module]
14:57:32: 0x44534d00: [unknown function] in [unknown module]
14:57:32: 0x4f00534f: [unknown function] in [unknown module]
14:57:32: 0x786176: [unknown function] in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0x78617645: [unknown function] in [unknown module]
14:57:32: 0x840012: [unknown function] in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0xaaf00000: [unknown function] in [unknown module]
14:57:32: 0xe3520000: [unknown function] in [unknown module]
14:57:32: 0x440000: PHPCodeGenerator::PHPCodeGenerator() in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0x8800ec: [unknown function] in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: 0xa67d0000: [unknown function] in [unknown module]
14:57:32: 0x482f13: XrcLoader::GetProject(ticpp::Document*) in D:\Program Files (x86)\wxFormBuilder\wxFormBuilder.exe
14:57:32: A Fatal Error Occurred. Click Details for a backtrace.

**Comment by jhasse** [comment]
Looks related to #376.

**Comment by jhasse** [comment]
Fixed by #425.
