### ISSUE TITLE
Broken codegen for wxBitmapButton on macOS since wxFB 3.8

### ISSUE THREAD

**Issue by Zenju** [wxFormBuilder/wxFormBuilder#427]
Hi,

This is in reference to https://github.com/wxFormBuilder/wxFormBuilder/pull/417

Since wxFB 3.8, the wxBitmapbuttons are drawn incorrectly on macOS:
![2](https://user-images.githubusercontent.com/7656530/42710622-fb82971c-86e4-11e8-9795-1ea5fddeda05.png)

This should look like:
![1](https://user-images.githubusercontent.com/7656530/42710621-fb619fc6-86e4-11e8-92ab-b62ff1a7e65a.png)

The reason is the lack of the "wxBU_AUTODRAW" style flag on wxBitmapButton. Even though it is (obviously incorrectly) marked as obsolete by wxWidgets themselves, it is still being used on macOS, even in the latest wxWidgets trunk code:
https://github.com/wxWidgets/wxWidgets/blob/0e92eb13dc127fd02e75f40ff83c1cc55ce4bdb4/src/osx/bmpbuttn_osx.cpp#L41

Please bring it back or at least provide a style flag that can be set in wxFB. Currently I don't see a workaround other than to revert back to the previous wxFB release.

Thanks for your awesome work!
Best

**Comment by sodevel** [comment]
What happens when you use a regular `wxButton` with a bitmap and the styles `wxBU_EXACTFIT` and `wxBU_NOTEXT` instead of the `wxBitmapButton`?

**Comment by Zenju** [comment]
wxButton + wxBU_NOTEXT + wxBU_EXACTFIT might be a viable alternative. I'll have to do some more testing, but the first attempt seems to work just like wxBitmapbutton on both macOS and Windows.
I'm however seeing one immediate issue:

The wxFB preview used to look like:
![1](https://user-images.githubusercontent.com/7656530/42715086-9f73f252-86f5-11e8-8112-9d0c2ed87a1d.png)

but with wxBitmapbuttons replaced by "wxButton + wxBU_NOTEXT + wxBU_EXACTFIT" looks like the following which is pretty much unusable at a large project-scope:
![2](https://user-images.githubusercontent.com/7656530/42715085-9f568bae-86f5-11e8-9332-1412902d7164.png)

**Comment by sodevel** [comment]
I don't observe this effect here, looks the same for me in the preview. Are both of your versions really the same, no different loading type, size specifications or the like?

**Comment by Zenju** [comment]
Yes they're the same. I can also reproduce the "invisible button" by adding a new wxButton in wxFB and setting "wxBU_NOTEXT + wxBU_EXACTFIT": it disappears.

**Comment by sodevel** [comment]
If you create a button with these styles and dont set a bitmap it will be invisible.

What happens with your otherwise correct buttons if you manually set the margins to 4?

**Comment by Zenju** [comment]
> What happens with your otherwise correct buttons if you manually set the margins to 4?

On Windows this triggers tons of wxWidgets asserts:
![1](https://user-images.githubusercontent.com/7656530/42725642-70ac66ec-8787-11e8-998e-3e2e03918c70.png)

On macOS it looks find as expected. However I'd like to avoid hard-coding numbers as a workaround in general and let the OS/wxWidgets determine the best native layout.

**Comment by sodevel** [comment]
Your empty buttons and debug assertions must be something else, but the too small buttons are because of the missing style. For me this looks like a defect in wxWidgets so i posted a [ticket](https://trac.wxwidgets.org/ticket/18170) there and will wait for their response.

**Comment by Zenju** [comment]
The reason I'm getting asserts is because I'm *not* setting the bitmaps inside wxFB. Instead I'm manually setting the bitmaps later during program startup by calling SetBitmap(). This is also the reason why there are all these question marks my screenshots above. I don't mind the question marks as I don't need a 100% correct preview, just something to get a rough idea. But hidden buttons are pretty much unworkable. I'm not sure what other design considerations there are for wxFB, but for my scenario it would be great if "no bitmap set" would always be shown with a question mark placeholder.

PS: In case you're wondering why I'm not setting the images in wxFB: I'm loading them during app startup from a ZIP stream.

PPS: Thanks for going the extra mile with opening the ticket!

**Comment by sodevel** [comment]
This explains the differences in your preview between wxBitmapButton and wxButton. The question mark bitmap is returned if the set bitmap cannot be loaded. wxButton only tries to load a bitmap if one is set, without any bitmap it results in an invisible button (and assertions when you try to set the margins). wxBitmapButton currently always tries to load the bitmap (but this won't be the case anymore when #428 gets applied), without a set bitmap this will always fail and return that question mark bitmap.

I know this problem of not wanting to set a value in wxFB from wxStaticText, i don't want dummy values to clutter up the message catalogs, but with all empty values it's hard to see how the layout looks. I don't know what is a good and easy to use (and easy to implement) solution to solve this.

**Comment by Zenju** [comment]
I'm not sure how many other wxWidgets users do this, but I like to dynamically generate button images with different fonts, colors, images, alignments, ect. like: 
![2](https://user-images.githubusercontent.com/7656530/42816311-be0a8fe6-89ca-11e8-93da-3cc20ac94305.PNG)
Therefore dynamic button image loading is a requirement for me.

As regarding a solution, it seems the first idea is to add another entry for bitmap: source, e.g named "Load dynamically" that conveys the intent that there will be an image set later, thous wxFB should show the question-mark placeholder.
![1](https://user-images.githubusercontent.com/7656530/42816368-df285460-89ca-11e8-8986-61d3edc6428f.png)

But thinking more about this - and I'm not sure if it's technically possible for wxFB - it would be great if a placeholder image were always shown in the wxFB preview, even when there is no image set when the generated program runs. This would simplify the wxFB interface by not requiring yet another option like "Load dynamically" and I believe there wouldn't be any drawback:

During design time in wxFB I'm always interested to see all important objects (including placeholders) even when they are hidden during the actual program run. This also includes your example with wxStaticText: I'm litterally using the word "dummy" for optional or static texts I'm dynamically generating, just so that I can see them in wxFB. Later during text extraction I just exclude "dummy" (and a couple of other texts that should not be localized) via a custom solution.

With this change a wxButton should completely superseed a wxBitmapButton and maybe wxBitmapButton should be removed from wxFB, especially if this is aligned with wxWidgets wanting to deprecate wxBitmapButton anyway.

**Comment by jhasse** [comment]
The original issue should be fixed by #428 (if not, please reopen).
