### ISSUE TITLE
Typo for adding enabled property in xrcconv.cpp?

### ISSUE THREAD

**Issue by jhasse** [wxFormBuilder/wxFormBuilder#435]
This looks like a typo to me:
https://github.com/wxFormBuilder/wxFormBuilder/blob/de5b54b6de2d7c4dcbc18256accb4729442c93ea/sdk/plugin_interface/xrcconv.cpp#L415

Shouldn't the second `!` be removed?

**Comment by sodevel** [comment]
No, this is used to filter out the property if it matches its default value (== true). You can see the effect in wxFB if you switch to the XRC tab in the editor pane and compare with the hidden property, it has the opposite default value.

**Comment by jhasse** [comment]
I see, thank you :)
