### ISSUE TITLE
Add FloatSpin

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#45]
There's missing the ability to add the spin control for floating-point values: wxSpinCtrlDouble. There's only one for integers.

Reported by: human-man

**Comment by eldarkg** [comment]
@jhasse Can you apply [this patch? ](https://github.com/marekr/wxFormBuilder/commit/a4aade70723fe0dd7eeb47737955bf11d1c7bd15)

**Comment by jhasse** [comment]
Done: https://github.com/wxFormBuilder/wxFormBuilder/commit/47eac3915d32b5f11d025dd6446aae616fc782c7

**Comment by eldarkg** [comment]
@jhasse Thank you
