### ISSUE TITLE
TimePickerCtrl wrong coded in python

### ISSUE THREAD

**Issue by XaniloM** [wxFormBuilder/wxFormBuilder#450]
Hi,

I'm using wxFormBuilder 3.8 and when the program created the code for my form, I found a little bug in the file.

The TimePicker Control is coded as wx.TimePickerCtrl, however it must be wx.adv.TimePickerCtrl.

Greetings,

XaniloM

**Comment by 256481788jianghao** [comment]
this problem is still there， why？

**Comment by jes1510** [comment]
It also passes wx.TP_DEFAULT , which is no longer supported

**Comment by AexisY** [comment]
Problem is still there with wxfrombuilder 3.9.0 and wxpython 4.1.1.
There is no binary for windows in version 3.9.1 in order to check with new version.
Is there a way to go arround this?
