### ISSUE TITLE
Component palette filter

### ISSUE THREAD

**Issue by specing** [wxFormBuilder/wxFormBuilder#457]
Could the component panel be tiled similar to how QtCreator does it? That is, a vertical list where the icon is on the left and the component name on the right, with a TextCtrl at the bottom (or on top) where we could apply a whitelist filter to the list.

**Comment by sodevel** [comment]
This sounds like 05d9e15eeee1b099b14ee3bd472ab97d99c15ae8 and should be resolved by that feature.
