### ISSUE TITLE
 error: ‘wxFALLTHROUGH’ was not declared in this scope

### ISSUE THREAD

**Issue by boern** [wxFormBuilder/wxFormBuilder#460]
My Env:
    Ubuntu 16.04
     Gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
     GNU Make 4.1
Build:

git clone --recursive --depth=1 https://github.com/wxFormBuilder/wxFormBuilder
cd wxFormBuilder
./create_build_files4.sh
cd build/3.0/gmake
make config=release

==== Building TiCPP (release) ====
==== Building plugin-interface (release) ====
==== Building additional-components-plugin (release) ====
==== Building common-components-plugin (release) ====
==== Building containers-components-plugin (release) ====
==== Building forms-components-plugin (release) ====
==== Building layout-components-plugin (release) ====
==== Building wxFormBuilder (release) ====
typeconv.cpp
../../../src/utils/typeconv.cpp: In function ‘void TypeConv::ParseBitmapWithResource(const wxString&, wxString*, wxString*, wxSize*)’:
../../../src/utils/typeconv.cpp:529:5: error: ‘wxFALLTHROUGH’ was not declared in this scope
     wxFALLTHROUGH;
     ^
wxFormBuilder.make:181: recipe for target 'obj/Release/wxFormBuilder/typeconv.o' failed
make[1]: *** [obj/Release/wxFormBuilder/typeconv.o] Error 1
Makefile:44: recipe for target 'wxFormBuilder' failed
make: *** [wxFormBuilder] Error 2
-------------------------------------------------------------------------------------
How to fix the issue？ thx！

**Comment by jhasse** [comment]
You'll need at least wxWidgets 3.0.3 to build wxFormBuilder from source, sorry.
