### ISSUE TITLE
git:98e1366 A ton of errors upgrading a git:359d3a3 .fbp project file to latest version

### ISSUE THREAD

**Issue by specing** [wxFormBuilder/wxFormBuilder#466]
"The property named "validator_type" of class "wxSlider" is not supported by this version of wxFormBuilder. If your project file was just ...

Details:
+ over 9000 errors of the above form

**Comment by sodevel** [comment]
Like your truncated error message says in the truncated part, you can ignore this error.

I doubt your project file was made by 359d3a3, there should be no changes to the project file format from there to current master that cause these messages. I do remember that converting from much older file versions can cause these messages however.

If you would like to track down this further it would be quite helpful if you can upload your original project file that causes these messages on upgrade.

**Comment by specing** [comment]
I did not truncate that message, wxFB did. Ignoring this error causes the widget tree to be filled with "unknown component = wxwidgets logo?", being unusable and having no components in the component selector.

There were changes and I was asked to upgrade the project file, which I did => these errors.

the fpb before upgrade: https://paste.pound-python.org/show/mDX1SdStgZ8mMGKYUBGU/

**Comment by sodevel** [comment]
I just converted your file and i didn't get a single error, which makes sense because it is only one version behind the current format.

I have the impression your wxFB installation is broken, the mentioned property in the message is a valid one. Also your unknown components are a sign that wxFB misses its XML definition files. Make sure that your wxFB installation contains all files from the output folder of the source tree.

**Comment by specing** [comment]
Perhaps the new build instructions using mason are a bit ... inadequate?

**Comment by jhasse** [comment]
I've also just converted your project with no errors using wxFormBuilder built with Meson on Linux. If a xml definition file is missing, you should get an error message at start-up.

**Comment by jhasse** [comment]
Please reopen if you can reproduce this.

**Comment by specing** [comment]
When the following is run in the source checkout:
```
meson /tmp/wxfb_build --prefix /tmp/wxfb_install
ninja -C /tmp/wxfb_build/ install
```
it produces a broken installation for me:
```
/tmp/wxfb_install/bin/wxformbuilder                                                       
15:36:56: Debug: palette.cpp@123 Create: [Palette] Pages 3                                                             
15:36:56: Debug: palette.cpp@74 PopulateToolbar: Missing Component for Class "wxTreeCtrl" of Package "Data".       
15:36:56: Debug: palette.cpp@74 PopulateToolbar: Missing Component for Class "wxGrid" of Package "Data".       
15:36:56: Debug: palette.cpp@74 PopulateToolbar: Missing Component for Class "wxCheckListBox" of Package "Data".
...
```

I will switch back to using the old instructions.

**Comment by specing** [comment]
Or not. The problem was that the install produces libraries in $PREFIX/lib64/wxformbuilder/*, while wxformbuilder attempts to load them from $PREFIX/lib/wxformbuilder/*. Adding the missing symlink makes everything work again.

**Comment by mnba** [comment]
I second that, in Linux 64bit wxFormBuilder can't find its own library files, 
It is needed to manually add such symlink to force wxFB find the needed libraries: 
Symlink at wxFormBuilder/_install/lib/wxformbuilder 
to point to: wxFormBuilder/_install/lib/x86_64-linux-gnu/wxformbuilder

**Comment by egilkv** [comment]
This issue persist. Running the latest version from the git source on my 64 bit Linux is broken, and yields a runtime that is missing pretty much everything. Extremely confusing for a newbie. Adding the symlink removes the symptom, but this should definitely be fixed properly.  
> cd wxFormBuilder/_install/lib
> ln -s x86_64-linux-gnu/wxformbuilder .
> cd ../..
