### ISSUE TITLE
Excessive verbosity in .fpb files, causing needless inflation in repository size.

### ISSUE THREAD

**Issue by specing** [wxFormBuilder/wxFormBuilder#467]
For example this line: ```                                <event name="OnTextEnter"></event>``` .. why include it if there is no event attached? Since a reasonable default is for there to be no handler, exclude such events from the XML.

The same also applies to other xml tags/components/items/whatever.

PS: can you stop with the excessive merge commits? They are cluttering your project's git history and making it difficult to see what the actual changes were. Use `git am` or something similar, git on its own already distinguishes between author and commiter in every commit.

**Comment by jhasse** [comment]
> making it difficult to see what the actual changes were.

Why? You can still see the commits of the branch that was merged.

**Comment by acolomb** [comment]
@specing, still off topic: Git can skip merge commits when printing history. Just add the `--no-merges` option.  I do like the merge commits in the history because they record links to relevant discussion, which is equally important as the code history.

**Comment by specing** [comment]
29 elements on a wxDialog results in a 143 KiB .fbp. This is unacceptable and any reasonable dev would kill me if I tried to commit it to repo! That would be >15MB just for formbuilder files if I moved all GUI code to it. And most of those project file would be 95% defaults.

**Comment by jhasse** [comment]
Those 143 kb will be a lot less compressed though, so you can't compare it with most binary files.

Still: We get the point and this is a valid issue.

**Comment by specing** [comment]
143 KB -> 99 KB  (4.2KB gzipped)

**Comment by jhasse** [comment]
Closing as fixed, as fixing this for properties also is out of scope for now.
