### ISSUE TITLE
v3.8.1, linux build error, ticpp missing

### ISSUE THREAD

**Issue by dallenwilson** [wxFormBuilder/wxFormBuilder#470]
Following the build instructions in the bundled README.md:
`git clone --recursive --depth=1 `https://github.com/wxFormBuilder/wxFormBuilder`
`cd wxFormBuilder`
`./create_build_files4.sh`
`cd build/3.0/gmake make config=release`

I skipped step one, as I was working from the release tarball. Step four failed with:
`../../../sdk/plugin_interface/xrcconv.cpp:31:10: fatal error: ticpp.h: No such file or directory`

I can't find a reference to ticpp being a dependency anywhere in README.md (or anywhere else, for that matter). Was it intended to be bundled in the release tarball? Is there a list of build/runtime dependencies somewhere that I haven't found yet, beyond what's listed in README.md (wxGTK3, libboost)?

In the meantime, I'll install ticpp from the repository and continue.

**Comment by jhasse** [comment]
ticpp is a submodule and GitHub doesn't include them in the tarball.
