### ISSUE TITLE
flatpak package running error

### ISSUE THREAD

**Issue by kurjakrichard** [wxFormBuilder/wxFormBuilder#471]
I have installed wxFormBuilder from flatpak package. When I try to install I get this error message:
[sire@sirelt Letöltések]$ flatpak run org.wxformbuilder.wxFormBuilder/x86_64/master
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"

(wxformbuilder:3): Gdk-ERROR **: The program 'wxformbuilder' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAccess (attempt to access private resource denied)'.
  (Details: serial 454 error_code 10 request_code 130 (MIT-SHM) minor_code 1)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
I installed another program (Audacity). It works.

**Comment by jhasse** [comment]
Can you give me the exact Linux distribution you're using?

What's the output when you run Audacity?

**Comment by balzamon** [comment]
I use Manjaro. 
Audacity output:
flatpak run org.audacityteam.Audacity/x86_64/stable 
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
00:06:32: Debug: Failed to connect to session manager: Could not open network socket
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5033:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM sysdefault
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4554:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5033:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2501:(snd_pcm_open_noupdate) Unknown PCM sysdefault

**Comment by jhasse** [comment]
I've downloaded Manjaro and installed it in a VM. I've installed flatpak with `pacman -S flatpak` and then installed wxFormBuilder 3.8.1 via `flatpak install ./wxformbuilder.flatpak`. It ran fine after that (the `Failed to load module "canberra-gtk-module"` seem to be normal), so I need more info on how to reproduce your issue, sorry.

**Comment by jhasse** [comment]
Okay after upgrading the system via `pacman -Syu` I get the same error as you. I'll try to check what flatpak versions were involved and create an upstream bug report.

**Comment by balzamon** [comment]
OK. Thank you! Somehow I could run it only once. After restart I could not again!

**Comment by jhasse** [comment]
Can you try again with the v3.9.0 flatpak?

**Comment by jhasse** [comment]
Can you try if it works with `flatpak run --share=ipc org.wxformbuilder.wxFormBuilder`? (suggested in the upstream bug report)

**Comment by davidea72** [comment]
same problem here , debian 9 with kde , yesterday ok with kernel 4.9.0-8 , now this error with kernel 4.19.0-0 (the whole system is the same, i've upgraded the kernel only) ....
same solution whit --share=ipc
