### ISSUE TITLE
Version conflict problem

### ISSUE THREAD

**Issue by balzamon** [wxFormBuilder/wxFormBuilder#472]
I used to 3.6 version on Windows and Linux without any problem. I use common folder.
I update to 3.8 use on Windows on the latest github release and I installed on Linux from AUR. Flatpak package does not run.

When I tried to open in Windows I get this error message: 
This project file is newer than this version of wxFormbuilder. It cannot be opened. 

The version is 3.8.1 in both system. 

![kepkivagas](https://user-images.githubusercontent.com/43314480/45596058-10181400-b9b6-11e8-87fe-ff9ad2f3e437.PNG)

**Comment by sodevel** [comment]
This looks like your project file got upgraded to the latest version but you open it with your old wxFB version.

Make sure that you use the new wxFB version, if the problem persists it would help if you can upload that project file.

**Comment by balzamon** [comment]
I am sure I open the latest version of the program.
![kepkivagas](https://user-images.githubusercontent.com/43314480/45599823-d0bbe880-b9f2-11e8-8694-f3735adf48eb.PNG)
This is the projekt file:
[MainFrame.zip](https://github.com/wxFormBuilder/wxFormBuilder/files/2386894/MainFrame.zip)

**Comment by balzamon** [comment]
I create a new file in Windows. I got this message when I open it in Linux:
![kepernyokep_2018-09-16_21-06-31](https://user-images.githubusercontent.com/43314480/45599931-7cb20380-b9f4-11e8-9a55-7295426501d4.png)

**Comment by jhasse** [comment]
It looks to me that you're compiling the Git master from source on Linux, but using the 3.8.1 release on Windows, correct?

**Comment by balzamon** [comment]
No, I installed on Linux from AUR.

**Comment by jhasse** [comment]
This one? https://aur.archlinux.org/packages/wxformbuilder-git/

It seems to build the Git master branch (I don't know that much about AUR though) and is therefore indeed a newer version than 3.8.1.

We should should name development versions differently (e.g. 3.8.1-dev). But the version conflict error is intended behavior.

**Comment by balzamon** [comment]
Any solution? Converter to 3.8.1? As I understand the development version is compatible only itself!

**Comment by jhasse** [comment]
In your fbp file decrease the `minor` attribute of the `FileVersion` tag.

**Comment by balzamon** [comment]
OK. Thank you!
