### ISSUE TITLE
Aborting with assert when inserting wxRichText component on Linux 

### ISSUE THREAD

**Issue by mnba** [wxFormBuilder/wxFormBuilder#474]
Linux version: Minux Mint 17.3 ~~ Ubuntu 14.04
wxFormBuilder, both master branch and v3.8.1 Release version, abnormally exits when inserting wxRichText component ( into the sizer under the panel  etc).

The tail of tracelog in console: 

13:04:20: Debug: mainframe.cpp@710 OnObjectSelected: MainFrame::OnObjectSelected
13:04:48: Debug: appdata.cpp@757 CreateObject: [ApplicationData::CreateObject] New wxRichTextCtrl
13:04:48: Debug: objectbase.cpp@249 ObjectBase: new ObjectBase
13:04:48: Debug: objectbase.cpp@249 ObjectBase: new ObjectBase
13:04:48: Debug: appdata.cpp@2977 NotifyEvent: event: wxEVT_FB_OBJECT_CREATED
../src/richtext/richtextbuffer.cpp(4965): assert "partialExtents.GetCount() >= (size_t) range.GetLength()" failed in wxRichTextGetRangeWidth().
Trace/breakpoint trap

Do I need to provide more information?

**Comment by 60vic** [comment]
Linux debe6500 4.19.0-4-686-pae #1 SMP Debian 4.19.28-2 (2019-03-15) i686 GNU/Linux
wxformbuilder v 3.9.0 unicode
same problem
crash after insert wxRichText

../src/richtext/richtextbuffer.cpp(4729): assert "partialExtents.GetCount() >= (size_t) range.GetLength()" failed in wxRichTextGetRangeWidth().

**Comment by Bob-YsPan** [comment]
Same problem...

Arch Linux version build by AUR
[https://aur.archlinux.org/packages/wxformbuilder/](https://aur.archlinux.org/packages/wxformbuilder/)

Trail of the log...
17:30:17: Debug: appdata.cpp@757 CreateObject: [ApplicationData::CreateObject] New wxRichTextCtrl
17:30:17: Debug: objectbase.cpp@249 ObjectBase: new ObjectBase
17:30:17: Debug: objectbase.cpp@249 ObjectBase: new ObjectBase
17:30:17: Debug: appdata.cpp@2977 NotifyEvent: event: wxEVT_FB_OBJECT_CREATED
./src/richtext/richtextbuffer.cpp(4729): assert "partialExtents.GetCount() >= (size_t) range.GetLength()" failed in wxRichTextGetRangeWidth().
[1]    6381 trace trap (core dumped)  wxformbuilder

**Comment by refaelsh** [comment]
I have the same problem exactly. I am also using Arch AUR package as @Bob-YsPan.

**Comment by refaelsh** [comment]
*bump*

**Comment by sodevel** [comment]
Some of these problems are caused by wxWidgets 3.0.x builds, they don't happen with recent wxWidgets 3.1.x builds. I checked on my Ubuntu 20.04 machine that uses wxWidgets 3.0.4 and cannot reproduce the issue.

I don't know how Arch works, if it supports Flatpak you can try the Flatpak release. Otherwise i suggest you build a recent wxFB release yourself on your platform, if available use a wxWidgets 3.1.x release.

**Comment by rsheink** [comment]
> Some of these problems are caused by wxWidgets 3.0.x builds, they don't happen with recent wxWidgets 3.1.x builds. I checked on my Ubuntu 20.04 machine that uses wxWidgets 3.0.4 and cannot reproduce the issue.
> 
> I don't know how Arch works, if it supports Flatpak you can try the Flatpak release. Otherwise i suggest you build a recent wxFB release yourself on your platform, if available use a wxWidgets 3.1.x release.

I will try your suggestion tonight.

**Comment by refaelsh** [comment]
> Some of these problems are caused by wxWidgets 3.0.x builds, they don't happen with recent wxWidgets 3.1.x builds. I checked on my Ubuntu 20.04 machine that uses wxWidgets 3.0.4 and cannot reproduce the issue.
> 
> I don't know how Arch works, if it supports Flatpak you can try the Flatpak release. Otherwise i suggest you build a recent wxFB release yourself on your platform, if available use a wxWidgets 3.1.x release.

It is reproducible for me in Arch with 3.0.5. I will update to 3.1.x and try again. Thank you for the suggestion.
