### ISSUE TITLE
Add Auto Generated Events Functions

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#48]
It would be grate to have auto generation of event handling functions similar to wxWidgets and wxDevCpp and Embarcadero project. Say Have an extra tab for each component with an events handler. I hope that you monitor the wxDevCpp and wxSmith projects and understand the feature request.

Reported by: *anonymous

**Comment by jhasse** [comment]
Please reopen if you don't think that the current implementation is enough.
