### ISSUE TITLE
Flatpak on Debian Stretch XFCE, font white color and customization

### ISSUE THREAD

**Issue by damufo** [wxFormBuilder/wxFormBuilder#480]
https://github.com/flatpak/flatpak.github.io/issues/300

**Comment by jhasse** [comment]
Thanks for the report. This seems to be a bug in wxWidgets 3.1.0.

**Comment by jhasse** [comment]
Please check if this issue is really fixed with the 3.9.0 flatpak and reopen if not.

**Comment by damufo** [comment]
Hello:
Checked!
Now it looks correctly!
Very thanks!
