### ISSUE TITLE
add flatpak instructions to readme

### ISSUE THREAD

**Issue by graph** [wxFormBuilder/wxFormBuilder#481]
It needs this

```
flatpak install flathub org.freedesktop.Platform//18.08
```

I'm new to flatpak, it took me a while to figure out how to run wxFormBuilder on ubuntu using the flatpak release build.

Thank you.

**Comment by jhasse** [comment]
Thanks! I've added it to the release notes instead.

Ultimately I think this is something Flatpak should figure out for itself. I will look for an upstream bug report.
