### ISSUE TITLE
deprecated AddLabelTool used instead of AddTool

### ISSUE THREAD

**Issue by elitur** [wxFormBuilder/wxFormBuilder#485]
System: Windows 10
Program: wxFormBuilder 3.9
Language: Python 3.7
wxPython version: 4.0.3
Widget: wxToolBar
Action: Adding tool

To add tool, "wxFormBuilder" use "AddLabelTool". This cause the Deprecation Warning: "
wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead."

**Comment by joehood** [comment]
This also applies to Python 2.7. A simple replacement of AddTool for instances of AddLabelTool seems to work. If that's all it takes, the fix in FormBuilder should be trivial

**Comment by sodevel** [comment]
Should already be fixed by #585, can you verify that?
