### ISSUE TITLE
Building on Mac OS 10.12 failure - additional.cpp unknown type wxMediaCtrl

### ISSUE THREAD

**Issue by programmingkidx** [wxFormBuilder/wxFormBuilder#486]
I am trying to build wxFormBuilder on Mac OS 10.12. I followed the Mac OS X directions from here: 
https://github.com/wxFormBuilder/wxFormBuilder.

When I do try building wxFormBuilder I see this error message: 

```
additional.cpp
../../../plugins/additional/additional.cpp:1360:3: error: unknown type name
      'wxMediaCtrl'
                wxMediaCtrl* mc = new wxMediaCtrl((wxWindow *)parent, wx...
                ^
../../../plugins/additional/additional.cpp:1360:25: error: unknown type name
      'wxMediaCtrl'
                wxMediaCtrl* mc = new wxMediaCtrl((wxWindow *)parent, wx...
                                      ^
../../../plugins/additional/additional.cpp:1373:100: error: use of undeclared
      identifier 'wxMEDIACTRLPLAYERCONTROLS_STEP'
  ..._("player_controls") ) == wxT("STEP") )    mc->ShowPlayerControls(wxMEDIAC...
                                                                     ^
../../../plugins/additional/additional.cpp:1374:102: error: use of undeclared
      identifier 'wxMEDIACTRLPLAYERCONTROLS_VOLUME'
  ...) == wxT("VOLUME") )       mc->ShowPlayerControls(wxMEDIACTRLPLAYERCONT...
                                                        ^
../../../plugins/additional/additional.cpp:1375:103: error: use of undeclared
      identifier 'wxMEDIACTRLPLAYERCONTROLS_DEFAULT'
  ...) == wxT("DEFAULT") )      mc->ShowPlayerControls(wxMEDIACTRLPLAYERCONT...
                                                        ^
../../../plugins/additional/additional.cpp:1376:100: error: use of undeclared
      identifier 'wxMEDIACTRLPLAYERCONTROLS_NONE'
  ..._("player_controls") ) == wxT("NONE") )    mc->ShowPlayerControls(wxMEDIAC...
                                                                     ^
../../../plugins/additional/additional.cpp:1388:55: error: use of undeclared
      identifier 'wxMEDIACTRLPLAYERCONTROLS_STEP'
                if(!obj->IsNull(_("style"))) mc->ShowPlayerControls(wxME...
                                                                    ^
../../../plugins/additional/additional.cpp:1397:37: error: use of undeclared
      identifier 'wxMediaCtrl'
                auto* window = wxDynamicCast(obj, wxMediaCtrl);
                                                  ^
../../../plugins/additional/additional.cpp:1397:18: error: expected expression
                auto* window = wxDynamicCast(obj, wxMediaCtrl);
                               ^
/usr/local/include/wx-3.0/wx/object.h:145:18: note: expanded from macro
      'wxDynamicCast'
    ((className *) wxCheckDynamicCast( \
                 ^
9 errors generated.
make[1]: *** [obj/Release/additional-components-plugin/additional.o] Error 1
make: *** [additional-components-plugin] Error 2

```

I think the solution to this problem may be to disable the building of the additional plugins.

**Comment by programmingkidx** [comment]
I think I am using version 3.9.0.

**Comment by jhasse** [comment]
Unfortunately the official `wxmac` package from Homebrew doesn't work anymore, the instructions in the README are outdated.  After you removed the existing package (`brew uninstall`? I don't use macOS), try this:

```
brew tap cdalvaro/tap
brew install cdalvaro/tap/wxmac
```

 https://github.com/wxFormBuilder/wxFormBuilder/blob/1ea413b964d1ce42b1291e3ff93c8cd4a17f1079/.travis.yml#L23

Hope this helps.

**Comment by programmingkidx** [comment]
The last command is what I'm having the most difficulties with. When it runs I see this error message: ==> Installing wxmac from cdalvaro/tap
Error: wxmac 3.0.4_1 is already installed
To upgrade to 3.1.2, run `brew upgrade wxmac`

When I run 'brew upgrade wxmac' I see: 
Error: wxmac 3.0.4_1 already installed

Thank you for the help.

**Comment by jhasse** [comment]
Did you brew uninstall wxmac?

**Comment by programmingkidx** [comment]
Using 'brew uninstall wxmac' I was then able to update wxmac to version 3.1.2.

When I tried building wxFormBuilder I ran into problems at this step: cd build/3.0/gmake

The first problem is there is no 3.0 folder. I would change this text be version neutral. 
Like this: cd build/<version number>/gmake

When I changed the number to 3.1 I was able to start building. Building stopped at this error: 

error: install_name_tool: changing install names or rpaths can't be redone for: /Users/john/desktop/wxformbuilder/output/wxFormBuilder.app/Contents/PlugIns/libcommon.dylib (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)


Error : An error occured while trying to fix depencies of /Users/john/desktop/wxformbuilder/output/wxFormBuilder.app/Contents/PlugIns/libcommon.dylib
~/desktop/wxformbuilder/output/wxFormBuilder.app/Contents/libs ~/desktop/wxformbuilder/build/3.1/gmake

**Comment by jhasse** [comment]
> Using 'brew uninstall wxmac' I was then able to update wxmac to version 3.1.2.

It should uninstall, remove wxmac instead.

**Comment by programmingkidx** [comment]
Wxmac does work. The issue is with wxFormBuilder. 

After opening the file wxFormBuilder/install/macosx/postbuild.sh and adding this to the install_name_tool line "-headerpad_max_install_names", I was able to build wxFormBuilder successfully.

This is what the line looks like now:
	`install_name_tool -headerpad_max_install_names -id "$APPCONTENTS/PlugIns/$base" "$APPCONTENTS/PlugIns/$base"`

**Comment by programmingkidx** [comment]
This issue is now solved. Note: none of the changes required to make wxFormBuilder on Mac OS X have been submitted yet. If you are someone who can do this, please do so.

Thank you.
