### ISSUE TITLE
Error in python generated code: BitmapComboBox has moved from wx.combo to wx.adv 

### ISSUE THREAD

**Issue by jmoraleda** [wxFormBuilder/wxFormBuilder#492]
Per the documentation, in wxpython 4,`BitmapComboBox` has moved from `wx.combo` to `wx.adv` (https://wxpython.org/Phoenix/docs/html/wx.adv.BitmapComboBox.html#wx-adv-bitmapcombobox). There is no longer a `wx.combo` module so the generated code which imports  `wx.combo` does not work.

**Comment by jhasse** [comment]
Fixed by your PR.
