### ISSUE TITLE
Request for version that can be installed in mint 19 (ubuntu bionic)

### ISSUE THREAD

**Issue by Alchemist45** [wxFormBuilder/wxFormBuilder#502]
I use wxformbuilder quite a bit.  It works fine on Windows machines, but I cannot get a version for Linux Mint 19.x, which is based on Ubuntu bionic Beaver.  Existing ppa's only go through xenial.  Can anyone help?

Thanks.

Alchemist45

**Comment by jhasse** [comment]
Have you tried using the Flatpak from https://github.com/wxFormBuilder/wxFormBuilder/releases ?

**Comment by Alchemist45** [comment]
I am not familiar with Flatpak.  Can you tell me how to use it?

Thanks,

Scott

-----Original Message-----

**Comment by jhasse** [comment]
I don't know Linux Mint, but you might be able to just double-click the file to install it with a GUI.

If not, run the following in a terminal:
```
flatpak install flathub org.freedesktop.Platform//18.08
flatpak install ./wxformbuilder.flatpak
```
