### ISSUE TITLE
Missing Component for Class "wxMediaCtrl"

### ISSUE THREAD

**Issue by DrEdHepler** [wxFormBuilder/wxFormBuilder#506]
I just built wxFormBuilder version 3.9.0 using wxWidgets-3.1.2

The executable loads OK, but a message appears in the log:
Debug: palette.cpp@74 PopulateToolbar: Missing Component for Class "wxMediaCtrl" of Package "Additional".
Looking at the tab for "Additional", there is no widget for wxMediaCtrl, although I see an icon file for it in /usr/share/wxformbuilder/plugins/additional/icons
Is there a fix for this?
Thanks!

**Comment by sodevel** [comment]
Did you build this on OSX? Is your wxWidgets built with wxMediaCtrl enabled? Did you disable the media-control support of wxFB?

**Comment by DrEdHepler** [comment]
The build was performed on CentOS 7
wxWidgets-3.1.2 was built using:
../configure --with-gtk3 -- prefix=/usr --with-opengl --enable-mediactrl

wxFormBuilder-3.9.0 was built using the recommended:
meson _build --prefix /usr
ninja -C _build install

I didn't see any options to disable the media control support in wxFB

As an aside:  Any thought in providing a "constraint-based" widget placement tool (similar to the one provided in Android Studio)?

**Comment by sodevel** [comment]
When using the PreMake path you can disable mediactrl support which was necessary for earlier versions on OSX. It looks like the Meson path doesn't enable mediactrl so its always missing, maybe @jhasse can take a look at that.

I don't know Android Studio, is its "constraint-based" layout what wxLayoutConstraints do? But even if it is, i don't think it can be integrated (easily), the whole wxFB architecture is strongly sizer based.
