### ISSUE TITLE
Value "c++17"

### ISSUE THREAD

**Issue by Xilmirius** [wxFormBuilder/wxFormBuilder#510]
When I try to build it with meson, in the first line of code: 
`meson _build --prefix $PWD/_install`
I got a erro that says: 

> Meson encountered an error in file meson.build, line 1, column 0:
> Value "c++17" for combo option "cpp_std" is not one of the choices. Possible choices are: "none", "c++03", "c++11", "c++14", "c++1z", "gnu++03", "gnu++11", "gnu++14", "gnu++1z".

Any help??

**Comment by jhasse** [comment]
Your Meson version is too old. Try upgrading it (depending on how you installed it).

**Comment by Xilmirius** [comment]
> Your Meson version is too old. Try upgrading it (depending on how you installed it).

Im using the 0.5 version, installed last day
