### ISSUE TITLE
Some buttons are missplaced in wxStdDialogButtonSizer

### ISSUE THREAD

**Issue by Micheus** [wxFormBuilder/wxFormBuilder#515]
In a Dialog, add a wxBoxSizer and add a wxStdDialogButtonSizer to it.
Then, in the Properties, check the boxes for the buttons: Save, Apply, No, Cancel and Help.
Now, if we check the box for any of: Yes, OK or ContextHelp the button is placed on the top/left side of the dialog (and they overlap each other):
![wxStdDialogButtonSizer-issue](https://user-images.githubusercontent.com/365243/56465682-f241e000-63d8-11e9-9335-246c99f0a029.png)

The placement works fine if we use sets like: [OK, Cancel], [Yes, No], [Apply, OK, Cancel], ...
But, for some other combinations not.

**Comment by sodevel** [comment]
It's not a bug, it's by design. This sizer is not designed to put in every possible button, it only supports one button per "button class". The wxWidgets source code reveals in the file `wx/sizer.h` the following:

```
    wxButton *m_buttonAffirmative;  // wxID_OK, wxID_YES, wxID_SAVE go here
    wxButton *m_buttonApply;        // wxID_APPLY
    wxButton *m_buttonNegative;     // wxID_NO
    wxButton *m_buttonCancel;       // wxID_CANCEL, wxID_CLOSE
    wxButton *m_buttonHelp;         // wxID_HELP, wxID_CONTEXT_HELP
```

This matches your observations pretty well :smile:

**Comment by Micheus** [comment]
Thanks for checking.
I'm working on the code generation for Erlang and was just putting controls on forms to debug it, but I never used this control. So, I didn't knew it would to work that way.
