### ISSUE TITLE
XRC preview window error when centering wxSpinCtrl text.

### ISSUE THREAD

**Issue by astrilchuk** [wxFormBuilder/wxFormBuilder#517]
System: macOS 10.13.4
Program: wxFormBuilder 3.9 (Downloaded)
Language: Python 3.7
wxPython version: 4.0.4
Widget: wxSpinCtrl

If I enable wxALIGN_CENTER_HORIZONTAL style attribute for a wxSpinCtrl, the designer correctly shows the current value as centered.

When I use the XRC preview window (Menu - View > XRC Window F5), an error appears: "XRC error: 168: unknown style flag "wxALIGN_CENTER_HORIZONTAL".

**Comment by astrilchuk** [comment]
I've realized this is most likely a bug with wxWidgets and not wxFormBuilder.  I will try to submit an issue on their bug tracker (Trac isn't sending me a confirmation email).

**Comment by Kvaz1r** [comment]
> I will try to submit an issue on their bug tracker (Trac isn't sending me a confirmation email).

Yes, it's a known problem. You can reach maintainers via https://groups.google.com/forum/#!forum/wx-users
