### ISSUE TITLE
Problem with Travis.

### ISSUE THREAD

**Issue by JacoboSpain** [wxFormBuilder/wxFormBuilder#522]
Hi 

I sent a pull request with some simple modifications, solving a wxcollapsePanel bug in Python and added support for StyledEditorCTrl for Python.
But it was rejected by the following error in Travis:

The job exceeded the maximum time limit for jobs, and has been terminated.
 [https://travis-ci.org/wxFormBuilder/wxFormBuilder/builds/543457710?utm_source=github_status&utm_medium=notification](https://travis-ci.org/wxFormBuilder/wxFormBuilder/builds/543457710?utm_source=github_status&utm_medium=notification )
why ??

I am new to github.

**Comment by sodevel** [comment]
It seems that all recent PR's build wxWidgets from source on linux which simply takes too long so the time limit is reached and travis kills the jobs.

I haven't setup this and have not really an idea how this works, the config mentions some kind of cache that previous PR builds could use but now can't anymore, hopefully @jhasse can take a look at that.

**Comment by jhasse** [comment]
Yes, Travis CI has to build wxWidgets from source on Linux (there are no pre-built Flatpak SDKs for wxWidgets like there are for Qt or Gtk). Previously this took about 15 minutes, see https://travis-ci.org/wxFormBuilder/wxFormBuilder/jobs/298049726 for example. Not sure why it takes so long now?

**Comment by jhasse** [comment]
Seems to have fixed itself :)

Hopefully Travis' runner performance will only get better.
