### ISSUE TITLE
Run Error on ubuntu 18.04

### ISSUE THREAD

**Issue by oxarbitrage** [wxFormBuilder/wxFormBuilder#524]
Afer installation, on my Linux Mint 19.1(Ubuntu 18.04 based) there is a runtime error with the libs:

Could not set current working directory (error 2: No such file or directory)

This is similar to https://github.com/wxFormBuilder/wxFormBuilder/issues/285 but a bit different.

Libraries were built at:
_install/lib/x86_64-linux-gnu/wxformbuilder

While the program expect them to be just at:
_install/lib/wxformbuilder

**Comment by st3255** [comment]
Same problem here, also not loading any widget content etc. Manually copying the files to the expected path (from /x86_64-linux-gnu/wxformbuilder to /wxformbuilder) solves this.

**Comment by elig0n** [comment]
For anyone else interested, after `meson _build --prefix $PWD/_install`, from the repo's root run:
`cp -r _install/lib/x86_64-linux-gnu/wxformbuilder/ _install/lib/` and then run as usual i.e. `ninja -C _build install`

**Comment by jmoraleda** [comment]
The instructions that worked for me to work around this issue were, from the `git` checkout directory:
* Configure and build the usual way:
`meson _build --prefix $PWD/_install`
`ninja -C _build install`
* Add a symbolic link to the location where the executable is expecting the libraries
`ln -s x86_64-linux-gnu/wxformbuilder/ _install/lib`
* Run the usual way
`./_install/bin/wxformbuilder`

**Comment by sodevel** [comment]
The root cause is that newer versions of meson / different platforms it runs on output libraries in a architecture tagged subdirectory. I don't know why it does this, how it can be changed or if this is state-of-the-art now and wxFB should be changed.

**Comment by jmoraleda** [comment]
FWIW I just read that meson's default `libdir` is platform dependent (https://mesonbuild.com/Builtin-options.html). I don't know what the best way to deal with the problem is.

**Comment by jhasse** [comment]
I think wxFormBuilder should also check the platform-dependend directory, not sure what's the best way to get it in C++.

**Comment by sodevel** [comment]
I finally found the reason for this issue but im afraid there is no simple solution for it. wxFB relies on `wxStandardPaths::GetPluginsDir()` to determine the directory of the plugins but this method returns even today a hardcoded value (https://github.com/wxWidgets/wxWidgets/blob/8df97af5fed9220486be3d390ea6355b3c8b4c93/src/unix/stdpaths.cpp). Meson however, if i understand it correctly, i cannot follow the source completely, uses quite a lot of logic to resolve the library dir (https://github.com/mesonbuild/meson/blob/18aff92d7a9f110cc3c790c61c2ced85b8d81a26/mesonbuild/mesonlib.py, search for libdir). So basically it is wxWidgets fault, i have found a 12 years old ticket about this (http://trac.wxwidgets.org/ticket/10417) but there is no progress at all.

The question is, how can that platform depended path be supplied to wxFB on ALL platforms and preferrably not only with Meson but currently also PreMake and maybe in the future CMake?

**Comment by bosso73** [comment]
Had the same issue with wxFormBuilder 3.9.0 and openSuse 15.2 Leap.
When I set a symbolic link in the _install directory it worked.
Hence:
```
cd wxFormBuilder-master
./create_build_files5.sh
meson _build --prefix $PWD/_install
ninja -C _build install
cd _install
ln -s lib64 lib
bin/wxformbuilder
```

**Comment by stefanos82** [comment]
> The instructions that worked for me to work around this issue were, from the `git` checkout directory:
> 
>     * Configure and build the usual way:
>       `meson _build --prefix $PWD/_install`
>       `ninja -C _build install`
> 
>     * Add a symbolic link to the location where the executable is expecting the libraries
>       `ln -s x86_64-linux-gnu/wxformbuilder/ _install/lib`
> 

I use Debian and the above code for symlink didn't work; to remedy the issue all I had to do was to replace `_install/lib` with `.`: 

```
cd _install/lib
ln -s x86_64-linux-gnu/wxformbuilder/ .
```

>     * Run the usual way
>       `./_install/bin/wxformbuilder`
