### ISSUE TITLE
Install from source doesn't work for Windows(can't run after building). 

### ISSUE THREAD

**Issue by Kvaz1r** [wxFormBuilder/wxFormBuilder#533]
.exe start running only when I manually transferred .dll files from old version.  

I see couple similar issues but they already closed.

**Comment by sodevel** [comment]
How do you build on Windows, with Meson or PreMake? What DLL files you need to copy?

At least PreMake does not take care of external DLLs, this is the wxWidgets DLL and the ones your compiler needs. You have to make sure that these are available on the search path, easiest way is to copy them in the output folder. This is not an error but kind of a limitation of the build system.

**Comment by Kvaz1r** [comment]
Via MSYS commands from Readme.
I don't know what exactly .dll was needed so just copied all of them (wxwidget , other dependency and standard (libstdc++-6, libgcc_s_dw2-1)).

**Comment by sodevel** [comment]
This is the expected behavior. You can use a dependency checker to figure out the exact dependencies but beside the single wxWidgets DLL there are only the compiler DLL's left, like in your case the C++ runtime DLL and DWARF-2 MinGW DLL.

**Comment by Kvaz1r** [comment]
Yes, it's not the point. I think it would be better write about it in Readme (especially if it's expected), because it's common issue and people back into it again and again.
