### ISSUE TITLE
Debian 10, building from source

### ISSUE THREAD

**Issue by denisgottardello** [wxFormBuilder/wxFormBuilder#549]
After having built wxFormBuilder in Debian 10
![Screenshot_20191009_154059](https://user-images.githubusercontent.com/43038562/66486657-56518100-eaab-11e9-9a1c-e9500725bee7.png)
, if I run it by typing
./_install/bin/wxformbuilder
I obtain
`15:37:07: Could not set current working directory (error 2: No such file or directory)
15:37:07: /home/denis/Cpp/wxFormBuilder/_install/lib/wxformbuilder/libcontainers.so: cannot open shared object file: No such file or directory
15:37:07: Error loading library /home/denis/Cpp/wxFormBuilder/_install/lib/wxformbuilder/libcontainers <database.cpp@1426>
15:37:07: Could not set current working directory (error 2: No such file or directory)
15:37:07: /home/denis/Cpp/wxFormBuilder/_install/lib/wxformbuilder/liblayout.so: cannot open shared object file: No such file or directory
15:37:07: Error loading library /home/denis/Cpp/wxFormBuilder/_install/lib/wxformbuilder/liblayout <database.cpp@1426>
15:37:07: Could not set current working directory (error 2: No such file or directory)
15:37:07: /home/denis/Cpp/wxFormBuilder/_install/lib/wxformbuilder/libadditional.so: cannot open shared object file: No such file or directory
15:37:07: Error loading library /home/denis/Cpp/wxFormBuilder/_install/lib/wxformbuilder/libadditional <database.cpp@1426>
15:37:07: Could not set current working directory (error 2: No such file or directory)
15:37:07: Could not set current working directory (error 2: No such file or directory)
15:37:07: Could not set current working directory (error 2: No such file or directory)
15:37:07: /home/denis/Cpp/wxFormBuilder/_install/lib/wxformbuilder/libcommon.so: cannot open shared object file: No such file or directory
15:37:07: Error loading library /home/denis/Cpp/wxFormBuilder/_install/lib/wxformbuilder/libcommon <database.cpp@1426>
15:37:07: Could not set current working directory (error 2: No such file or directory)
15:37:07: Could not set current working directory (error 2: No such file or directory)
15:37:07: /home/denis/Cpp/wxFormBuilder/_install/lib/wxformbuilder/libforms.so: cannot open shared object file: No such file or directory
15:37:07: Error loading library /home/denis/Cpp/wxFormBuilder/_install/lib/wxformbuilder/libforms <database.cpp@1426>
`

After that the main form appears but it is unisable, all the objects are missing

**Comment by sodevel** [comment]
Does the directory `/home/denis/Cpp/wxFormBuilder/_install/lib/wxformbuilder` exist? Do you have proper read access to every part of it?

**Comment by denisgottardello** [comment]
denis@tomcat:~/Cpp/wxFormBuilder$ **ls -lh _install/lib**
totale 4,0K
drwxr-xr-x 3 denis denis 4,0K ott  9 16:37 x86_64-linux-gnu


denis@tomcat:~/Cpp/wxFormBuilder$ **ls -lh _install/lib/x86_64-linux-gnu/**
totale 4,0K
drwxr-xr-x 2 denis denis 4,0K ott  9 16:37 wxformbuilder


denis@tomcat:~/Cpp/wxFormBuilder$ **ls -lh _install/lib/x86_64-linux-gnu/wxformbuilder/**
totale 15M
-rwxr-xr-x 1 denis denis 3,7M ott  9 16:37 libadditional.so
-rwxr-xr-x 1 denis denis 2,9M ott  9 16:37 libcommon.so
-rwxr-xr-x 1 denis denis 2,8M ott  9 16:37 libcontainers.so
-rwxr-xr-x 1 denis denis 2,6M ott  9 16:37 libforms.so
-rwxr-xr-x 1 denis denis 2,5M ott  9 16:37 liblayout.so

**Comment by sodevel** [comment]
So it's the same reason like in #524, for some reason the libraries get created inside a subdirectory. I don't know what is causing this, but refer to the linked issue for a solution.
