### ISSUE TITLE
checking wxCAL_SHOW_WEEK_NUMBERS on wxCalendarCtrl properties generate wx.CAL_SHOW_WEEK_NUMBERS instead of wx.adv.CAL_SHOW_WEEK_NUMBERS

### ISSUE THREAD

**Issue by cigusi** [wxFormBuilder/wxFormBuilder#559]
As title says using wxCalendarCtrl with style option  wxCAL_SHOW_WEEK_NUMBERS generate
self.myMonthCalendar = wx.adv.CalendarCtrl( self, wx.ID_ANY, wx.DefaultDateTime, wx.DefaultPosition, wx.DefaultSize, wx.adv.CAL_SHOW_HOLIDAYS|wx.CAL_SHOW_WEEK_NUMBERS )

and I need to correct to add "adv." like below. 
self.myMonthCalendar = wx.adv.CalendarCtrl( self, wx.ID_ANY, wx.DefaultDateTime, wx.DefaultPosition, wx.DefaultSize, wx.adv.CAL_SHOW_HOLIDAYS|wx.adv.CAL_SHOW_WEEK_NUMBERS )
otherwise I get error.

I am not sure it is an issue or not as I am new to wxFormBuilder but thought to inform as every time I change something in wxFB then I have to correct manually in the project where i use the generated python script.
using the latest wxFB version.

**Comment by Kvaz1r** [comment]
It's definitely a bug, I've opened PR with fix. For some reason this style wasn't added in the list so solution is trivial.

**Comment by sodevel** [comment]
Like outlined in #459 the code generation for Python and Lua is not ideal at the moment. Another problem is that there is currently no active developer who is using Python or Lua and at least in Python there have been some big changes in the past according to modules. Most probably there will be more cases where the module got changed and the lookup table didn't get updated. I simply don't have the time to check the recent Python bindings and update the code generators plus i don't know what Python is currently in widespread use and what will break if everything gets updated to the latest version.
