### ISSUE TITLE
Multiple exceptions thrown during startup

### ISSUE THREAD

**Issue by Randalphwa** [wxFormBuilder/wxFormBuilder#561]
Currently during startup, calls to ObjectDatabase::ParseProperties() and ObjectDatabase::ParseEvents() results in a large number of exceptions thrown by the tinyxml library. The reason for this is that instead of checking return values and types, the methods are relying on catching the exception when invalid calls are being made. I.e, currently we have this code:

```
		try
		{
			ticpp::Node* lastChild = elem_evt->LastChild();
			ticpp::Text* text = lastChild->ToText();
			def_value = text->Value();
		}
		catch( ticpp::Exception& ){}
```

We don't check for _lastChild_ being NULL (**LastChild**() will throw an exception rather than returning NULL), and we call **ToText**() even if the child isn't a text type. Instead of silently catching the exception, we could write the code to avoid the exception in the first place:

```
		try
		{
			ticpp::Node* lastChild = elem_prop->LastChild(false);
			if (lastChild && lastChild->Type() == TiXmlNode::TEXT)
			{
				ticpp::Text* text = lastChild->ToText();
				wxASSERT(text);
				def_value = text->Value();
			}
		}
		catch( ticpp::Exception& ex)
		{
			wxLogError( ex.what() );
		}
```

Replacing the three locations where the current code relies on exceptions results in a completely clean startup -- no exceptions thrown at all.

**Comment by sodevel** [comment]
I am quite unsure what i shall do with this information now. Is there a case where these exceptions cause an error? Or is this just a more or less optimization, replace exception based error handling with error code error handling?

I am not familiar with the TiCPP library at all, i see that your suggested change still requires exception handling, what is the benefit of doing both?

**Comment by Randalphwa** [comment]
The exceptions do not cause a programming error, it's more of a performance hit since exceptions have to do stack unwinding. For example, instead of checking to see if an element is a text type, the code currently simply assumes it is and relies on tinyxml to throw an exception if it is not.

The object here is not to remove exceptions, but rather to use them only to catch unexpected errors rather then using them for expected conditions (we know we will step past the last child, and we know that not all child elements will be text types).

If you would prefer, I can make a PR with the changes in place for a more thorough code review. Since I'm new to submitting PR's to this project, I want to be sure I understood the process before I simply started adding issues followed by a PR.

**Comment by sodevel** [comment]
In general enhancements and especially fixes are welcome. If it is a rather small and local change that does not require a huge discussion it is fine to just post a PR. If it has a larger impact on the code base or usability it is better to ask first before spending time on something that has a low chance to get merged.

Please keep in mind that wxFB runs on three platforms and supports four different languages, changes should not break that and additions should be usable for all languages if possible. I know from personal experience the second point can be challenging.

Your proposal sounds good and i would happily merge that PR.

**Comment by Randalphwa** [comment]
Can you clarify a bit more on what to avoid doing that breaks alternate language support? I always use _() or wxTRANSLATE() macros for any text presented to the user, but I don't see .po or .mo files as part of the project, so it appears the strings aren't currently translated? Also, I see that wxT() is being used a lot even though wxWidgets states it is only there for compatibility with versions prior to 2.9. The compiler and wxWidgets appear to be fine with just "" instead of wxT("") for non-UI strings -- do you have a preference?

**Comment by sodevel** [comment]
Sorry for the confusion but i wasn't talking about the languages of the UI but of the languages the code gets generated for: C++, Python, PHP and LUA.

The situation with the UI languages is bad, there is a bit of too much usage of _(), even data values stored in the project files get passed through this macro, so currently it's not possible to support any other language than english (unless you want to deal with localized project files that can only be processed by a wxFB of the same locale).

I don't understand why wxWidgets states that wxT() is useless, at least on windows it has a huge impact. Windows doesn't support unicode in narrow strings (well, looks like the very latest Windows 10 update did change that, but i didn't check the details) so without wxT(), which does expand to a wide string there, it is impossible to use any character in string literals that your compile time locale doesn't contain.

So for now we use wxT() for all literals that should not be translated and _() or wxTRANSLATE() for the ones that should.
