### ISSUE TITLE
Missing wxFormBuilder-cmake_build\sdk\ticpp

### ISSUE THREAD

**Issue by leevawns** [wxFormBuilder/wxFormBuilder#564]
There were no files in this directory when I downloaded the zip file

**Comment by patlkli** [comment]
It seems that you have downloaded a snapshot of the `cmake_build` branch, which isn't up-to-date at all right now. On top of that, you're missing the appropriate submodules.

Please use the master branch or one of the release tags for now and build it as instructed in the README file.

**Comment by leevawns** [comment]
I want to build it by cmake in msys, I solved the problem by copying the version of ticpp into the directory, build finish
