### ISSUE TITLE
Proposal for changes to UI dealing with old project files

### ISSUE THREAD

**Issue by Randalphwa** [wxFormBuilder/wxFormBuilder#567]
A while back I used **wxFB** to look at some project files in a repository I had cloned. I got a somewhat odd message about the project file being old (the message is missing a verb and has some unusual sentence construction), and saw the bit about the old file being overwritten. I assumed that meant I would overwrite it if I clicked Save rather than Save As, so I continued opening various project files. Then I noticed that GitHub Desktop was telling me I had modified every .fbp file I opened, but apparently nothing else had changed. **wxFB** hadn't told me where it was saving the backup files to, so I just checked the .fbp files out again to restore them. While doing that I did notice the .bak files, but they had an old file date so I assumed they were part of the repository. It wasn't until I was looking at the **wxFB** code that I realized where it saved the backup files to.

While looking at the **wxFB** code, the other thing I noticed is that there is no check to see if the backup file was successfully created. While it's highly unlikely that it would fail, that's small comfort to someone that doesn't have a backup of the original file.

I have some proposals that might reduce the chances of someone else inadvertently changing a project file and not knowing how to get it back:

- Change the wording to say where the old file will be copied to and indicating that the new project will be automatically saved.
- Confirm that the backup copy was created. If not, give the user the option of trying again (so they can fix network issues, disk space, unprotecting the file, etc.), skipping the backup, or just cancelling opening the project file.

Longer term once I've had a chance to become a lot more familiar with the code base, I'd like to look at the conversion results which are currently displayed in a really long line that's hard to read -- it'd be nice to make that easier to read. The bigger issue is why the project needs to be saved in the first place -- I suspect that's a coding requirement rather than a design choice, but I do think it would better if reasonably possible to not automatically overwrite the original file unless the user asks to.

**Comment by sodevel** [comment]
These are all good ideas to make the workflow more user friendly. I wouldn't put too much effort into that what you call conversion results, this is actually kind of an internal that the user shouldn't even see. The information of these removed parameters should have been preserved during the conversion, otherwise there was an data loss during the conversion, maybe that should be presented to the user somehow.
