### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by osnipezzini** [wxFormBuilder/wxFormBuilder#586]
I'm use tutorial from README.md to compile for Windows .

But i faced this :

![image](https://user-images.githubusercontent.com/4562546/73308831-de48cb80-41ff-11ea-94c7-c355e21b141a.png)

**Comment by Kvaz1r** [comment]
The instruction works for me. Text of error more like there is some problem with g++ installing not about related to wxFormBuilder. Can you provide more information about your environment?

**Comment by sodevel** [comment]
I am not an MSYS2 expert but there are different "types" of MSYS2 shells you can start, they differ in the path setup. You probably started a plain MSYS2 shell that doesn't have any compiler in the path, like the instructions say you have to start a MinGW 32-bit shell. In a standard installation you should have 3 MSYS links in your start menu, you have to use the `MSYS2 MinGW 32-bit`.

As an alternative you can build with Visual Studio together with a self built wxWidgets version (or use a prebuilt version, not sure if they contain the required monolithic variant though). This has the advantage that you can use a much newer wxWidgets version, the 3.x version of MSYS2 causes a few problems with wxFB.

**Comment by osnipezzini** [comment]
I tryed with visual studio too , but i found problem with files missing in SDK

**Comment by sodevel** [comment]
I am building with VS 2019 myself and both paths, Premake 4 and Premake 5, work without problems for me. What is the exact error? What is the command line you used to create the project files? Did you forget to clone with submodules?

Or are you trying to build the SDK alone? This is only required if you want to create a plugin and that is currently broken like outlined in #579.

**Comment by tomay3000** [comment]
Msys2 sucks, and can't live without patches.
its Binutils as of version 2.31 is very buggy and kan't link sometimes with errors.
Me myself I have switched back the plain and stable [MinGW-w64 GCC-8.1.0](https://sourceforge.net/projects/mingw-w64/files/) toolchain.
[wxWidgets v3.1.3](https://github.com/wxWidgets/wxWidgets/releases/tag/v3.1.3) and [Code::Blocks svn 11957](http://forums.codeblocks.org/index.php?topic=23673.0) prebuilt banaries are using this exact toolchain.

**Comment by keleven-uk** [comment]
Mine failed also, but when I read this and properly read the instructions to use MSYS2 MinGW 32-bit - it worked perfectly. :-)
