### ISSUE TITLE
wxSplitterWindow python code generation broken because of bad indentation.

### ISSUE THREAD

**Issue by jmoraleda** [wxFormBuilder/wxFormBuilder#587]
When creating a splitter window, the following python code is generated:

```python
	def m_splitter1OnIdle( self, event ):
	self.m_splitter1.SetSashPosition( 0 )
	self.m_splitter1.Unbind( wx.EVT_IDLE )
```

but should have been

```python
	def m_splitter1OnIdle( self, event ):
	    self.m_splitter1.SetSashPosition( 0 )
	    self.m_splitter1.Unbind( wx.EVT_IDLE )
```

A git bisect reveals that the culprit is commit 6f2fa937a8c1afb459870542a4ad7296da999776 which inappropriately trims leading white space in this case.

**Comment by sodevel** [comment]
At first glance it looks like the code path introduced by that commit isn't even executed by the affected template, after all it produces a multi-line result. At second glance there is a recursive call happening that does call that code path with parameters that should actually result into removing the indentation.

I don't know why it was working before, a quick fix however made it even worse, there is some weird logic happening, i'll take a look into that.
