### ISSUE TITLE
Bugs: Python,  adding columns to wx.dataview.DataViewListCtrl

### ISSUE THREAD

**Issue by elitur** [wxFormBuilder/wxFormBuilder#589]
Hi,

instead of flags named like "wx.dataview.DATAVIEW.<flag name>" flags named like "wx.DATAVIEW.<flag name>" are added .

Thank you in advance!

**Comment by sodevel** [comment]
As outlined in #459 the C++ names are used in wxFB and unfortunately the Python binding sometimes isn't 1:1 so the generic approach to generate the Python names fail. To deal with that there are hardcoded lists in the source to use specific translations but currently there is no active wxFB developer using Python so these lists became outdated.

That solution isn't ideal but currently there is no other one available. If you are using Python the best you could do is update these lists and post a PR, i don't have the time to look through wxPython to update these lists.

**Comment by elitur** [comment]
Hi,
thank you very much for the moment reaction. You do a great job from all points of view! I'll see what can be done. But not immediately (deeply inside some research).

Best regards!
