### ISSUE TITLE
codewriter.cpp:77:73: error: ‘wxRegEx::wxRegEx(const wxRegEx&)’ is private within this context

### ISSUE THREAD

**Issue by pbertoni89** [wxFormBuilder/wxFormBuilder#593]
While checking out 006148d5348ad6ff189ee0ea8b0f350d6ec163ad, obtained both with
```
meson _build --prefix $PWD/_install
ninja -C _build install
```
And with old-fashioned
```
/create_build_files4.sh
cd build/3.0/gmake
make config=release
```

>../src/codegen/codewriter.cpp:77:73: error: ‘wxRegEx::wxRegEx(const wxRegEx&)’ is private within this context
>  static const wxRegEx reIndent = wxRegEx(wxT("%TAB%\\s*"), wxRE_ADVANCED);

**Comment by sodevel** [comment]
What compiler and its version and which wxWidgets version are you using?

**Comment by pbertoni89** [comment]
Non-default alternative `Ubuntu 6.5.0-2ubuntu1~18.04) 6.5.0` due to non-related issues.
After rolling back to default `Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0`, everything's ok!
