### ISSUE TITLE
Complie ubuntu 20.04

### ISSUE THREAD

**Issue by damufo** [wxFormBuilder/wxFormBuilder#598]
How to compile for ubuntu 20.04?
> sudo apt install libwxgtk3.0-dev libwxgtk-media3.0-dev meson
In ubuntu 20.04 the packages dev are renamed to:
libwxgtk3.0-**gtk3**-dev
libwxgtk-media3.0-**gtk3**-dev

Very thanks.

**Comment by guysoft** [comment]
See #613

**Comment by sodevel** [comment]
Fixed by #613
