### ISSUE TITLE
Generate coding, does nothing

### ISSUE THREAD

**Issue by KammutierSpule** [wxFormBuilder/wxFormBuilder#600]
v3.9.0
It used to work. I just test it with a previous file I used.
Now when I press button of on the file menu, there is no generate files, no message or anything.
Any idea?

**Comment by KammutierSpule** [comment]
I found it:
The "code_generation" option was not selected, so I must select C++ in order to it work

**Comment by sodevel** [comment]
This looks like this was an user error. Another cause might have been an error during project file conversion, but to confirm that more details are necessary.
