### ISSUE TITLE
SetPropertyHelpString is not using "self." in python code generation

### ISSUE THREAD

**Issue by clawjelly** [wxFormBuilder/wxFormBuilder#601]
When creating a property grid item and adding a help text, the generated python code is buggy, as it misses the "self."-prefix:

```
self.m_propertyGrid2 = pg.PropertyGrid(self, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, wx.propgrid.PG_DEFAULT_STYLE)
self.m_propertyGridItem6 = self.m_propertyGrid2.Append( pg.StringProperty( u"Name", u"Name" ) )
self.m_propertyGrid2.SetPropertyHelpString( m_propertyGridItem6, u"Some Help Text" )
```

The last line should have `self.m_propertyGridItem6` as first parameter instead of `m_propertyGridItem6`. 

**Steps to reproduce:** Create in order a frame, a sizer, a property grid and a property item. Add help text to property item.

**Comment by Kvaz1r** [comment]
It seems a typo in this [line](https://github.com/wxFormBuilder/wxFormBuilder/blob/91bc87596a0cd4e426a59fef58089ce0744200a0/output/plugins/additional/xml/data.pythoncode#L299). I'm going to open PR with fix.
