### ISSUE TITLE
Install instructions are causing virus detection

### ISSUE THREAD

**Issue by IamSierraCharlie** [wxFormBuilder/wxFormBuilder#603]
Hi, I haven't installed wxFormbuilder ina while, but am going through the process again.  I'm following the exact process provided to perform the install and my antivirus is showing the following...
![image](https://user-images.githubusercontent.com/10386637/80899286-b9f61100-8d51-11ea-8908-f659529e6840.png)
Thought I'd raise it because I couldn't find anything on it. (maybe googling the wrong thing)
Is this anything to worry about?

**Comment by sodevel** [comment]
The "infected" application is part of the GCC compiler toolchain of MSYS2 so this is the wrong place to raise the issue. In general virus scanners can produce false positives and like to do that for development tools. I can't do much more than giving the general advice to check with multiple scanners and search for other reports about it.

**Comment by IamSierraCharlie** [comment]
okay thankyou for your feedback
