### ISSUE TITLE
wxformbuilder generates wx.THICK_FRAME if you have wx.RESIZE_BORDER set for a dialog

### ISSUE THREAD

**Issue by dhyams** [wxFormBuilder/wxFormBuilder#605]
wx.THICK_FRAME is gone in wxPython; the fix here I think is easy; just don't output that flag.  

https://github.com/wxWidgets/Phoenix/issues/481

**Comment by sodevel** [comment]
Unless i have missed something current master also doesn't use this flag anymore.

**Comment by dhyams** [comment]
OK; interesting; I'm using latest release 3.9.  I did an issue search to see if there was something similar before posting, but maybe it's fixed already in master.

This is for Python code generation.

**Comment by dhyams** [comment]
Ah, OK; the behavior is actually little more interesting.  I am working with files that have been upgraded for nearly a decade.  If I go into wxFormbuilder, turn wxRESIZE_BORDER off and save then file, then turn wxRESIZE_BORDER on and save the file, then wx.THICK_FRAME doesn't appear in the generated code.

I think it has something to do with the major and minor fileversion of my .fbp files.

**Comment by dhyams** [comment]
To follow up yet again, I think what happened is that I loaded the fbp file into 3.9, letting it convert to the latest version, generated the code, and then saved the file.  So wxFormbuilder, when I generated the code, thought the file version was older than what it really was, maybe, because I had not saved it yet.
