### ISSUE TITLE
Purpose for label in wxMenuBar

### ISSUE THREAD

**Issue by Kvaz1r** [wxFormBuilder/wxFormBuilder#610]
What is purpose for label field in wxMenuBar? It don't use in code but only for xrc.

**Comment by sodevel** [comment]
Currently it indeed serves no purpose, even XRC doesn't use this (at least according to the latest documentation) so it is kind of wrong to add that property there. Maybe this is a leftover from a distant past where this might have had a use or an error that got never noticed. For me it looks like it can be removed.
