### ISSUE TITLE
Toolbar Icons too Small

### ISSUE THREAD

**Issue by ptrongithub** [wxFormBuilder/wxFormBuilder#612]
Please update the interface for those of us with high-res displays. Please see this screenshot.

![image](https://user-images.githubusercontent.com/26679996/83314270-aff7ee80-a1e7-11ea-9c4d-b5f3016ad637.png)

**Comment by Kvaz1r** [comment]
Duplicate: https://github.com/wxFormBuilder/wxFormBuilder/issues/295

**Comment by ptrongithub** [comment]
Issue #295 referenced #555, which mentioned a workaround. It took me a bit to find it. Here is the workaround that works for me:

![image](https://user-images.githubusercontent.com/26679996/83329403-47485a80-a257-11ea-8745-17375a3c1601.png)

In the shortcut properties for wxFormBuilder, to to `Compatibility` -> `Change high DPI settings`. 
Then Check `Override high DPI scaling behavior.` Set `Scaling performed by:` to `System` or `System (Enhanced)`. You may ignore `Use this setting to fix scaling problems for this program instead of the one in Settings`.
