### ISSUE TITLE
Runtime error - embedding python into c

### ISSUE THREAD

**Issue by bsrc** [wxFormBuilder/wxFormBuilder#614]
I am working on a project which is related to object detection and ocr. I am using Ubuntu 18.04 and python 2.7, yolov3 for object detection and tesseract 5.0.0-alpha-692-g62ea for ocr. I have to embed the python code that is for ocr into the C code for object detection. I wrote this C code and compile at the terminal by " sudo gcc code.c -lpython2.7 "

```
#include </usr/include/python2.7/Python.h>

int main() {
Py_Initialize();
PyRun_SimpleString("import sys; sys.path.append('.')");
PyRun_SimpleString("import ocr3;");
PyRun_SimpleString("print ocr3.myabs(2.0)");
Py_Finalize();

return 0;
}
```

but it gives an error while running a.out:

```
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
File "", line 1, in
File "./ocr3.py", line 1, in
import cv2
File "/home/asus/.local/lib/python2.7/site-packages/cv2/init.py", line 3, in
from .cv2 import *
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
File "", line 1, in
NameError: name 'ocr3' is not defined
```

so, I tried another C code:

```
#include <stdio.h>
#include <ncurses.h>
#include </usr/local/include/python2.7/Python.h>

int main()
{
char filename[] = "ocr3.py";
FILE* fp;

Py_Initialize();

fp = _Py_fopen(filename, "r");
PyRun_SimpleFile(fp, filename);

Py_Finalize();
return 0;
}
```
but again I have an issue while running a.out: `" code.c:(.text+0x3e): undefined reference to _Py_fopen' "
`
Unfortunately, I could not find any solution. Can anyone help about the fix one of the these problems?

**Comment by sodevel** [comment]
This question is totally unrelated to wxFormBuilder. Joining GitHub to just spam this question to multiple random projects that have Python in their description is not exactly a great start. 

Additionally Issues are usually not the place to ask general programming questions or questions in general, some projects might have a different policy about questions, but for sure these questions have to be about the project and not something unrelated or general.
