### ISSUE TITLE
Create RichText XRC object for RichTextCtrl instead of "Unknown" object

### ISSUE THREAD

**Issue by bigpilot** [wxFormBuilder/wxFormBuilder#618]
The current implementation generates an Unknown object for the RichTextCtrl even though wxWidgets XRC implementation seems to have support for a RichTextCtrl (src/xrc/xh_richtext.cpp)

Code needs to be changed in plugins/additional/additional.cpp (RichTextCtrlComponent::ExportToXrc())

**Comment by sodevel** [comment]
I happily merge a PR that implements this

**Comment by guysoft** [comment]
Hey, has this been released? The last release v3.9.0 seems to be from 2018.

**Comment by bigpilot** [comment]
It's probably present in the master branch. Build from source if you want it.
