### ISSUE TITLE
期望新版本的可执行程序发布

### ISSUE THREAD

**Issue by cwhuasmile** [wxFormBuilder/wxFormBuilder#620]
你好，我看到目前的版本已经是两年前的了，而我又不会使用readme.md中的教程编译可执行程序，还是希望你能发布一个新版的可执行程序。谢谢

**Comment by sodevel** [comment]
English only please! This projects language is english, we can't and don't want to support different languages in communication, this makes it easier for us and our audience to follow conversations.

**Comment by cwhuasmile** [comment]
Hello, sorry first, because I am not very proficient in English, the following is machine translated: I see that the current version is already two years ago, and I will not use the tutorial compilation in readme.md Executable program, I still hope you can release a new version of the executable program. Thank you

**Comment by sodevel** [comment]
And i don't understand any chinese. Currently no next release is scheduled, if you are on windows you can use a CI build from GitHub Actions, e.g. https://github.com/wxFormBuilder/wxFormBuilder/suites/909694405/artifacts/10986569, otherwise you have to compile yourself.

**Comment by cwhuasmile** [comment]
> And i don't understand any chinese. Currently no next release is scheduled, if you are on windows you can use a CI build from GitHub Actions, e.g. https://github.com/wxFormBuilder/wxFormBuilder/suites/909694405/artifacts/10986569, otherwise you have to compile yourself.

Thank you very much
