### ISSUE TITLE
Use the default values defined by wxWidgets library

### ISSUE THREAD

**Issue by Micheus** [wxFormBuilder/wxFormBuilder#640]
For code optimisation, it would be good if the default values set by wxWidgets would be respected. That way we could avoid to get code where it should not be added.

An example are the properties show/hide effect in _wxInfoBar_ class. They default value was set to **wxSHOW_EFFECT_NONE**, but in accord with the[ wxWidgets docs](https://docs.wxwidgets.org/3.0/classwx_info_bar.html#a7a07a24280a4a3e64ab13db6c1106a44) they are **wxSHOW_EFFECT_SLIDE_TO_BOTTOM** and **wxSHOW_EFFECT_SLIDE_TO_TOP** respectively:

> Either or both of the parameters can be set to wxSHOW_EFFECT_NONE to disable using effects entirely.
> 
> By default, the info bar uses wxSHOW_EFFECT_SLIDE_TO_BOTTOM effect for showing itself and wxSHOW_EFFECT_SLIDE_TO_TOP for hiding if it is the first element of the containing sizer and reverse effects if it's the last one. If it is neither the first nor the last element, no effect is used to avoid the use of an inappropriate one and this function must be called if an effect is desired.

In order to not generate code for what should be default, we can write a template script like this:
```
  <template name="settings">
    ifnotequal $show_effect "wxSHOW_EFFECT_SLIDE_TO_BOTTOM"
    @{ #class:setShowHideEffects($name, $show_effect, $hide_effect), }@
    ifequal $show_effect "wxSHOW_EFFECT_SLIDE_TO_BOTTOM"
    @{
      #ifnotequal $hide_effect "wxSHOW_EFFECT_SLIDE_TO_TOP"
      @{ #class:setShowHideEffects($name, $show_effect, $hide_effect), }@
    @}
  </template>
```
which, in this case, will always generate an unnecessary line for _setShowHideEffects_.

Supposing we want to keep the system behaviour, we have to remember which settings to use otherwise we are disabling it as it was the default behaviour.

**Comment by sodevel** [comment]
In general it is always a good idea to use the default values if nothing is set, however your suggested approach is not suitable for a couple of reasons. First, you put quite some logic into the code templates, this is not the proper place for such logic. Second, you kind of ignore what the user specified in the project and don't apply his settings because you assume these are the default values and they don't need to be set. This also sort of duplicates the knowledge about what the default values are, if these get changed for some reason in the future you need to update your "copy" of these values as well.

The better approach is to simply don't apply any settings if you want to use the defaults. This is kind of a problem for wxFB because some controls simply don't allow to "set nothing". Even worse, some controls display some value in case there is nothing set (because the default value is "set nothing") although the displayed settings don't get applied. However, if you change that setting to something else and reset it to what was displayed before, this actually does not reset to "set nothing" but now actually applies what is displayed. Most prominent examples for this issue are colors and fonts.

Luckily, the example you mentioned above is not affected by this issue because these two settings are of type option. For this type there is a way to set them to nothing and this gets used by e.g. wxDataView related elements. Just add an option with an empty value, this is not a valid option. The code template just has to check if the value is empty and don't do anything in that case.

**Comment by Micheus** [comment]
> First, you put quite some logic into the code templates
Well, it's a resource available - why not to use?!
That has been working well and helping to reduce the amount of code on constructors since for some controls we have a couple of create options, each one using different amount of parameters - which also can help us to remove some lines usually present in settings session - comparing to doing an exact translation from C++ templates  (a short and less confusing code is preferred in Erlang code - a [menu sample](https://github.com/erlang-labs/wx/blob/master/examples/demo/ex_popupMenu.erl)).

For the menus I coded the template with that in mind. A comparison can be saw bellow. The use of variable declarations is minimised as in their standardised examples (maybe to minimise the garbage collection - I don't know Erlang in deep to be sure).

I've trying to respect the C++ source code restrictions/formations you want - in accordance with some comments I found reading some of PR's -, but if the template files must to follow the exact translation of the C++ ones, maybe I'm just wasting my time. Please let me know it that will be a problem.

Anyway, thanks for comment and congrats for your enforce on this tool - very useful.


**C++** code generated
```
	m_menubar1 = new wxMenuBar( 0 );
	m_menu1 = new wxMenu();
	wxMenuItem* m_menuItem1;
	m_menuItem1 = new wxMenuItem( m_menu1, wxID_ANY, wxString( wxT("wxMenuItem Normal") ) + wxT('\t') + wxT("Ctrl+B"), wxEmptyString, wxITEM_NORMAL );
	m_menu1->Append( m_menuItem1 );
	m_menuItem1->Enable( false );
	m_menu1->AppendSeparator();
	wxMenuItem* m_menuItem6;
	m_menuItem6 = new wxMenuItem( m_menu1, wxID_ANY, wxString( wxT("wxMenuItem Radio") ) , wxEmptyString, wxITEM_RADIO );
	m_menu1->Append( m_menuItem6 );
	m_submenu1 = new wxMenu();
	wxMenuItem* m_submenu1Item = new wxMenuItem( m_menu1, wxID_ANY, wxT("Sub Menu"), wxEmptyString, wxITEM_NORMAL, m_submenu1 );
	wxMenuItem* m_menuItem2;
	m_menuItem2 = new wxMenuItem( m_submenu1, wxID_ANY, wxString( wxT("wxMenuItem Check") ) , wxEmptyString, wxITEM_CHECK );
	m_submenu1->Append( m_menuItem2 );
	m_menuItem2->Check( true );
	wxMenuItem* m_menuItem5;
	m_menuItem5 = new wxMenuItem( m_submenu1, wxID_ANY, wxString( wxT("wxMenuItem Check Disabled") ) , wxEmptyString, wxITEM_CHECK );
	m_submenu1->Append( m_menuItem5 );
	m_menuItem5->Enable( false );
	m_menuItem5->Check( true );
	m_menu1->Append( m_submenu1Item );
	m_menubar1->Append( m_menu1, wxT("wxMenu 1") );
	this->SetMenuBar( m_menubar1 );
	m_toolBar1 = this->CreateToolBar( wxTB_HORIZONTAL, wxID_ANY );
	m_tool1 = m_toolBar1->AddTool( wxID_ANY, wxT("Tool 1"), wxBitmap( wxT("F:\\Temp\\icon_opengl.png"), wxBITMAP_TYPE_ANY ), wxNullBitmap, wxITEM_NORMAL, wxT("Tooltip text"), wxT("StatusBar text"), NULL );
	m_toolBar1->AddSeparator();
	m_tool3 = m_toolBar1->AddTool( wxID_ANY, wxT("Tool 2"), wxBitmap( wxT("F:\\Temp\\icon_opengl.png"), wxBITMAP_TYPE_ANY ), wxNullBitmap, wxITEM_NORMAL, wxEmptyString, wxEmptyString, NULL );
	m_toolBar1->Realize();
	m_menu2 = new wxMenu();
	wxMenuItem* m_menuItem3;
	m_menuItem3 = new wxMenuItem( m_menu2, wxID_ANY, wxString( wxT("wxMenuItem 3") ) , wxEmptyString, wxITEM_NORMAL );
	m_menu2->Append( m_menuItem3 );
	wxMenuItem* m_menuItem4;
	m_menuItem4 = new wxMenuItem( m_menu2, wxID_ANY, wxString( wxT("wxMenuItem 4") ) , wxEmptyString, wxITEM_NORMAL );
	m_menu2->Append( m_menuItem4 );
```
**Erlang** code generated:
```
	M_menubar1 = wxMenuBar:new(),
	M_menu1 = wxMenu:new(),
	wxMenuItem:enable(wxMenu:append(M_menu1, ?wxID_ANY, "wxMenuItem Normal""\t""Ctrl+B", []), [{enable,false}]),
	wxMenu:appendSeparator(M_menu1),
	wxMenu:append(M_menu1, ?wxID_ANY, "wxMenuItem Radio", [{kind,?wxITEM_RADIO}]),
	M_submenu1 = wxMenu:new(),
	wxMenuItem:check(wxMenu:append(M_submenu1, ?wxID_ANY, "wxMenuItem Check", [{kind,?wxITEM_CHECK}]), [{check,false}]),
	M_menuItem5 = wxMenu:append(M_submenu1, ?wxID_ANY, "wxMenuItem Check Disabled", [{kind,?wxITEM_CHECK}]),
	wxMenuItem:check(M_menuItem5, [{check,true}]),
	wxMenuItem:enable(M_menuItem5, [{enable,false}]),
	wxMenu:append(M_menu1, ?wxID_ANY, "Sub Menu", M_submenu1),
	wxMenuBar:append(M_menubar1, M_menu1, "wxMenu 1"),
	wxFrame:setMenuBar(MyFrame1, M_menubar1),
	M_toolBar1 = wxFrame:createToolBar(MyFrame1, [{style,?wxTB_HORIZONTAL} ]),
	wxToolBar:addTool(M_toolBar1, ?wxID_ANY, "Tool 1", wxBitmap:new("F:\\Temp\\icon_opengl.png", [{type,?wxBITMAP_TYPE_ANY}]), [{shortHelp,"Tooltip text"}]),
	wxToolBar:addSeparator(M_toolBar1),
	wxToolBar:addTool(M_toolBar1, ?wxID_ANY, "Tool 2", wxBitmap:new("F:\\Temp\\icon_opengl.png", [{type,?wxBITMAP_TYPE_ANY}]), []),
	wxToolBar:realize(M_toolBar1),
	M_menu2 = wxMenu:new(),
	wxMenu:append(M_menu2, ?wxID_ANY, "wxMenuItem 3", []),
	wxMenu:append(M_menu2, ?wxID_ANY, "wxMenuItem 4", []),
```

**Comment by sodevel** [comment]
> That has been working well and helping to reduce the amount of code on constructors since for some controls we have a couple of create options, each one using different amount of parameters - which also can help us to remove some lines usually present in settings session - comparing to doing an exact translation from C++ templates  (a short and less confusing code is preferred in Erlang code - a [menu sample](https://github.com/erlang-labs/wx/blob/master/examples/demo/ex_popupMenu.erl)).

You should be careful with that, wxFB uses inheritance. Elements further down the chain get constructed by their own construction block, but the settings blocks of all previous classes are also applied. If you move settings from the settings block to the construction block these settings won't get applied for inherited classes.

> I've trying to respect the C++ source code restrictions/formations you want - in accordance with some comments I found reading some of PR's -, but if the template files must to follow the exact translation of the C++ ones, maybe I'm just wasting my time. Please let me know it that will be a problem.

This i don't understand but i also don't know anything about Erlang. In general your generator should generate valid code that does what is designed in wxFB. And the client side should be able to use the generated code to do the missing parts that can't be done in wxFB, like transferring data in and out of the controls. For C++ there are some additional properties like visibility, if these don't apply to Erlang then of course you don't need to support them, the other generators also don't do this.

**Comment by Micheus** [comment]
I've been working on the generator (erlangcg.cpp) and templates (*.erlangcode) in order to create a source that can be compiled and tested in Erlang console (werl.exe/erl.exe). I'm also creating a project for every palette to test its controls and I just go forward after I fixed each one - that is why I have been getting some doubts/questions.

> In general your generator should generate valid code that does what is designed in wxFB. And the client side should be able to use the generated code to do the missing parts that can't be done in wxFB, like transferring data in and out of the controls.

So, we can say I have some level of freedom to work in the specific Erlang code generator and the its templates (*.erlangcode). Is that right?

Like some additions to the templates file like these in [defaul.erlangcode](https://github.com/Micheus/wxFormBuilder/blob/25bf30bbce13674a3734adea0d95683d82022dda/output/xml/default.erlangcode#L38) which I create different template names to be used exclusively by Erlang code generator.

Erlang isn't a OOP language and the code may be slight different from the ones wxFormBuilder offers, but I've getting a good translation from your form designer to the source code. There are some prints in the [post](https://twitter.com/MicheusVieira/status/1307734222300491777).
