### ISSUE TITLE
where is the property page?

### ISSUE THREAD

**Issue by dotkt** [wxFormBuilder/wxFormBuilder#647]
guys my property page just disappear. how to show it ?
![图片](https://user-images.githubusercontent.com/49758966/96530643-73be4b00-12ba-11eb-9404-4263c60bf8e3.png)

**Comment by dotkt** [comment]
need your help thanks

**Comment by dotkt** [comment]
i have solve it.
open reg,delete this:
![图片](https://user-images.githubusercontent.com/49758966/96534647-bb48d500-12c2-11eb-80b3-c5b94d60909c.png)

here you are:
![图片](https://user-images.githubusercontent.com/49758966/96534672-ca2f8780-12c2-11eb-82fb-1f0a1703c421.png)

**Comment by sodevel** [comment]
Another good solution in such cases is also formatting the harddrive or reinstalling windows. And if that fails buying a new computer might help.

Seriously, this is not a solution at all. A proper solution would have been just dragging the slider from the very far right side more to the left so that the object properties pane wouldn't be of zero width anymore.

**Comment by dotkt** [comment]
actually i try .but my mouse did not change it's style. so this is not a solution at all.
________________________________
发件人: Steffen Olszewski <notifications@github.com>
发送时间: 2020年10月20日 19:54
收件人: wxFormBuilder/wxFormBuilder <wxFormBuilder@noreply.github.com>
抄送: dotkt <holiday_life@outlook.com>; State change <state_change@noreply.github.com>
主题: Re: [wxFormBuilder/wxFormBuilder] where is the property page? (#647)


Another good solution in such cases is also formatting the harddrive or reinstalling windows. And if that fails buying a new computer might help.

Seriously, this is not a solution at all. A proper solution would have been just dragging the slider from the very far right side more to the left so that the object properties pane wouldn't be of zero width anymore.

―
