### ISSUE TITLE
Install dir of library is wrong

### ISSUE THREAD

**Issue by jes1510** [wxFormBuilder/wxFormBuilder#649]
Here are the errors:
15:59:09: Could not set current working directory (error 2: No such file or directory)
15:59:09: /home/jesse/tools/wxFormBuilder/_install/lib/wxformbuilder/libcontainers.so: cannot open shared object file: No such file or directory
15:59:09: Error loading library /home/jesse/tools/wxFormBuilder/_install/lib/wxformbuilder/libcontainers <database.cpp@1447>
15:59:09: Could not set current working directory (error 2: No such file or directory)
15:59:09: /home/jesse/tools/wxFormBuilder/_install/lib/wxformbuilder/libforms.so: cannot open shared object file: No such file or directory
15:59:09: Error loading library /home/jesse/tools/wxFormBuilder/_install/lib/wxformbuilder/libforms <database.cpp@1447>
15:59:09: Could not set current working directory (error 2: No such file or directory)
15:59:09: /home/jesse/tools/wxFormBuilder/_install/lib/wxformbuilder/liblayout.so: cannot open shared object file: No such file or directory
15:59:09: Error loading library /home/jesse/tools/wxFormBuilder/_install/lib/wxformbuilder/liblayout <database.cpp@1447>
15:59:09: Could not set current working directory (error 2: No such file or directory)
15:59:09: /home/jesse/tools/wxFormBuilder/_install/lib/wxformbuilder/libadditional.so: cannot open shared object file: No such file or directory
15:59:09: Error loading library /home/jesse/tools/wxFormBuilder/_install/lib/wxformbuilder/libadditional <database.cpp@1447>
15:59:09: Could not set current working directory (error 2: No such file or directory)
15:59:09: Could not set current working directory (error 2: No such file or directory)
15:59:09: Could not set current working directory (error 2: No such file or directory)
15:59:09: /home/jesse/tools/wxFormBuilder/_install/lib/wxformbuilder/libcommon.so: cannot open shared object file: No such file or directory
15:59:09: Error loading library /home/jesse/tools/wxFormBuilder/_install/lib/wxformbuilder/libcommon <database.cpp@1447>
15:59:09: Could not set current working directory (error 2: No such file or directory)

This is what the path really looks like:
/home/jesse/tools/wxFormBuilder/_install/lib/x86_64-linux-gnu/wxformbuilder

This is fixed by moving the wxformbuilder directory out of the x86_64-linux-gnu folder like so:
/home/jesse/tools/wxFormBuilder/_install/lib/wxformbuilder

**Comment by sodevel** [comment]
This is a known problem and not so easy to fix, see #615 and #524

**Comment by pbertoni89** [comment]
Just experienced at 0eccdbc, built under Ubuntu 20.04

**Comment by pbertoni89** [comment]
Lol it seems I found a trick in the past and forgot about it. See #594
