### ISSUE TITLE
Cannot build on OS X 11.0.1, Big Sur

### ISSUE THREAD

**Issue by b123400** [wxFormBuilder/wxFormBuilder#651]
Hello, I've upgraded to OS X 11.0.1, Big Sur, and have a problem building the project.

When I run 

```
make config=release
```

it has trouble finding `libSystem.B.dylib`

```
sh ../../../install/macosx/postbuild.sh -c release
* Collecting dependencies.......
/!\ WARNING : Cannot resolve path '/usr/lib/libSystem.B.dylib'

/!\ WARNING : Library libSystem.B.dylib has an incomplete name (location unknown)
```

According to the release note https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes#Kernel

> New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

The same issue probably happens for all other system libraries, e.g. `libc++.1.dylib`.

I am using 
```
$ cmake --version
cmake version 3.18.4
```

**Comment by andreamoro** [comment]
It seems to be a problem connected with the C compiler that Mac OS X (via XCode) has changed from libstdc++ to libc++.

By installing GCC (via HomeBrew) I get a different result, yet an error.

An extract of my installation log below:

```
Linking additional-components-plugin
ld: warning: dylib (/Users/andreamoro/homebrew/lib/libwx_osx_cocoau_richtext-3.0.dylib) was built for newer macOS version (11.0) than being linked (10.16)
ld: warning: dylib (/Users/andreamoro/homebrew/lib/libwx_osx_cocoau_propgrid-3.0.dylib) was built for newer macOS version (11.0) than being linked (10.16)
ld: warning: dylib (/Users/andreamoro/homebrew/lib/libwx_osx_cocoau_stc-3.0.dylib) was built for newer macOS version (11.0) than being linked (10.16)
ld: warning: dylib (/Users/andreamoro/homebrew/lib/libwx_osx_cocoau_ribbon-3.0.dylib) was built for newer macOS version (11.0) than being linked (10.16)
ld: warning: dylib (/Users/andreamoro/homebrew/lib/libwx_osx_cocoau_aui-3.0.dylib) was built for newer macOS version (11.0) than being linked (10.16)
ld: warning: dylib (/Users/andreamoro/homebrew/lib/libwx_osx_cocoau_xrc-3.0.dylib) was built for newer macOS version (11.0) than being linked (10.16)
ld: warning: dylib (/Users/andreamoro/homebrew/lib/libwx_osx_cocoau_media-3.0.dylib) was built for newer macOS version (11.0) than being linked (10.16)
....
```

Anybody has an idea?

**Comment by morty346** [comment]
any resolution to this? I am having the same issue

**Comment by sodevel** [comment]
Is this still an issue? Because according to #693 building seems to work on (recent) macOS Big Sur versions?

**Comment by b123400** [comment]
Not sure what was updated, but yes, it builds now. Closing the issue.
Thank you!
