### ISSUE TITLE
Can't install on Ubuntu 18.04

### ISSUE THREAD

**Issue by puposet** [wxFormBuilder/wxFormBuilder#658]
I have cloned the wxFormBuilder and followed the instructions for installation on Linux.

The command "ninja -C _build install" stops with message
`/usr/bin/ld: cannot find -lwx_gtk3u_media-3.1`
I note that it used the ld parameter `-L/usr/local/lib`

In /usr/local.lib there are various similar libs eg `libwx_gtk3u_core-3.1.so`. 
but not `wx_gtk3u_media-3.1.so`.  The same applies to the wxWidgets build target lib directory.

I'm on Ubuntu 18.04 (Bionic)
I have gtk 3.0 installed (libgtk-3.so.0.2200.30)
I have wxWidgets-3.1.4 built and installed.

I do not find any `wx_gtk3u_media-3.1` files on my system.

**Comment by sodevel** [comment]
Where did you get wxWidgets 3.1 from? I suppose it is self build. For some reason Meson seems to think the media library is present and tries to use it, or the Meson build definition is wrong (im not familiar with Meson and don't know if this optional dependency is configured right). Either try to get / build the media library as well or try to use the PreMake build system and forcefully exclude the media library from the build.

**Comment by puposet** [comment]
I downloaded the source from wxWidgets.org and followed the procedure laid out in wxWidgets-3.1.4/docs/gtk which did not appear to have any problems.  I guess I'll have to do some more research if I want to use it.  I'm not familiar with recent build systems.

**Comment by cowdingus** [comment]
My friend has the same problem. I don't know what his exact setup is, but he uses Ubuntu too, with the same error described by @puposet above. He followed the exact build tutorial in the README.md. I checked what version of `libwxgtk-media3.0-gtk3-dev` installed using `apt list libwxgtk-media3.0-gtk3-dev` and it says that he has `libwxgtk-media3.0-gtk3-dev/focal, now 3.0.4+dfsg-15build1 amd64 [installed]`. We've also checked the library files using `locate libwx_gtk3u | grep media` and it outputs
```
/usr/lib/x86_64-linux-gnu/libwx_gtk3u_media-3.0.so
/usr/lib/x86_64-linux-gnu/libwx_gtk3u_media-3.0.so.0
/usr/lib/x86_64-linux-gnu/libwx_gtk3u_media-3.0.so.0.4.0
```

**Comment by puposet** [comment]
I got something to work after much messing around. it looks like there was something wrong with the wxWidgets installation.  I have wxWidgets 3.0 runtime in use by other software, and I fear that downloading 3.1 in addition has confused the poor dear.  I tried uninstalled widgets 3.1 and reinstalled from the ubuntu ppa, but that only made things worse.  So I uninstalled it again, aiming to use 3.0 but meson was still trying to use 3..1 I found I had some residual 3.1 files, in particular 
`/usr/local/include/wx-3.1` which would be harmless if it were not for 
`/usr/local/bin/wx-config` symlinked to `usr/local/lib/wx/config/gtk3-unicode-3.1` 
The presence of the extra headers meant that instead of giving a "file not found" ninja tried to use the 3.1 headers and gave lots of code errors. 

Removing the link, deleting ~/wxFormBuilder/_build  and rerunning meson and ninja, then built a wxWidgets 3.0 version successfully.
Incidentally the media library missing from the widgets build is present in the ppa.  Possibly something to do with the comments in `wxWidgets-3.1.4/README-GIT.md`.

**Comment by puposet** [comment]
Forgot to mention, to get it running I also had to copy 
`~/wxFormBuilder/_install/lib/x86_64-linux-gnu/wxformbuilder` to 
`wxFormBuilder/_install/lib`
It had obviously installed it in the wrong place.

**Comment by ywiyogo** [comment]
I can confirm that the instruction to build the code on Ubuntu 21.04 doesn't work.

```
[56/67] Linking target wxformbuilder
FAILED: wxformbuilder 
c++  -o wxformbuilder wxformbuilder.p/src_codegen_codegen.cpp.o wxformbuilder.p/src_codegen_codeparser.cpp.o wxformbuilder.p/src_codegen_codewriter.cpp.o wxformbuilder.p/src_codegen_cppcg.cpp.o wxformbuilder.p/src_codegen_luacg.cpp.o wxformbuilder.p/src_codegen_phpcg.cpp.o wxformbuilder.p/src_codegen_pythoncg.cpp.o wxformbuilder.p/src_codegen_xrccg.cpp.o wxformbuilder.p/src_maingui.cpp.o wxformbuilder.p/src_md5_md5.cc.o wxformbuilder.p/src_model_database.cpp.o wxformbuilder.p/src_model_objectbase.cpp.o wxformbuilder.p/src_model_types.cpp.o wxformbuilder.p/src_model_xrcfilter.cpp.o wxformbuilder.p/src_rad_about.cpp.o wxformbuilder.p/src_rad_appdata.cpp.o wxformbuilder.p/src_rad_bitmaps.cpp.o wxformbuilder.p/src_rad_cmdproc.cpp.o wxformbuilder.p/src_rad_codeeditor_codeeditor.cpp.o wxformbuilder.p/src_rad_cpppanel_cpppanel.cpp.o wxformbuilder.p/src_rad_dataobject_dataobject.cpp.o wxformbuilder.p/src_rad_designer_innerframe.cpp.o wxformbuilder.p/src_rad_designer_menubar.cpp.o wxformbuilder.p/src_rad_designer_visualeditor.cpp.o wxformbuilder.p/src_rad_designer_visualobj.cpp.o wxformbuilder.p/src_rad_geninheritclass_geninhertclass_gui.cpp.o wxformbuilder.p/src_rad_geninheritclass_geninhertclass.cpp.o wxformbuilder.p/src_rad_inspector_objinspect.cpp.o wxformbuilder.p/src_rad_inspector_wxfbadvprops.cpp.o wxformbuilder.p/src_rad_luapanel_luapanel.cpp.o wxformbuilder.p/src_rad_mainframe.cpp.o wxformbuilder.p/src_rad_menueditor.cpp.o wxformbuilder.p/src_rad_objecttree_objecttree.cpp.o wxformbuilder.p/src_rad_palette.cpp.o wxformbuilder.p/src_rad_phppanel_phppanel.cpp.o wxformbuilder.p/src_rad_pythonpanel_pythonpanel.cpp.o wxformbuilder.p/src_rad_title.cpp.o wxformbuilder.p/src_rad_wxfbevent.cpp.o wxformbuilder.p/src_rad_wxfbmanager.cpp.o wxformbuilder.p/src_rad_xrcpanel_xrcpanel.cpp.o wxformbuilder.p/src_rad_xrcpreview_xrcpreview.cpp.o wxformbuilder.p/src_utils_annoyingdialog.cpp.o wxformbuilder.p/src_utils_filetocarray.cpp.o wxformbuilder.p/src_utils_stringutils.cpp.o wxformbuilder.p/src_utils_typeconv.cpp.o wxformbuilder.p/src_utils_wxfbipc.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,--start-group libplugin_interface.a subprojects/ticpp/libticpp.a -pthread -L/usr/lib/x86_64-linux-gnu -lwx_gtk3u_unofficial_stc-3.1 -lwx_gtk3u_unofficial_propgrid-3.1 -lwx_gtk3u_unofficial_aui-3.1 -lwx_gtk3u_unofficial_ribbon-3.1 -lwx_gtk3u_unofficial_richtext-3.1 -lwx_gtk3u_unofficial_xrc-3.1 -lwx_gtk3u_unofficial_html-3.1 -lwx_gtk3u_unofficial_qa-3.1 -lwx_gtk3u_unofficial_core-3.1 -lwx_baseu_unofficial_xml-3.1 -lwx_baseu_unofficial_net-3.1 -lwx_baseu_unofficial-3.1 -L/usr/lib/x86_64-linux-gnu -lwx_gtk3u_unofficial_media-3.1 -lwx_baseu_unofficial-3.1 -L/usr/lib/x86_64-linux-gnu -lwx_gtk3u_unofficial_stc-3.1 -lwx_gtk3u_unofficial_propgrid-3.1 -lwx_gtk3u_unofficial_aui-3.1 -lwx_gtk3u_unofficial_ribbon-3.1 -lwx_gtk3u_unofficial_richtext-3.1 -lwx_gtk3u_unofficial_xrc-3.1 -lwx_gtk3u_unofficial_html-3.1 -lwx_gtk3u_unofficial_qa-3.1 -lwx_gtk3u_unofficial_core-3.1 -lwx_baseu_unofficial_xml-3.1 -lwx_baseu_unofficial_net-3.1 -lwx_baseu_unofficial-3.1 -L/usr/lib/x86_64-linux-gnu -lwx_gtk3u_unofficial_media-3.1 -lwx_baseu_unofficial-3.1 -Wl,--end-group
/usr/bin/ld: cannot find -lwx_gtk3u_unofficial_media-3.1
/usr/bin/ld: cannot find -lwx_gtk3u_unofficial_media-3.1
collect2: error: ld returned 1 exit status
[61/67] Compiling C++ object libadditional.so.p/plugins_additional_additional.cpp.o
ninja: build stopped: subcommand failed.
```
I even installed the package libwxgtk3.1unofficial-dev. It still doesn't work.

**Comment by sodevel** [comment]
> ```
> /usr/bin/ld: cannot find -lwx_gtk3u_unofficial_media-3.1
> ```
> 
> I even installed the package libwxgtk3.1unofficial-dev. It still doesn't work.

But you did not install the media library like the install instructions mention.

**Comment by ywiyogo** [comment]
> But you did not install the media library like the install instructions mention.

Which media library did you refer to? I installed by executing `sudo apt install libwxgtk3.0-gtk3-dev libwxgtk-media3.0-gtk3-dev meson`. There error shows `-lwx_gtk3u_unofficial_media-3.1` and I cannot find a package named `libwxgtk3.1-0-unofficial-media` on Ubuntu 20-04.

**Comment by sodevel** [comment]
Apparently you have at least two different wxWidgets versions installed, one 3.0.x version and one 3.1.x version. The error message shows that meson picks up the 3.1.x version and its media library is missing. I don't know how Ubuntu names the packages, you have search for yourself to find the proper name.
