### ISSUE TITLE
ninja -C _build install error

### ISSUE THREAD

**Issue by Jajv** [wxFormBuilder/wxFormBuilder#663]
Bear with me, I'm new to this and might be missing something obvious.
On Linux Mint 19 (gcc 7.5.0, wxWidgets 3.0.5 in default installation) when running "ninja -C _build install" got some linking errors:

[1/8] Linking target libforms.so.
FAILED: libforms.so 
...
/usr/bin/ld: cannot find -lwx_gtk2u_media-3.0
collect2: error: ld returned 1 exit status

Similar error appears 4 more times and then i got this compile error:

[6/8] Compiling C++ object 'additional.../plugins_additional_additional.cpp.o'.
FAILED: additional@sha/plugins_additional_additional.cpp.o 
...
'additional@sha/plugins_additional_additional.cpp.o' -MF 'additional@sha/plugins_additional_additional.cpp.o.d' -o 'additional@sha/plugins_additional_additional.cpp.o' -c ../plugins/additional/additional.cpp
../plugins/additional/additional.cpp: In member function ‘virtual wxObject* MediaCtrlComponent::Create(IObject*, wxObject*)’:
../plugins/additional/additional.cpp:1539:3: error: ‘wxMediaCtrl’ was not declared in this scope
   wxMediaCtrl* mc = new wxMediaCtrl((wxWindow *)parent, wxID_ANY, wxT(""),obj->GetPropertyAsPoint(_("pos")),
   ^~~~~~~~~~~
../plugins/additional/additional.cpp:1539:3: note: suggested alternative: ‘wxSpinCtrl’
   wxMediaCtrl* mc = new wxMediaCtrl((wxWindow *)parent, wxID_ANY, wxT(""),obj->GetPropertyAsPoint(_("pos")),
   ^~~~~~~~~~~
   wxSpinCtrl
... and some more...
ninja: build stopped: subcommand failed.

Whole output is attached here:
[error.txt](https://github.com/wxFormBuilder/wxFormBuilder/files/6003273/error.txt)

**Comment by sodevel** [comment]
Looks like the media library is not present on your system but meson thinks it is. Check if it's present and try to install it if its missing. Also see #658.

**Comment by Jajv** [comment]
I tried to check, it seems that the library in version 3.0 is present. Also there is no problem with the wrong symlink config as mentioned in the #658 issue. I am also not aware nor have I found any previous version of wxWidgets present on the system. However I have installed version 3.0.5 which was marked as stable instead of 3.1.4 version mentioned in that issue.
