### ISSUE TITLE
wxSimplebook written as "unknown" class to XRC.

### ISSUE THREAD

**Issue by OmniBlade** [wxFormBuilder/wxFormBuilder#666]
Using XRC generation, a wxSimplebook control is written as an "unknown" class rather than "wxSimplebook.

I get the following as an example:
`<object class="unknown" name="m_parameterBook" />`

This means more unnecessary work to either fix the generated XRC or to load the controls correctly from "unknown".

This could of course be something I'm doing wrong, but I'm not quite sure what it could be. I've tested this on a snapshot build of master as well, not just the release builds.

**Comment by OmniBlade** [comment]
Further to this, wxSimplebook is also not recognised when importing an xrc either.

**Comment by sodevel** [comment]
This is because XRC import and export is not implemented in ``plugins/containers/container.cpp`` for wxSimplebook.
