### ISSUE TITLE
wxMediaCtrl define

### ISSUE THREAD

**Issue by redtide** [wxFormBuilder/wxFormBuilder#671]
Does anybody reminds why a custom `USE_MEDIACTRL` define was used  by disabling the control manually in the build scripts instead [wxUSE_MEDIACTRL](https://github.com/wxWidgets/wxWidgets/blob/master/src/common/mediactrlcmn.cpp#L24)? I only suppose there was some issue with wxWidgets, otherwise there shouldn't be the need of it.

**Comment by sodevel** [comment]
MacOS had? and MSYS2 still has problems with wxMediaCtrl, thats why there is an option to disable it. If you would rely on wxUSE_MEDIACTRL you could not disable it by yourself but have to rely on the configuration of wxWidgets. I don't know if current wxWidgets of MSYS2 does define that symbol and does not work, i do MSVC builds only myself and simply did not investigate this.

**Comment by redtide** [comment]
I recall there was a reason, but it's difficult to remind the details after 10 years, I don't even recall if it was me to add it in the premake4 scripts 😄 Meanwhile I found that in the MSYS2 MinGW wx libs the media library is included, but it seems there is about nothing in the `wx-config` script about it. I let this open if OK, I'll close if no other ideas or if we'll get something to document.
