### ISSUE TITLE
Bug about wxTimer

### ISSUE THREAD

**Issue by Puiching-Memory** [wxFormBuilder/wxFormBuilder#692]
wxtimer has an optional property called 'oneshot'
But when I select it, it doesn't work properly
The code generated automatically by software is as follows:

self.T_Check = wx.Timer()
self.T_Check.SetOwner( self, wx.ID_ANY )
self.T_Check.Start( 1000, true )

Where 'true' should be 'True'
This small flaw caused my code to return such a report in vscode:

self.T_Check.Start( 1000, true )   
NameError: name 'true' is not defined

This bug comes from wxFormBuilder 3.9.0
I don't know if this problem has been solved in the later version update

**Comment by sodevel** [comment]
No, the problem is not solved yet, but it is easy to solve, just one character needs to be changed in the code template :smile:
