### ISSUE TITLE
Binding events in Chinese will be garbled

### ISSUE THREAD

**Issue by YangZhengXun** [wxFormBuilder/wxFormBuilder#708]
![11](https://user-images.githubusercontent.com/53441499/139408637-7409a43a-850a-4820-8c16-b033cb6defa9.png)

**Comment by sodevel** [comment]
Strange, this seems to affect the connect calls only, as can be seen in your screenshot, the actual method definition does work. Anyway, this is not such a big issue, it looks like Python does not allow chinese characters for identifiers anyway, so you can't use such names for event handler methods :wink:.

**Comment by YangZhengXun** [comment]
> Strange, this seems to affect the connect calls only, as can be seen in your screenshot, the actual method definition does work. Anyway, this is not such a big issue, it looks like Python does not allow chinese characters for identifiers anyway, so you can't use such names for event handler methods 😉.

Python should allow the use of Chinese. I manually correct the garbled code, it can be used normally! Because my English is not very good, so I still hope to use Chinese.

![00](https://user-images.githubusercontent.com/53441499/139520329-c80a21f5-8344-4ab2-9b78-cbc3aa61149a.png)
![01](https://user-images.githubusercontent.com/53441499/139520331-fa293e8a-7823-41f5-8c7b-bf50e195a2d9.png)

**Comment by sodevel** [comment]
Looks like i was wrong. Granted, i don't know any Python and the first Google results said you can only use a subset of ASCII for identifiers. Maybe some part of wxFB also assumes that, it looks like an encoding conversion error. This will be either easy to fix or will take ages to find the location doing this.
