### ISSUE TITLE
wxTextCtrl add  drag file name 

### ISSUE THREAD

**Issue by wannianhong** [wxFormBuilder/wxFormBuilder#712]
We often need to put the file name in the wxTextCtrl box 
wxTextCtrl need add property：SetDropTarget

code:
```
#pragma once
#include <wx/dnd.h>
#include <wx/textctrl.h>
#include <wx/arrstr.h>

 */
class CopyFilename : public wxFileDropTarget
{
private:
    wxTextCtrl* m_text;
public:
    CopyFilename(wxTextCtrl* text);
    virtual bool OnDropFiles(wxCoord x, wxCoord y, const wxArrayString& filenames);
    ~CopyFilename();
};
#include "CopyFilename.h"
CopyFilename::CopyFilename(wxTextCtrl* text) 
{
    m_text = text;
}

bool CopyFilename::OnDropFiles(wxCoord x, wxCoord y, const wxArrayString& filenames) 
{
    size_t nFiles = filenames.GetCount();
    wxString str;
    str.Printf(wxT("%d files dropped"), (int)nFiles);
    for (size_t n = 0; n < nFiles; n++) {
        m_text->AppendText(filenames[n]);
    }
    return true;
}
CopyFilename::~CopyFilename() {}

```

**Comment by sodevel** [comment]
I'm sorry, but i'm afraid i don't understand the issue / request here.

**Comment by wannianhong** [comment]
wxTextCtrl need add property：SetDropTarget
example:
m_obf_textCtrl->SetDropTarget(new CopyFilename(m_obf_textCtrl));

add SetDropTarget

**Comment by wannianhong** [comment]
<img width="670" alt="edit" src="https://user-images.githubusercontent.com/59216544/147848846-915e5ac5-f342-4e64-a888-456919dd62b9.PNG">

**Comment by wannianhong** [comment]
<img width="390" alt="e1" src="https://user-images.githubusercontent.com/59216544/147848866-fca3d05a-65ce-4b25-98dc-d6bbb111631a.PNG">
i can add property，but i don't know add new class CopyFilename

**Comment by sodevel** [comment]
To keep the conversation in one place, i will answer in the linked PR.
