### ISSUE TITLE
Upgrading old project loses wxFONTWEIGHT_BOLD property on wxStaticText

### ISSUE THREAD

**Issue by CarSim-bporter** [wxFormBuilder/wxFormBuilder#713]
When upgrading a project from version "Oct 26 2018" to 3.10.1-0-g8feb16b3, all wxStaticText fields that were set to use wxFONTWEIGHT_BOLD were changed to wxFONTWEIGHT_NORMAL.
The conversion was initiated by opening the old *.fbp file with the latest (as of 2022-01-03) release version of wxFormBuilder.

**Comment by sodevel** [comment]
I can confirm this issue. The tricky part is, this is not caused directly by wxFB. wxFB stores the binary value of these symbols in the project file, but the binary value of these symbols has changed in wxWidgets 3.1.2. So depending on which wxWidgets version wxFB is compiled against, a different value is stored in the project file. Even today wxFB can be compiled against wxWidgets 3.0.x (and the Ubuntu releases are).

Thanks for reporting this.
