### ISSUE TITLE
Linux setup command incorrect

### ISSUE THREAD

**Issue by trevorhauter** [wxFormBuilder/wxFormBuilder#721]
Two of the commands under the [linux setup](https://github.com/wxFormBuilder/wxFormBuilder) is incorrect/outdated.

```
cmake -S . -B _build -G "Unix Makefiles" --install-prefix "$PWD/_install" -DCMAKE_BUILD_TYPE=Release -DWXFB_WXWIDGETS_ENABLE_30=ON
```
Should be 
```
cmake -S . -B _build -G "Unix Makefiles" --install-prefix "$PWD" -DCMAKE_BUILD_TYPE=Release -DWXFB_WXWIDGETS_ENABLE_30=ON
```

And
`_install/bin/wxformbuilder`

should just be `./bin/wxformbuilder`

That's all I had to fix to be able to build wxformbuilder on 64 bit Ubuntu 20.04.3 LTS.

**Comment by sodevel** [comment]
The commands are just fine, installing into $PWD pollutes the source tree with fragments of the install tree and is a bad idea. What errors do you get when building with that directory?

**Comment by trevorhauter** [comment]
When running the first command I mentioned, I get this. But if I run my suggested command, it works. 
```
cmake -S . -B _build -G "Unix Makefiles" --install-prefix "$PWD/_install" -DCMAKE_BUILD_TYPE=Release -DWXFB_WXWIDGETS_ENABLE_30=ON

CMake Error: The source directory "/home/trevor/wxFormBuilder/_install" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```

I suppose I don't mean to make a prescription as to what should or shouldn't be done in regards to best practice, I more meant that the suggested command didn't work but this did, and assumed it was an issue with the command

**Comment by sodevel** [comment]
This sounds somewhat familiar but if it is, what i think it is, im surprised it works at all. What is the output of `cmake --version`?

**Comment by trevorhauter** [comment]
Oh! I completely forgot to mention that. I'm using `cmake version 3.22.1`. I wasn't able to use the version of cmake I had (I think 3.16) and I was forced to upgrade it to work. Sorry, I had did the set up and made a note to mention it to you guys after the fact, so I had forgotten to mention a few details.

**Comment by sodevel** [comment]
Hmm, thats strange. Older CMake versions do not have the `--install-prefix` command line option and produce some very strange error messages if it is used. Your solution doesn't make sense together with the error message, it complains about an invalid source directory but you modify the install directory, why should that fix the reported error?

I have no explanation for this, maybe as a workaround you could omit `--install-prefix` from the build command and specify the prefix on the install command directly instead.
