### ISSUE TITLE
Please add library support for wx.html2!

### ISSUE THREAD

**Issue by Puiching-Memory** [wxFormBuilder/wxFormBuilder#722]
https://docs.wxpython.org/wx.html2.1moduleindex.html?highlight=html2#module-wx.html2

It seems that wx.html2 already has complete functional documentation.
However, it is still not supported in the latest wxformbuilder release.

**Comment by wannianhong** [comment]
you can use wxHtmlWindow，
but you need add property ，LoadPage or LoadFile
example ：
https://github.com/wxFormBuilder/wxFormBuilder/pull/719
