### ISSUE TITLE
enum for ID

### ISSUE THREAD

**Issue by Sayori1576** [wxFormBuilder/wxFormBuilder#725]
Now, wxformbuilder uses #define id setting. but using of enum will be much cleaner.
example:
enum 
{
wxButton_id=wxID_HIGHEST+1,
wxtextctrl_id,
};

**Comment by SpareSimian** [comment]
Click on the project (top-level node in the tree), look at the project properties in the right-most pane, down where it says C++ Properties. The first option is the checkbox use_enum. Check that.

**Comment by Sayori1576** [comment]
Oh, it was already there. sorry.
