### ISSUE TITLE
Building on Fedora fails

### ISSUE THREAD

**Issue by FlanOfHarmony** [wxFormBuilder/wxFormBuilder#735]
I've followed the instructions in the readme, but the line `cmake -S . -B _build -G "Unix Makefiles" --install-prefix "$PWD/_install" -DCMAKE_BUILD_TYPE=Release` gives the following error:
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS) (Required is at least version "3.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindwxWidgets.cmake:1025 (find_package_handle_standard_args)
  CMakeLists.txt:140 (find_package)
```

(I'm using Cmake 3.22.2).
A workaround is to install `wxGTK-devel`, so I guess it should be added in the list of prerequisites?

**Comment by sodevel** [comment]
Indeed, the devel package should be listed there. Thanks for spotting this, i will push an update later today.
