### ISSUE TITLE
Why Cento 7 flatpak install failed?

### ISSUE THREAD

**Issue by wahello** [wxFormBuilder/wxFormBuilder#744]
I downloaded wxFormBuilder from this [release](https://github.com/wxFormBuilder/wxFormBuilder/releases/download/v3.10.1/wxFormBuilder-3.10.1-x86_64.flatpak), and copy it to my computer with centos 7.9 installed, which is offline.
Then install it via terminal by
` flatpak install  --bundle   wxFormBuilder-3.10.1-x86_64.flatpak`
Error raised with tip: 
`error: Can't load dependent file https://flathub.org/repo/flathub.flatpakrepoError resolving “flathub.org”: Name or service not known`
Why?

**Comment by sodevel** [comment]
Because
> which is offline

The required flatpak runtime is missing on your computer and its download fails because of the above reason.
