### ISSUE TITLE
DataView column, incorrect constant in Python

### ISSUE THREAD

**Issue by Conkey100** [wxFormBuilder/wxFormBuilder#748]
Adding a column to a DataView control, the constant for editable mode is incorrect in Python.  It is "wx.DATAVIEW_CELL_EDITABLE", it should be "wx.dataview.DATAVIEW_CELL_EDITABLE". Activatable and inert modes are both correct. Below is an example of the generated output for all 3 modes.

        self.col1 = self.dvc.AppendToggleColumn( u"X", 0, wx.DATAVIEW_CELL_EDITABLE, -1, wx.ALIGN_CENTER, wx.dataview.DATAVIEW_COL_RESIZABLE )
        self.col2 = self.dvc.AppendTextColumn( u"#", 0, wx.dataview.DATAVIEW_CELL_ACTIVATABLE, -1, wx.ALIGN_RIGHT, wx.dataview.DATAVIEW_COL_RESIZABLE )
        self.col3 = self.dvc.AppendTextColumn( u"Date", 0, wx.dataview.DATAVIEW_CELL_INERT, -1, wx.ALIGN_RIGHT, wx.dataview.DATAVIEW_COL_RESIZABLE )

**Comment by sodevel** [comment]
This has already been fixed in df7791bf6a9441a6b5af408dba250f97fbdd02c9.
