### ISSUE TITLE
Bitmap relative path

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#75]
Migrating this bug from the old bug tracker.

I have my source located in a directory called "Source", my final executable builds to a directory called "Bin", and images are found in "Bin/Data/Images"; this means that any paths in the automatically generated code look like "../Bin/Data/Icons/" due to it exporting the paths relative to the code export location.

This actually works ok providing that the executable is ALWAYS in a directory called "Bin", my suggestion would have been to have two paths, one for where you wanted the exported code to be sent (in my case "Source"), and another for your executables working directory (in my case "Bin"),

Then the exported code could use wxTheApp-&gt;GetPath() followed by the image location relative to the working directory set.

Example:
working path = Bin/
image path = Bin/Data/Images/add.png
Exported code: wxTheApp-&gt;GetPath() + wxT("/Data/Images/add.png")

Reported by: *anonymous

**Comment by jhasse** [comment]
Fixed by #496.
