### ISSUE TITLE
release new version with wxWidgets version 3.2 

### ISSUE THREAD

**Issue by sdwarwick** [wxFormBuilder/wxFormBuilder#753]
the current version of this system is now a year old - how about doing an updated release with wxWidgets set to default to current stable version of 3.2 - that's now updated to use Gtk 3/4 as well..

**Comment by sodevel** [comment]
Is there any benefit to build against wxWidgets 3.2 right now? Is this version available on platforms where it would be a benefit (looking at you, Ubuntu :smile:)? There are a bunch of WIP features i wanted to finish first, but i'm quite short on time right now, so this will still take some time. I don't see an urgent need to make a release in the near future.

**Comment by ericwomer** [comment]
@sdwarwick Just build wxWidgets and wxForm from source.  Just install the dependencies before building wxWidgets

```
sudo apt-get install libsecret-1-dev libnotify-dev libcurl4-openssl-dev libwebkit2gtk-4.0-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libgstreamer-plugins-base1.0-dev libboost1.74-dev
```

boost is for wxForms the rest are for other parts of wxWidgets, you may or may not need them, depending on what you do with it.

**Comment by virtmax** [comment]
Hi,
how about a new release? The last version for Windows is almost 2 years old. Looks like unmaintained for people who just want to try it out. 
Would be really nice :)

**Comment by sodevel** [comment]
I know, the current situation is rather unfortunate. Most work i did in the last two years was improving the build system and improving the shape of the project to simplify to work on it, escpecially for external contributors. This includes the replacement of dead external dependencies with maintained ones. All this results in severe breaking of current API and ABI which would justify a new major release.

However, the user visible changes are not that huge, so releasing a new major release might lead to some disappointments. So i wanted to wait with a new release until there are more user visible changes, i wanted to add some new features that are very useful for my own use cases.

Sadly, i can't devote so much time to this project currently. There are also some serious flaws and bugs that need to be fixed first, and regarding my past work in this project, i'm afraid that will take quite some time to accomplish. So right now im quite unsure what to do.

**Comment by Kvaz1r** [comment]
> I know, the current situation is rather unfortunate. Most work i did in the last two years was improving the build system and improving the shape of the project to simplify to work on it, escpecially for external contributors. This includes the replacement of dead external dependencies with maintained ones. All this results in severe breaking of current API and ABI which would justify a new major release.
> 
> However, the user visible changes are not that huge, so releasing a new major release might lead to some disappointments. So i wanted to wait with a new release until there are more user visible changes, i wanted to add some new features that are very useful for my own use cases.
> 
> Sadly, i can't devote so much time to this project currently. There are also some serious flaws and bugs that need to be fixed first, and regarding my past work in this project, i'm afraid that will take quite some time to accomplish. So right now im quite unsure what to do.


I think that users are much more disappointed that project long time don't have new release than any amount of new features in any possible new release.

**Comment by sodevel** [comment]
The v4.0.0 GitHub CI builds use wxWidgets 3.2.x now (except the Ubuntu builds because the used distributions are too old).
