### ISSUE TITLE
Hope to increase the support of Chinese translation（中文版本）

### ISSUE THREAD

**Issue by BunnySakura** [wxFormBuilder/wxFormBuilder#756]
- **English**
  Since my English is not very good, so I tried to modify the source code to recompile a Chinese interface package.
  
  But I have found that there does not seem to be a good way to achieve this goal.
  
  So what can I do to get a Chinese version of the interface🤣, I hope to get your help, thank you!

- **中文**
  介于我的英语不算很好，所以我试图修改源代码重新编译一个中文界面的包。
  
  但是我发现似乎并没有一个较好的方法可以实现这个目标。
  
  所以我该如何做才能得到一个中文界面的版本🤣，希望得到诸位的帮助，谢谢！

**Comment by sodevel** [comment]
As i already said in https://github.com/wxFormBuilder/wxFormBuilder/issues/727#issuecomment-1046115911, localization is a complex task and not easy to do.

Basically, localization can be split into two parts:
1. Localize the application itself
2. Localize the contents of the XML files

The application uses wxWidgets and this uses gettext for localization. Basically, you have to mark the strings which should get translated with the `_()` macro, run with gettext over the source files to create a POT file and use that to create PO files for each desired language. The PO files need to get compiled into MO files and the application must load these files during startup, the rest works automatically. The biggest problem here is, the application uses the `_()` macro wrong. Currently, basically all strings that should NOT be translated are marked for translation while all strings, that should be translated, are not marked.

For the XML files, you can also use gettext to extract the strings that should be translated, however gettext cannot do this out of the box. I forgot how that feature is called, but basically you write a configuration file that contains XPATH expressions to match the elements of the XML file that should be translated. You will end up with POT files that need to be processed like above. The remaining steps are more complicated, the application must be changed to load the MO files for each plugin and the code reading the XML files must be adapted to not use the strings directly but call the translation function on them.

Additionally, at least the MO files must be installed during the installation phase. It would also be nice to have some CMake utility targets to actually update the POT files and to compile the PO files into MO files.

**Comment by BunnySakura** [comment]
Well, that looks like trouble. Fortunately, after a period of time has been some of the basis for the use of it, so for now, thank you very much!
好吧，看起来很麻烦。好在经过一段时间使用已经有些基础了，目前先这样吧，非常感谢！

**Comment by stockstock2006** [comment]
Try to use GBK2312
