### ISSUE TITLE
app crashes on new form with 'BadMatch' X error in kubuntu 9

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#76]
What steps will reproduce the problem?

Install wxFormBuilder on Kubuntu 9.10 from repository.
Run wxFormBuilder.
Navigate to FORMS tab and select any of the three form types.
What is the expected output? What do you see instead?

wxFormBuilder immediately crashes regardless of weather the project is saved prior to creating a form or no.  Here are the last few lines of strace including the output error message:
poll([{fd=10, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=10, revents=POLLOUT}]) writev(10, [{”\22\0\7\0\376\5\300\2\366\0\0\0!\0\0\0 \4\7\0\1\0\0\0\1\0\300\2\22 \0\7\0”..., 3256}, {NULL, 0}, {”“, 0}], 3) = 3256 poll([{fd=10, events=POLLIN}], 1, -1) = 1 ([{fd=10, revents=POLLIN}]) read(10, “\34\322\347C\376\5\300\2\22\1\0\0\340&lt;d\27\0\212\270\17\0\0\0\0\20\300 \304\2\0\0\0\0”..., 4096) = 544 open(”/usr/share/X11/XErrorDB”, O_RDONLY) = 11 fstat(11, {st_mode=S_IFREG|0644, st_size=41481, ...}) = 0 brk(0x1dd1000) = 0x1dd1000 read(11, “! $Xorg: XErrorDB,v 1.3 2000/08/”..., 41481) = 41481 close(11) = 0 brk(0x1df2000) = 0x1df2000 write(2, “The program ‘wxformbuilder’ rece”..., 575The program ‘wxformbuilder’ r eceived an X Window System error. This probably reflects a bug in the program. The error was ‘BadMatch (invalid parameter attributes)’.

(Details: serial 17417 error_code 8 request_code 151 minor_code 5)
(Note to programmers: normally, X errors are reported asynchronously;
that is, you will receive the error a while after causing it.
To debug your program, run it with the --sync command line
option to change this behavior. You can then get a meaningful
backtrace from your debugger if you break on the gdk_x_error() function.)
) = 575 exit_group(1) = ?

No errors were found in the syslog or the Xorg.0.log. Attached is the xorg.conf for this system. It’s a triple head setup using dual NVIDIA cards and so is using xinerama rather than Xrandr which remains incapable of true triplehead support. All drivers were installed via standard kubuntu repositories. All software on the system was installed from the standard and backports repos with the exception of the chromium browser from http://ppa.launchpad.net/chromium-daily/ppa/ubuntu. At this point wxFormBuilder is unusable as it crashes immediately upon creating a new form.

Please use labels and text to provide additional information.

Reported by: jfouche

**Comment by jhasse** [comment]
Please reopen if someone can sill reproduce this (I can't with 2 monitors).
