### ISSUE TITLE
Add multiple elements to AUI pane?

### ISSUE THREAD

**Issue by Allan-S-Menefee** [wxFormBuilder/wxFormBuilder#773]
I would like to have a floating wxPanel which contains different types of basic elements - like radio buttons, labels, and entry fields, but I can't find a way to do that. I've had trouble determining if this is an AUI limitation, a wxFormBuilder limitation, or a lack of understanding. 

If I attempt to create in a wxPanel (or any other container?) they become independent elements in the parent wxFrame, and cannot be 'nested' into the wxPanel. If I manually edit the generated code and make the elements children of the wxPanel, those elements appear inside the wxPanel and it can be docked as usual. I also attempted to nest them in the XML with no success - wxFormBuilder opened the file but ignored the nested element.

**Comment by sodevel** [comment]
To add elements into a non-AUI-managed container, you have to add a sizer first. Then you can add the child elements into that sizer.

**Comment by sodevel** [comment]
Closing this as resolved
