### ISSUE TITLE
Add images relative to wxTheApp->GetPath()

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#78]
I have a problem with the files loaded from relative paths and bitmap buttons/images.

Imagine this situation:

\- You create a new dialog in wxFB. You place a bitmap button with an image “./MyImage.png”. You create the .H.

\- In your application, you use the .H created by wxFB.

\- Then, the application asks the user to select a file using a wxFileDialog call. The current folder changes...

\- Now, I open the wxFB dialog using the “./MyImage.png”... and voilá! A file not found assert is fired... That’s because the current folder changed and, like I specified a “./MyImage.png” as bitmap button’s icon then the error appears correctly...

SOLUTION: Add an option in wxFB to use relative-to-application image paths. For example, I could specify for the bitmap button created in wxFB a path like “{AppPath}/MyImage.png”. Then, the dialog’s constructor on your wxFB .CPP output can call something like

this-&gt;MyButton-&gt;SetIcon(wxTheApp-&gt;GetPath()+wxT("/MyImage.png"));
Thanks.

Reported by: jfouche

**Comment by jhasse** [comment]
Fixed by #496.
