### ISSUE TITLE
BitmapComboBox produces incorrect choice parameter type for python

### ISSUE THREAD

**Issue by int-bio** [wxFormBuilder/wxFormBuilder#783]
When creating a BitmapComboBox, the choices parameter has an incorrect type.  It should be an empty list, not a str.

formbuilder 3.10.0 prodcues the following code for python:
 `self.m_bcomboBox_chamber = wx.adv.BitmapComboBox( self.m_panel_primary, wx.ID_ANY, u"------", wx.DefaultPosition, wx.DefaultSize, "", wx.CB_READONLY )`

When running the code on python 3.8.10 (wxpython 4.2.0) I get:
`  File "C:\Projects\work_area\frame.py", line 151, in __init__
self.m_bcomboBox_chamber = wx.adv.BitmapComboBox( self.m_panel_primary, wx.ID_ANY, u"------", wx.DefaultPosition, wx.DefaultSize, "", wx.CB_READONLY )`

`TypeError: BitmapComboBox(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 6 has unexpected type 'str'
`

[wxpython](https://docs.wxpython.org/wx.adv.BitmapComboBox.html ) indicates the correct type should be 
 `self.m_bcomboBox_chamber = wx.adv.BitmapComboBox( self.m_panel_primary, wx.ID_ANY, u"------", wx.DefaultPosition, wx.DefaultSize, [], wx.CB_READONLY )`

**Comment by sodevel** [comment]
I just pushed a commit that should fix this issue. However, i don't know any Python nor can i test the generated code, maybe you can verify that this change is correct.

**Comment by int-bio** [comment]
Thank you.  I will check it out this week.

**Comment by sodevel** [comment]
I assume this is fixed, otherwise reopen this issue again.
