### ISSUE TITLE
Windows executables bundled with Linux source tarballs

### ISSUE THREAD

**Issue by melizasw** [wxFormBuilder/wxFormBuilder#787]
Please exclude the following Windows executables from the  wxFormBuilder-<VERSION>-source-full.tar.gz tarball:
scripts/premake/4.3/bin/release/premake4.exe
scripts/premake/5.0/bin/release/premake5.exe

The Debian packaging tool "Lintian" does not like to see these and produces the following warning:
```
W: wxformbuilder source: source-contains-prebuilt-windows-binary [scripts/premake/4.3/bin/release/premake4.exe]
N: 
N:   The source tarball contains a prebuilt binary for Microsoft Windows. They
N:   are usually provided for the convenience of users. These files usually
N:   just take up space in the tarball.
N:   
N:   However, they may be a DFSG violation in that the corresponding source and
N:   build system are not available.
N:   
N:   Check if upstream also provides source-only tarballs that you can use as
N:   the upstream distribution instead. If not, you may want to ask upstream to
N:   provide source-only tarballs.
```

**Comment by sodevel** [comment]
The Premake build system has been removed shortly after the last release, there shouldn't be any binaries left in the repository. This issue shouldn't occur anymore.

**Comment by melizasw** [comment]
Thanks for letting me know. Hopefully wxFormBuilder will be in Debian soon and then in Ubuntu and its derivatives in 24.04.
