### ISSUE TITLE
Python call to super() for each class??

### ISSUE THREAD

**Issue by tester0077** [wxFormBuilder/wxFormBuilder#794]
since I am using wxFB to create the GUI for my wxPython app, I am wondering if there should be a call to super() as part of __init__
As it is, I am very new to Python and am unsure just how important this call would be for such apps and if it is important whether it would be possible to add such support to wxFB or possibly point me to a way to work around it

**Comment by sodevel** [comment]
Zero Python knowledge on my side so you preferrably ask this in the wxPython community.

**Comment by lebao3105** [comment]
`super()` calls the original class (superclass) that your widget is using (e.g wxNotebook).

And, `super().__init__(*args, **kwds)` as the first line of the derived `__init__` function is needed anyway, for the widget to setup properly.

But you can also use:

`python
wxNotebook.__init__(self, *args, **kwds)
`

Where wxNotebook is the superclass (the one to be inherited). You can see that the first argument of the `__init__` function is `self`, the instance of the subclass.

This is may not really clear for you, if so please go learn about deriving classes properly.
