### ISSUE TITLE
Values for AUI best & min size are not output to code files

### ISSUE THREAD

**Issue by tester0077** [wxFormBuilder/wxFormBuilder#795]
As part of my issues with adding a stretch spacer to a GUI's AUI tool bar, I have concluded, that the AUI properties for at least min & best size are not added to the output for at least C++ & Python when the respective code is generated, although the appearance in the designer seems to take them into account.
My generated python code (from the curent version of wxFB) for this tool bar is:
```
self.m_auiToolBarSpacer = wx.aui.AuiToolBar( self, wx.ID_TB_SPACER, wx.DefaultPosition, wx.DefaultSize, wx.aui.AUI_TB_HORZ_LAYOUT )
        self.m_staticText1 = wx.StaticText( self.m_auiToolBarSpacer, wx.ID_ANY, _(u"wwwwwww"), wx.DefaultPosition, wx.DefaultSize, 0 )
        self.m_staticText1.SetLabelMarkup( _(u"wwwwwww") )
        self.m_staticText1.Wrap( -1 )

        self.m_auiToolBarSpacer.AddControl( self.m_staticText1 )
        self.m_auiToolBarSpacer.Realize()
        self.m_mgr.AddPane( self.m_auiToolBarSpacer, wx.aui.AuiPaneInfo().Name( u"spacer" ).Top().CaptionVisible( False ).CloseButton( False ).PaneBorder( False ).Movable( False ).Dock().Resizable().FloatingSize( wx.DefaultSize ).DockFixed( True ).BottomDockable( False ).TopDockable( False ).LeftDockable( False ).RightDockable( False ).Floatable( False ).Position( 4 ).Layer( 10 ).ToolbarPane() )
```
the corresponding C++ code:
```
m_auiToolBarSpacer = new wxAuiToolBar( this, wxID_TB_SPACER, wxDefaultPosition, wxDefaultSize, wxAUI_TB_HORZ_LAYOUT );
	m_staticText1 = new wxStaticText( m_auiToolBarSpacer, wxID_ANY, _("wwwwwww"), wxDefaultPosition, wxDefaultSize, 0 );
	m_staticText1->SetLabelMarkup( _("wwwwwww") );
	m_staticText1->Wrap( -1 );
	m_auiToolBarSpacer->AddControl( m_staticText1 );
	m_auiToolBarSpacer->Realize();
	m_mgr.AddPane( m_auiToolBarSpacer, wxAuiPaneInfo().Name( wxT("spacer") ).Top().CaptionVisible( false ).CloseButton( false ).PaneBorder( false ).Movable( false ).Dock().Resizable().FloatingSize( wxDefaultSize ).DockFixed( true ).BottomDockable( false ).TopDockable( false ).LeftDockable( false ).RightDockable( false ).Floatable( false ).Position( 4 ).Layer( 10 ).ToolbarPane() );
```
For a similar layout, wxCrafter adds something like _MinSize(20,20).MaxSize(100,100)_  to the line containing`![ScreenshotwxFbSizes](https://github.com/wxFormBuilder/wxFormBuilder/assets/9053628/914165d1-576c-49bb-91de-0383f09afe48)`

If I add the equivalent code to the wxFB generated Python code, the app's GUI looks a bit more like what I would expect. It naturally is not completely as I want it because I have only added the extra code to one tool bar panel for these tests

**Comment by sodevel** [comment]
Apparently wxToolBar and wxAuiToolbar have their own code templates to add the pane information in AUI mode and these templates are broken. Therefor, only these two classes are affected, other widgets work correctly. I'll try to fix this soon, thanks for reporting.

**Comment by tester0077** [comment]
Since I now have a workable test bed, I'd be very interested in help to fix this issue, if you need a tester.
It is not really a show stopper for me, but important enough to be worth some effort :-)

**Comment by tester0077** [comment]
Thank you for both the quick response as well as maintaining this app.
I have been able to compile the latest & updated version with success and as far as I can tell at this time, the issue is corrected.
FWIW, when compiling the release versions under MSVC 2022 & with wxWidgets 3.2.2, I get a memory leak warning:
```
37>Generating Code...
37>D:\pkg\wx\MSVC_2022\_3.2.2_2022\wxFormBuilder\src\maingui.cpp(426): warning C4722: 'LoggingStackWalker::~LoggingStackWalker': destructor never returns, potential memory leak
37>Compiling...

Also a big thank you for the log window for the debug version. It is something I was wishing for when I tried to debug earlier versions.
```
