### ISSUE TITLE
Add wxFormBuilder to Flathub

### ISSUE THREAD

**Issue by lebao3105** [wxFormBuilder/wxFormBuilder#797]
I can see that in the Releases section there are always a .flatpak file - which is in fact a Flatpak package. I was searching around Flathub but found no wxFormBuilder there.

Isn't allowing users to install using package managers like Flatpak good?

**Comment by sodevel** [comment]
The packages attached to releases are provided as convenience and are produced automatically by the GitHub CI. Of course it would be nice to have wxFB available on whatever package manager there is, but there are just too many and i simply don't have the ressources to support them.

**Comment by lebao3105** [comment]
Can I publish it to FlatHub myself? Just use the generated ones.

I will look at requirements at FlatHub

**Comment by sodevel** [comment]
I did a quick look at their documentation, they do not favor third party releases. I checked the requirements for publishing, besides some minor issues wxFB currently does not fullfill at least one critical requirement, so there won't be a Flathub release in the near future.

**Comment by lebao3105** [comment]
May I create a repository and distribute wxFB with it?

**Comment by sodevel** [comment]
wxFB is GPL software so of course you can fork the repository. However, i doubt that Flathub will accept such a fork as base for a distribution, their docs say that they don't like this. Because to use your fork for Flathub, you MUST change the application id so that it matches your fork domain. This does create a second wxFB application that is in Flatpak sense a different application to the application that the GitHub CI builds here.

**Comment by lebao3105** [comment]
> wxFB is GPL software so of course you can fork the repository. However, i doubt that Flathub will accept such a fork as base for a distribution, their docs say that they don't like this. Because to use your fork for Flathub, you MUST change the application id so that it matches your fork domain. This does create a second wxFB application that is in Flatpak sense a different application to the application that the GitHub CI builds here.

I did not ask for a fork of wxFB, but a repository to distribute wxFB so that we won't have to make a submit to FlatHub

**Comment by sodevel** [comment]
Sorry, I thought you meant a GitHub repository. I do not know much about how Flatpak works, does Flatpak work like Apt/Yum/Maven and allows to create your own hosting repositories that you can add to Flatpak to download packages from? Basically Flathub but private/non-official? Does Flatpak offer infrastructure for this, like Ubuntu with Launchpad or Fedora with COPR?

Sure you can do this, you just should mark this repository as non-official.

**Comment by lebao3105** [comment]
> Sorry, I thought you meant a GitHub repository. I do not know much about how Flatpak works, does Flatpak work like Apt/Yum/Maven and allows to create your own hosting repositories that you can add to Flatpak to download packages from? Basically Flathub but private/non-official? Does Flatpak offer infrastructure for this, like Ubuntu with Launchpad or Fedora with COPR?
> 
> Sure you can do this, you just should mark this repository as non-official.

Flatpak allows third-party repositories: https://docs.flatpak.org/en/latest/hosting-a-repository.html. Self-hosted though.

Sure, I will mark my repository as unofficial distributing repository.

**Comment by lebao3105** [comment]
Repositories on flatpak is different than those for APT... They do not provide any .flatpak but make it something else from them.

However, I made a repository and the installation ran just fine. Not signed.

```bash
$ flatpak remote-add --no-gpg-verify lebao3105-repo https://lebao3105.github.io/flatpak-repo/repo.platpakrepo
$ flatpak install org.wxformbuilder.wxFormBuilder
```

Now I just need to fetch .flatpak files and do stuff with GitHub Actions when a new release of wxFB is out.
