### ISSUE TITLE
Code generation for wxDataViewTreeCtrl sets an invalid style by default

### ISSUE THREAD

**Issue by dendron2000** [wxFormBuilder/wxFormBuilder#799]
Hi, the code generation for C++ and Python creates something like the following:
```cpp
_myTreeListCtrl = new wxDataViewTreeCtrl( _overviewControlPanel, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0 );
```
Note the zero at the end of the arguments' list.

However, the default constructor for [wxDataViewTreeCtrl](https://docs.wxwidgets.org/3.0/classwx_data_view_tree_ctrl.html#a263a8abb605575c5ab9db5eba259cf89) sets a different style by default:
```cpp
style = wxDV_NO_HEADER|wxDV_ROW_LINES,
```
Without the `wxDV_ROW_LINES` style the wxDataViewTreeCtrl  looks wrong with an invisible and irremovable empty element (it is not the root element, it is something else):
<img width="67" alt="wxBug" src="https://github.com/wxFormBuilder/wxFormBuilder/assets/14233126/46a243df-e905-4075-b949-2eb11f02bf22">

I found this time consuming to find out and fix (as it is not described in much detail anywhere) . This is how the default style should look like:
<img width="454" alt="wxBug2" src="https://github.com/wxFormBuilder/wxFormBuilder/assets/14233126/71e5519b-70e7-4899-bb8f-a1e9d4b67e77">

**Comment by sodevel** [comment]
It is not nice from wxWidgets to behave like that but anyway, i think the policy of wxFB is to use the same parameters by default like wxWidgtes does. This should be easy to fix, will do so if i have some spare time for this, thanks for reporting.
