### ISSUE TITLE
Change a property for many widgets

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#80]
It would be very helpful to have the possibility to change a property for many widgets in the same time. I explain my problem : Currently, if you have to disable the wxALL border for 30 wxStaticText, you must click on each wxStaticText one by one and disable its wxALL border. One possibility would be to select all the widgets we want to change, and their common properties would be shown in the property panel. So, you just have to modify the property you want. Another alternative is to allow the user to create some shortcuts. For my example, you create a shortcut to disable wxALL border, so after you just have to click on each widget and press your shortcut.

Reported by: jfouche

**Comment by jhasse** [comment]
This would be very nice, indeed. But definitely out of scope currently, sorry.

As a workaround is to edit the .fbp file directly with search-and-replace.
