### ISSUE TITLE
Generated C++ code cannot be built if wxNO_IMPLICIT_WXSTRING_ENCODING  is defined

### ISSUE THREAD

**Issue by vadimgrn** [wxFormBuilder/wxFormBuilder#801]
Generated C++ code
`m_button_add->SetBitmap( wxArtProvider::GetBitmap( wxART_PLUS, wxART_BUTTON ) );`

**Compiler errors**
1>D:\usbip-win2\userspace\wusbip\frame.cpp(118,42): error C2664: 'wxBitmap wxArtProvider::GetBitmap(const wxArtID &,const wxArtClient &,const wxSize &)': cannot convert argument 1 from 'const char [11]' to 'const wxArtID &'
1>D:\usbip-win2\userspace\wusbip\frame.cpp(118,53):
1>Reason: cannot convert from 'const char [11]' to 'const wxArtID'
1>D:\usbip-win2\userspace\wusbip\frame.cpp(118,53):
1>Constructor for class 'wxString' is declared 'explicit'

Generated C++ code must be tested when wxNO_IMPLICIT_WXSTRING_ENCODING is defined.
wxART_PLUS, wxART_BUTTON must be wrapped into wxASCII_STR(wxART_PLUS), wxASCII_STR(wxART_BUTTON).

I'm using wxFormBuilder 4.0.0, wxWidgets 3.2.2

**Comment by sodevel** [comment]
This looks like an wxWidgets issue to me, their own code does not behave nice with their own hardening macros enabled :smile:. At least their documentation mentions this potential issue and offers a solution. I will fix that in the future, thanks for reporting.

**Comment by vadimgrn** [comment]
This is definitely not wxWidgets issue, please read https://www.wxwidgets.org/blog/2020/08/implicit_explicit_encoding/
Such explicit conversions of ascii string literals must be applied anywhere in generated C++ code.

**Comment by sodevel** [comment]
The symbols `wxART_PLUS` and the like are not user generated but part of the wxWidgets API designed to be used in that context. As library user i would expect to not need to know the implemention details of these but just use them without failing after touching some switches the library offers.
