### ISSUE TITLE
RFC window not rendering wxStyledTextCtrl

### ISSUE THREAD

**Issue by Xbz-24** [wxFormBuilder/wxFormBuilder#802]
Hi, why does wxDesigner is able to display the wxStyledTextCtrl but Rfc window does not?

this is the from my designer view in wxFormBuilder  

![image](https://github.com/wxFormBuilder/wxFormBuilder/assets/68678258/1c88ac71-bdad-4942-b30d-89937c1a26d8)

and this is how RFC window renders the project

![image](https://github.com/wxFormBuilder/wxFormBuilder/assets/68678258/96ac675f-4d1e-40fc-bed7-92cf8b18e341)

This is the XRC

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<resource xmlns="http://www.wxwidgets.org/wxxrc" version="2.5.3.0">
  <object class="wxFrame" name="editor_frame" subclass="forward_declare">
    <size>901,800</size>
    <style>wxDEFAULT_FRAME_STYLE|wxMAXIMIZE_BOX|wxRESIZE_BORDER|wxSYSTEM_MENU|wxBORDER_THEME|wxTAB_TRAVERSAL|wxVSCROLL</style>
    <bg>#15539e</bg>
    <title>editor</title>
    <centered>1</centered>
    <aui_managed>0</aui_managed>
    <object class="wxBoxSizer" name="bSizer3">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <flag>wxEXPAND</flag>
        <border>5</border>
        <option>1</option>
        <object class="wxBoxSizer" name="bSizer5">
          <orient>wxHORIZONTAL</orient>
          <object class="sizeritem">
            <flag>wxALL|wxEXPAND</flag>
            <border>5</border>
            <option>1</option>
            <object class="wxGenericDirCtrl" name="m_genericDirCtrl3">
              <style>wxDIRCTRL_3D_INTERNAL|wxSUNKEN_BORDER</style>
              <defaultfolder></defaultfolder>
              <filter></filter>
              <defaultfilter>0</defaultfilter>
            </object>
          </object>
          <object class="sizeritem">
            <flag>wxEXPAND</flag>
            <border>5</border>
            <option>1</option>
            <object class="unknown" name="m_scintilla6"/>
          </object>
        </object>
      </object>
      <object class="sizeritem">
        <flag>wxALL|wxEXPAND</flag>
        <border>5</border>
        <option>1</option>
        <object class="wxTextCtrl" name="m_textCtrl1">
          <value></value>
        </object>
      </object>
    </object>
  </object>
</resource>
```

**Comment by sodevel** [comment]
I do not fully understand your post (What is wxDesigner, what is RFC window?), but since you posted a XRC file, i assume you load this file instead of using the generated code. The XRC system is more limited than the generated code and you might lose some functionality by using it, some widgets might not be supported at all.

I checked the XRC documentation, the `wxStyledTextCtrl` is supported, however it has almost no extra properties (i am not familiar with this widget and don't know if this is correct). Sadly, wxFB has no XRC export code for this widget implemented hence it gets exported as `unknown`.

Right now wxFB does not support `wxStyledTextCtrl` with XRC.

**Comment by Xbz-24** [comment]
Interesting, yeah makes sense why the wxStyledTextCtrl scintilla widget was being tagged as object class unknown in the xrc file, 

with wxDesigner I was referring to the designer view where you drag and drop widgets in wxFB, 
with RFC window I meant the live preview of the xrc code being rendered in real time

anyways thank you for your answer as this clarifies why the widgets was not being rendered in the preview
