### ISSUE TITLE
Error creating code in python. Create "true" Instead of "True"

### ISSUE THREAD

**Issue by killo3967** [wxFormBuilder/wxFormBuilder#803]
# -*- coding: utf-8 -*-

###########################################################################
##
###########################################################################

import wx
import wx.xrc
import wx.aui
import wx.grid

###########################################################################
###########################################################################

class frameMain ( wx.Frame ):

	def __init__( self, parent ):
		wx.Frame.__init__ ( self, parent, id = wx.ID_ANY, title = u"COMIC MANAGER", pos = wx.DefaultPosition, size = wx.Size( 1024,768 ), style = wx.DEFAULT_FRAME_STYLE|wx.TAB_TRAVERSAL )

		self.SetSizeHints( wx.DefaultSize, wx.DefaultSize )
		self.DragAcceptFiles( true ) <------------------------------ HERE THE ERROR

		self.menubar_Main = wx.MenuBar( 0 )
		self.menu_Main_File = wx.Menu()

**Comment by sodevel** [comment]
Thanks for reporting, will be fixed in the future. Next time you post some code, please wrap it into code fences so GitHub doesn't interpret this as Markdown and applies fancy formatting.
