### ISSUE TITLE
Code for property grid manager code generated with an error

### ISSUE THREAD

**Issue by dncarachiola** [wxFormBuilder/wxFormBuilder#805]
I've added a property grid manager to my GUI. 
In the import statement for 'propgrid' an "as" is included to "pg"
But in the definition for the propgrid uses "wx.propgrid", and thus is undefined.
Later code uses "pg".

`# -*- coding: utf-8 -*-

###########################################################################
##
###########################################################################

import wx
import wx.xrc
import wx.propgrid as pg

import gettext
_ = gettext.gettext

###########################################################################
###########################################################################

class **************** ( wx.Dialog ):

    def __init__( self, parent ):

		* * *

        self.grid_manager = pg.PropertyGridManager(self, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, wx.propgrid.PGMAN_DEFAULT_STYLE|wx.propgrid.PG_BOLD_MODIFIED|wx.propgrid.PG_DESCRIPTION|wx.propgrid.PG_NO_INTERNAL_BORDER|wx.propgrid.PG_SPLITTER_AUTO_CENTER|wx.propgrid.PG_TOOLTIPS|wx.TAB_TRAVERSAL)
        self.grid_manager.SetExtraStyle( wx.propgrid.PG_EX_HELP_AS_TOOLTIPS )

        self.page = self.grid_manager.AddPage( _(u"Page"), wx.NullBitmap );
        self.task_data = self.page.Append( pg.PropertyCategory( _(u"Task data (req'd)."), _(u"Task data (req'd).") ) )
        self.duration = self.page.Append( pg.FloatProperty( _(u"Duration"), _(u"Duration") ) )

		* * *

		edit.Add( self.grid_manager, 1, wx.EXPAND, 0 )

`

**Comment by sodevel** [comment]
I know basically nothing about Python so why is this beeing done and how can this be fixed?

**Comment by dncarachiola** [comment]
Thank you for addressing this so quickly.
