### ISSUE TITLE
Lua code bug when creating a wxBoxSizer

### ISSUE THREAD

**Issue by Liteb0t** [wxFormBuilder/wxFormBuilder#807]
Incorrect Lua code is generated when i add any box sizer onto a new frame.
The problem is these two lines:
```
UI.:SetSizer( UI.gbSizer2 )
UI.:Layout()
```

After i manually add the frame name to UI, it works as intended:
```
UI.MyFrame1:SetSizer( UI.gbSizer2 )
UI.MyFrame1:Layout()
```

**Comment by sodevel** [comment]
I am surpised that someone is using the Lua generator, i thought this port is dead.

Apparently all sizer are affected but only for top level elements, the code looks correct for sizers added to child elements.
