### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by DarkAlchy** [wxFormBuilder/wxFormBuilder#811]
I generate the code and take the .cpp and .h over to MSVC to replace the hello world two files and get nothing but errors from the code generated by wxFormBuilder with wxwidgets.

One of the errors I remember (out of 69) is that it doesn't like :: in MyFrame.   MyFrame works with the Hello World example.

Another is: Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2653	'MyFrame2': is not a class or namespace name	WxTest	C:\Users\MobRules\source\repos\wxTest\WxTest.cpp	1

**Comment by SpareSimian** [comment]
Give us the step-by-step instructions on how to reproduce this. We don't have enough to work with given your description.

**Comment by DarkAlchy** [comment]
I am not sure I know enough for that.

What I did is take

`// Start of wxWidgets "Hello World" Program
#include <wx/wx.h>
 
class MyApp : public wxApp
{
public:
    bool OnInit() override;
};
 
wxIMPLEMENT_APP(MyApp);
 
class MyFrame : public wxFrame
{
public:
    MyFrame();
 
private:
    void OnHello(wxCommandEvent& event);
    void OnExit(wxCommandEvent& event);
    void OnAbout(wxCommandEvent& event);
};
 
enum
{
    ID_Hello = 1
};
 
bool MyApp::OnInit()
{
    MyFrame *frame = new MyFrame();
    frame->Show(true);
    return true;
}
 
MyFrame::MyFrame()
    : wxFrame(nullptr, wxID_ANY, "Hello World")
{
    wxMenu *menuFile = new wxMenu;
    menuFile->Append(ID_Hello, "&Hello...\tCtrl-H",
                     "Help string shown in status bar for this menu item");
    menuFile->AppendSeparator();
    menuFile->Append(wxID_EXIT);
 
    wxMenu *menuHelp = new wxMenu;
    menuHelp->Append(wxID_ABOUT);
 
    wxMenuBar *menuBar = new wxMenuBar;
    menuBar->Append(menuFile, "&File");
    menuBar->Append(menuHelp, "&Help");
 
    SetMenuBar( menuBar );
 
    CreateStatusBar();
    SetStatusText("Welcome to wxWidgets!");
 
    Bind(wxEVT_MENU, &MyFrame::OnHello, this, ID_Hello);
    Bind(wxEVT_MENU, &MyFrame::OnAbout, this, wxID_ABOUT);
    Bind(wxEVT_MENU, &MyFrame::OnExit, this, wxID_EXIT);
}
 
void MyFrame::OnExit(wxCommandEvent& event)
{
    Close(true);
}
 
void MyFrame::OnAbout(wxCommandEvent& event)
{
    wxMessageBox("This is a wxWidgets Hello World example",
                 "About Hello World", wxOK | wxICON_INFORMATION);
}
 
void MyFrame::OnHello(wxCommandEvent& event)
{
    wxLogMessage("Hello world from wxWidgets!");
}`

to its own file and it compiled, and ran fine.  That means it is not a wxWIdget's, nor Visual Studio 2022 issue.

For the code I hit f8 in wxFB I took the two files it created into the same project that worked.  Nope, tons of errors (I wish VS allowed copying all of the errors).

My hands are being tied by all of this when even Github says it doesn't allow .cpp nor .h files.

.h
`///////////////////////////////////////////////////////////////////////////
// C++ code generated with wxFormBuilder (version 4.1.0-0-g733bf3d)
// http://www.wxformbuilder.org/
//
// PLEASE DO *NOT* EDIT THIS FILE!
///////////////////////////////////////////////////////////////////////////

#pragma once

#include <wx/artprov.h>
#include <wx/xrc/xmlres.h>
#include <wx/bmpbuttn.h>
#include <wx/string.h>
#include <wx/bitmap.h>
#include <wx/image.h>
#include <wx/icon.h>
#include <wx/gdicmn.h>
#include <wx/font.h>
#include <wx/colour.h>
#include <wx/settings.h>
#include <wx/button.h>
#include <wx/textctrl.h>
#include <wx/gbsizer.h>
#include <wx/frame.h>

///////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////
/// Class MyFrame1
///////////////////////////////////////////////////////////////////////////////
class MyFrame1 : public wxFrame
{
	private:

	protected:
		wxBitmapButton* m_bpButton2;
		wxTextCtrl* m_textCtrl1;

		// Virtual event handlers, override them in your derived class
		virtual void fileOpenButton_click( wxCommandEvent& event ) { event.Skip(); }


	public:

		MyFrame1( wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = wxEmptyString, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize( 500,300 ), long style = wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL );

		~MyFrame1();

};

`

.cpp

`///////////////////////////////////////////////////////////////////////////
// C++ code generated with wxFormBuilder (version 4.1.0-0-g733bf3d)
// http://www.wxformbuilder.org/
//
// PLEASE DO *NOT* EDIT THIS FILE!
///////////////////////////////////////////////////////////////////////////

#include "test.h"

///////////////////////////////////////////////////////////////////////////

MyFrame1::MyFrame1( wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style ) : wxFrame( parent, id, title, pos, size, style )
{
	this->SetSizeHints( wxDefaultSize, wxDefaultSize );

	wxGridBagSizer* gbSizer1;
	gbSizer1 = new wxGridBagSizer( 0, 0 );
	gbSizer1->SetFlexibleDirection( wxBOTH );
	gbSizer1->SetNonFlexibleGrowMode( wxFLEX_GROWMODE_SPECIFIED );

	m_bpButton2 = new wxBitmapButton( this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDefaultSize, wxBU_AUTODRAW|wxBORDER_NONE );

	m_bpButton2->SetBitmap( wxBitmap( wxT("downloads/button.png"), wxBITMAP_TYPE_ANY ) );
	gbSizer1->Add( m_bpButton2, wxGBPosition( 0, 0 ), wxGBSpan( 1, 1 ), wxALL, 5 );

	m_textCtrl1 = new wxTextCtrl( this, wxID_ANY, wxEmptyString, wxPoint( -1,7 ), wxSize( 340,50 ), 0 );
	gbSizer1->Add( m_textCtrl1, wxGBPosition( 0, 1 ), wxGBSpan( 1, 1 ), wxALL, 5 );


	this->SetSizer( gbSizer1 );
	this->Layout();

	this->Centre( wxBOTH );

	// Connect Events
	m_bpButton2->Connect( wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler( MyFrame1::fileOpenButton_click ), NULL, this );
}

MyFrame1::~MyFrame1()
{
	// Disconnect Events
	m_bpButton2->Disconnect( wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler( MyFrame1::fileOpenButton_click ), NULL, this );

}
`

First issue is wxFB is not generating the required 

`class MyApp : public wxApp
{
public:
    bool OnInit() override;
};

wxIMPLEMENT_APP(MyApp);

class MyFrame : public wxFrame
{
public:
    MyFrame();

private:
    void OnHello(wxCommandEvent& event);
    void OnExit(wxCommandEvent& event);
    void OnAbout(wxCommandEvent& event);
};

enum
{
    ID_Hello = 1
};

bool MyApp::OnInit()
{
    MyFrame* frame = new MyFrame();
    frame->Show(true);
    return true;
}`

I add that and still no dice.

**Comment by DarkAlchy** [comment]
sorry about having to upload like that but GitHub does not allow files of .h nor cpp to be stuck here and the 
![image](https://github.com/wxFormBuilder/wxFormBuilder/assets/10561690/e9c495da-f9dd-4327-a730-66d563100090)
does work as a real code block.

**Comment by SpareSimian** [comment]
When uploading code to share with mailing lists, I recommend https://pastebin.com/

You should be able to upload source code by adding a .txt extension to the end.

**Comment by SpareSimian** [comment]
Also add a .txt to your .vcxproj file so we can see that. Or zip the whole project and put it up somewhere where we can download it.

**Comment by DarkAlchy** [comment]
> Also add a .txt to your .vcxproj file so we can see that. Or zip the whole project and put it up somewhere where we can download it.

Here is everything: https://drive.google.com/file/d/1zCWcVnJ10AZ8gqcCqG3I0rBRw_s7DWyW/view?usp=sharing

**Comment by SpareSimian** [comment]
Your nowhere.cpp looks like the output of wxFB and then edited. Don't do that. Never edit the output. Derive from it in a different file and modify the derived class. The edited file has errors caused by pasting in a method that should be in a derived class.

What I do is have wxFB name my classes with "Gui" on the end of the name, so you'd have MyFrameGui. Then my derived class is called MyFrame. So after you renamed the class in wxFB, change the declaration in main.cpp so that it says "class MyFrame : public MyFrameGui". You'll need to #include "nowhere.h" in main.cpp.

**Comment by DarkAlchy** [comment]
those Nowhere files are not edited but anyway if you look the code it is generating is nothing like the hello world from the wxWidgets code.

I have tried for two days to get FB code to work in VS and forget it.  wxWidgets works just not the code this outputs.



Take a glance as the frame

MyFrame::MyFrame()
    : wxFrame(nullptr, wxID_ANY, "Hello World")
{
    wxMenu* menuFile = new wxMenu;
    menuFile->Append(ID_Hello, "&Hello...\tCtrl-H",
        "Help string shown in status bar for this menu item");
    menuFile->AppendSeparator();
    menuFile->Append(wxID_EXIT);

    wxMenu* menuHelp = new wxMenu;
    menuHelp->Append(wxID_ABOUT);

    wxMenuBar* menuBar = new wxMenuBar;
    menuBar->Append(menuFile, "&File");
    menuBar->Append(menuHelp, "&Help");

    SetMenuBar(menuBar);

    CreateStatusBar();
    SetStatusText("Welcome to wxWidgets!");

    Bind(wxEVT_MENU, &MyFrame::OnHello, this, ID_Hello);
    Bind(wxEVT_MENU, &MyFrame::OnAbout, this, wxID_ABOUT);
    Bind(wxEVT_MENU, &MyFrame::OnExit, this, wxID_EXIT);
}


compared to FB code for the frame:

MyFrame::MyFrame( wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style ) : wxFrame( parent, id, title, pos, size, style )
{
	this->SetSizeHints( wxDefaultSize, wxDefaultSize );


	this->Centre( wxBOTH );
}

MyFrame::~MyFrame()
{
}

I am beyond frustrated now as there are no documentation on this for VS and no videos on this all is for Python stuff.  I used this, along with wxWidgets, 12-18 years ago in that time frame and I just never had these issues then.  The net was a smaller place YET I could actually find information I wanted.  With Youtube so prevalent now you would think, but no.

**Comment by DarkAlchy** [comment]
I managed to get it down to 11 errors now but mine is just along for the ride it is not used.

![image](https://github.com/wxFormBuilder/wxFormBuilder/assets/10561690/38f1293d-fb22-4fee-8e68-993ffccfcb71)

See that first error?  That is my custom code I had wxFB do and it inserted here:

![image](https://github.com/wxFormBuilder/wxFormBuilder/assets/10561690/fffd8bd8-1737-4534-8933-8ff231a820b5)

**Comment by SpareSimian** [comment]
Ah, you're using the code insertion feature with wxFB. I don't do that. I use a derived class to add code.

You can't insert entire methods. You can only insert snippets inside of existing methods. Notice how you now have a method inside a method. That's illegal in C++.

**Comment by DarkAlchy** [comment]
Yep, and no matter how hard I tried I couldn't do it.  What do you suggest in this case as the code should sit by itself but this is where it gets confusing because wxFB should have way better management for this by now.  The last time I used this was around 2012 so in 12 years I come back to all of this to see it has stagnated.  A bit sad at that as all I see is Python and that horrid webui being used.  imo, no browser should be used as a gui.

Anyway, the other issues I removed as they were just missing header files, but then I am unsure how to add them since those generated by wxFB are not to be touched.  I finally just threw them in before the others in main and that worked leaving me 

![image](https://github.com/wxFormBuilder/wxFormBuilder/assets/10561690/49d98e27-658f-4b54-9fa8-9c95e210b656)

The middle "this" will go away when I can understand how you manage it then the first will go away too then that will leave the last one. :/

**Comment by DarkAlchy** [comment]
I finally manage to remove those errors, then tried to start wxFB gui and POP. far too many errors to list.  Just something about what wxFB wrote it despises and I do not know how to fix it so it plays nice.

**Comment by SpareSimian** [comment]
It works quite well for me, and it's kept up with changes to the wxWidgets library. There's minor support for custom controls that I've used, but that's an expert topic. The code insertion feature is another advanced topic and you need to understand the language well to use it. Stick to using a derived class to customize the code it creates. I'm considering adding a Python wrapper to my C++ library so the Python support will be useful.

**Comment by DarkAlchy** [comment]
When I use Python it is for AI and ML and nothing else so no need for me.

I got it to compile and work only I need to see why I am getting an image error 15 now for the png.  I think I saw a png header file but not sure.

**Comment by DarkAlchy** [comment]
![image](https://github.com/wxFormBuilder/wxFormBuilder/assets/10561690/35c387ae-fad8-4a4b-8efc-0f463705f773)
I needed to add wxImage::AddHandler(new wxPNGHandler); before it is initialized, so I am not sure how to do that if I am not allowed to touch those two files and the custom codes puts it too late.

**Comment by SpareSimian** [comment]
Add the PNG handler in your application init, before the frame is created. Put the handler object in the application object.

**Comment by DarkAlchy** [comment]
got it all working now save one issue which is a wxwidget's issue as I shrink my panel then enlarge it and my button loses its transparency. 

Since I am having to work with all these separate files where wxFB doesn't even know they exist why use wxFB?  I am seriously asking, and not trying to be mean or anything because I am working in the blind.  Only thing I can now use wxFB for is to create the item then that is about it.  A lot of this is happening outside the two files it creates, and some of this doesn't even reference anything in those two files (a lot of forced custom code).

**Comment by SpareSimian** [comment]
I use it to mock up some fairly complicated panels with a LOT of buttons and knobs and display fields. I work in factory automation and it's pretty nice for putting together a control panel to operate lots of motors and see what they're doing.

**Comment by DarkAlchy** [comment]
Well, in my use case the basic knobs, buttons, etc... are far too primitive so I am forced to use custom code and that is where this falls apart.  Not just this, though, but every last one I checked.  I could not check qt (only one I did not try) because I couldn't even get a copy without having to log in.  I skipped it.


Well, thank you for all your help as it was invaluable to me.
