### ISSUE TITLE
Programming in python in three layers

### ISSUE THREAD

**Issue by killo3967** [wxFormBuilder/wxFormBuilder#812]
How can I program in 3 levels. That is, a program in which the entire graphical environment is defined, another in which the events are defined and another in which the actions to be taken are defined.
Is this possible or am I talking nonsense.

**Comment by SpareSimian** [comment]
This is the wrong place to ask this. Your question is not a bug or feature request for wxFormBuilder. Ask on Reddit, Facebook, or one of the many programming support web forums.

**Comment by killo3967** [comment]
Yhansk and sorry.
