### ISSUE TITLE
Setting DataViewCtrl Column property `ellipsize` to "wxELLIPSIZE_NONE" will lead to an redundant comma in generated python code

### ISSUE THREAD

**Issue by lucifersteph** [wxFormBuilder/wxFormBuilder#813]
![image](https://github.com/wxFormBuilder/wxFormBuilder/assets/2692580/315b416f-b8c1-461b-a857-f6da772e3096)
![image](https://github.com/wxFormBuilder/wxFormBuilder/assets/2692580/2f0198d0-984b-436f-88d7-0c4eb6c750e1)

**Comment by sodevel** [comment]
Thanks for reporting. Apparently there are even more locations that add unnecessary semicolons, i will fix these as well soon.
