### ISSUE TITLE
wxStaticBoxSizer incorrect parent in Lua

### ISSUE THREAD

**Issue by SwiftyJ** [wxFormBuilder/wxFormBuilder#829]
Hi, In Lua wxStaticBoxSizer uses the frame as a parent when placed on a panel within a frame instead of the panel. In the code below the last line should be:
UI.sbSizer15 = wx.wxStaticBoxSizer( wx.wxStaticBox( UI.m_panel4, wx.wxID_ANY, "label" ), wx.wxVERTICAL )

`UI = {}
-- create MyFrame2
UI.MyFrame2 = wx.wxFrame (wx.NULL, wx.wxID_ANY, "", wx.wxDefaultPosition, wx.wxSize( 500,300 ), wx.wxDEFAULT_FRAME_STYLE+wx.wxTAB_TRAVERSAL )
	UI.MyFrame2:SetSizeHints( wx.wxDefaultSize, wx.wxDefaultSize )
	UI.bSizer5 = wx.wxBoxSizer( wx.wxVERTICAL )
	UI.m_panel4 = wx.wxPanel( UI.MyFrame2, wx.wxID_ANY, wx.wxDefaultPosition, wx.wxDefaultSize, wx.wxTAB_TRAVERSAL )
	UI.sbSizer15 = wx.wxStaticBoxSizer( wx.wxStaticBox( UI.MyFrame2, wx.wxID_ANY, "label" ), wx.wxVERTICAL )
`

When using a notebook this causes issues

**Comment by sodevel** [comment]
Looks like the wxWidgets parent processing for Lua is severely broken, i will look into this, thanks for reporting.
