### ISSUE TITLE
wxSplitterWindow should not require a sizer as parent?

### ISSUE THREAD

**Issue by DRNadler** [wxFormBuilder/wxFormBuilder#837]
The wxWidgets splitter.cpp sample uses wxSplitterWindow with a wxFrame as the parent.
Shouldn't wxFormBuilder allow this?
Thanks!

**Comment by sodevel** [comment]
wxWidgets supports 3 different layout systems, absolute positioning, constraint based positioning and sizer based positioning, wxFB only supports sizer based positioning. The wxWidgets samples rely on a special case for top level windows, if such a window contains only a single child, it will be sized to cover the whole window. Implementing this for wxFB is not so easy so it was not done. I do not really see a need for this, adding a sizer that does the same job is trivial.

**Comment by DRNadler** [comment]
Thanks. I need to have an user-draggable separator between sizing areas so user can adjust which areas get more or less space. Would you recommend a better way to do this than using wxSplitterWindow?
Thanks again!

**Comment by DRNadler** [comment]
Never mind, I found out this works mostly automatically using AUI.
If only there was a concise AUI overview, between the nice AUI intro video and the too-many-notes AUI sample app...
Thanks for wxFormBuilder and your help!
