### ISSUE TITLE
HOWTO: share a wxMenu as both a top-level menubar item *and* a menu submenu

### ISSUE THREAD

**Issue by robertroessler** [wxFormBuilder/wxFormBuilder#846]
To be clear, I already have most of what I want [in terms of menus] working... in particular, I am definitely taking advantage of being able to define a menu to "hang off" of a menubar *and* at runtime pop up that same menu [object] when I want to use it as a "context menu" instead.

But now I have another wrinkle on this: I would like to have a menu to both appear as a top-level item on the menubar *and* as a submenu under another menubar menu... I think I can see how to do this at runtime, but it would involve dynamically changing a wxMenu object, which I would rather not do - creating these and manipulating them is what wxFB is there for. ;)

So what I am really asking is: is there a way to describe this linking structure *symbolically* within the graphically-oriented wxFB?  As in, what would I *say* to have an already-existing menubar menu appear also as a submenu under another menubar menu [within wxFB], without actually making a separate copy?

If anyone is wondering "why?" here, it is because I am attempting to evolve a previously "all context menus, all the time" UI into one that allows people that are more comfortable with menubars to also get at the same functionality.

Thanks for any wxFB insights into this [possibly weird] corner case.

**Comment by sodevel** [comment]
First one question, do you really want to use the same `wxMenu` object twice in your use case? I don't think wxWidgets does allow such double usage of a `wxMenu` object, but even if it does, such linking option does not exist in wxFB.

I am quite sure you have to create two identical `wxMenu` objects if you want to use identical menus in two places. wxFB can save you some copy-paste work if you create a `MenuBar` form and define your `wxMenu` there, at runtime you can instantiate two of these `wxMenuBar` and move the contained `wxMenu` to the desired target location.

A complete "static" solution by just using wxFB is not possible.

**Comment by robertroessler** [comment]
Thanks for a responsive and comprehensive answer to my question... like I said in the "why?" part of my post, this is an unnatural and unusual situation - so I am not surprised there isn't a way of doing it directly in wxFB.
I talked things over with the user(s) who had _thought_ they were interested in this possibility, and they have decided to stick with the context menus for now. ;)
