### ISSUE TITLE
Python code styling isssues

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#86]
When generating Python code with the 3.1.61 beta, there are some code styling error:

If “id” is not specified, is possible to omit it, instead of using wx.ID_ANY.
Same applies to an empty title (why use wx.EMPTY_STRING?) and the default position and/or style.
It would be better to always use keyword arguments, also in the controls code.
As with XRC the first sizer is not necessary and can be skipped.
There are empty spaces that should be removed (see attached file).
Size can be specified without wx.Size(), just use a tuple!.
I attach a file with both the generated code and how it should be.

Reported by: jfouche

**Comment by jhasse** [comment]
Please reopen if you still think this is a problem.
