### ISSUE TITLE
wxArtProvider based bitmap source

### ISSUE THREAD

**Issue by wxfbint** [wxFormBuilder/wxFormBuilder#9]
wxArtProvider should be supported as a bitmap source for menus/tools/buttons as well. Now only RC resource files or simple bitmap files stored on a disk are supported as a bitmap sources. Unfortunately, both of these ways are platform specific (RC files are available only at MS platforms, and file-based resources lacks the portability due to different forms of file paths). Moreover, the wxArtProvider provides a common (default) bitmaps/icons sets for target platform without need of distributing the graphics files together with the source code.

Reported by: jfouche

**Comment by sodevel** [comment]
Implemented in current release
